/*
 * CypressTestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Message type.
 */
public class Message {
    private int code;
    private String text;

    /**
     * Default constructor.
     */
    public Message() {
    }

    /**
     * Initialization constructor.
     * @param  code  int value for code.
     * @param  text  String value for text.
     */
    public Message(
            int code,
            String text) {
        this.code = code;
        this.text = text;
    }

    /**
     * Getter for Code.
     * @return Returns the int
     */
    @JsonGetter("code")
    public int getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * @param code Value for int
     */
    @JsonSetter("code")
    public void setCode(int code) {
        this.code = code;
    }

    /**
     * Getter for Text.
     * @return Returns the String
     */
    @JsonGetter("text")
    public String getText() {
        return text;
    }

    /**
     * Setter for Text.
     * @param text Value for String
     */
    @JsonSetter("text")
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Converts this Message into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Message [" + "code=" + code + ", text=" + text + "]";
    }

    /**
     * Builds a new {@link Message.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Message.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(code, text);
        return builder;
    }

    /**
     * Class to build instances of {@link Message}.
     */
    public static class Builder {
        private int code;
        private String text;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  code  int value for code.
         * @param  text  String value for text.
         */
        public Builder(int code, String text) {
            this.code = code;
            this.text = text;
        }

        /**
         * Setter for code.
         * @param  code  int value for code.
         * @return Builder
         */
        public Builder code(int code) {
            this.code = code;
            return this;
        }

        /**
         * Setter for text.
         * @param  text  String value for text.
         * @return Builder
         */
        public Builder text(String text) {
            this.text = text;
            return this;
        }

        /**
         * Builds a new {@link Message} object using the set fields.
         * @return {@link Message}
         */
        public Message build() {
            return new Message(code, text);
        }
    }
}
