/*
 * SwaggerPetstoreOpenApi30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore3.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import io.swagger.petstore3.DateTimeHelper;
import java.time.LocalDateTime;
import java.util.Map;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * This is a model class for Order type.
 */
public class Order {
    private Long id;
    private Long petId;
    private Integer quantity;
    private LocalDateTime shipDate;
    private OrderStatus status;
    private Boolean complete;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Order() {
    }

    /**
     * Initialization constructor.
     * @param  id  Long value for id.
     * @param  petId  Long value for petId.
     * @param  quantity  Integer value for quantity.
     * @param  shipDate  LocalDateTime value for shipDate.
     * @param  status  OrderStatus value for status.
     * @param  complete  Boolean value for complete.
     */
    public Order(
            Long id,
            Long petId,
            Integer quantity,
            LocalDateTime shipDate,
            OrderStatus status,
            Boolean complete) {
        this.id = id;
        this.petId = petId;
        this.quantity = quantity;
        this.shipDate = shipDate;
        this.status = status;
        this.complete = complete;
    }

    /**
     * Getter for Id.
     * @return Returns the Long
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "id")
    public Long getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for Long
     */
    @JsonSetter("id")
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for PetId.
     * @return Returns the Long
     */
    @JsonGetter("petId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "petId")
    public Long getPetId() {
        return petId;
    }

    /**
     * Setter for PetId.
     * @param petId Value for Long
     */
    @JsonSetter("petId")
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * Getter for Quantity.
     * @return Returns the Integer
     */
    @JsonGetter("quantity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "quantity")
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * Setter for Quantity.
     * @param quantity Value for Integer
     */
    @JsonSetter("quantity")
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Getter for ShipDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("shipDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    @XmlJavaTypeAdapter(DateTimeHelper.Rfc8601DateTimeAdapter.class)
    @XmlElement(name = "shipDate")
    public LocalDateTime getShipDate() {
        return shipDate;
    }

    /**
     * Setter for ShipDate.
     * @param shipDate Value for LocalDateTime
     */
    @JsonSetter("shipDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setShipDate(LocalDateTime shipDate) {
        this.shipDate = shipDate;
    }

    /**
     * Getter for Status.
     * Order Status
     * @return Returns the OrderStatus
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "status")
    public OrderStatus getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Order Status
     * @param status Value for OrderStatus
     */
    @JsonSetter("status")
    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    /**
     * Getter for Complete.
     * @return Returns the Boolean
     */
    @JsonGetter("complete")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "complete")
    public Boolean getComplete() {
        return complete;
    }

    /**
     * Setter for Complete.
     * @param complete Value for Boolean
     */
    @JsonSetter("complete")
    public void setComplete(Boolean complete) {
        this.complete = complete;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Order into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Order [" + "id=" + id + ", petId=" + petId + ", quantity=" + quantity
                + ", shipDate=" + shipDate + ", status=" + status + ", complete=" + complete
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Order.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Order.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .petId(getPetId())
                .quantity(getQuantity())
                .shipDate(getShipDate())
                .status(getStatus())
                .complete(getComplete());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Order}.
     */
    public static class Builder {
        private Long id;
        private Long petId;
        private Integer quantity;
        private LocalDateTime shipDate;
        private OrderStatus status;
        private Boolean complete;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for id.
         * @param  id  Long value for id.
         * @return Builder
         */
        public Builder id(Long id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for petId.
         * @param  petId  Long value for petId.
         * @return Builder
         */
        public Builder petId(Long petId) {
            this.petId = petId;
            return this;
        }

        /**
         * Setter for quantity.
         * @param  quantity  Integer value for quantity.
         * @return Builder
         */
        public Builder quantity(Integer quantity) {
            this.quantity = quantity;
            return this;
        }

        /**
         * Setter for shipDate.
         * @param  shipDate  LocalDateTime value for shipDate.
         * @return Builder
         */
        public Builder shipDate(LocalDateTime shipDate) {
            this.shipDate = shipDate;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  OrderStatus value for status.
         * @return Builder
         */
        public Builder status(OrderStatus status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for complete.
         * @param  complete  Boolean value for complete.
         * @return Builder
         */
        public Builder complete(Boolean complete) {
            this.complete = complete;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Order} object using the set fields.
         * @return {@link Order}
         */
        public Order build() {
            Order model =
                    new Order(id, petId, quantity, shipDate, status, complete);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
