/*
 * SwaggerPetstoreOpenApi30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore3.authentication;

import io.swagger.petstore3.models.OauthScopePetstoreAuth;
import io.swagger.petstore3.models.OauthToken;
import java.util.List;
import java.util.Map;

/**
 * Interface for Implicit OAuth 2.
 */
public interface PetstoreAuthCredentials {

    /**
     * String value for oauthClientId.
     * @return oauthClientId
     */
    String getOauthClientId();

    /**
     * String value for oauthRedirectUri.
     * @return oauthRedirectUri
     */
    String getOauthRedirectUri();

    /**
     * OauthToken value for oauthToken.
     * @return oauthToken
     */
    OauthToken getOauthToken();

    /**
     * List of OauthScopePetstoreAuth value for oauthScopes.
     * @return oauthScopes
     */
    List<OauthScopePetstoreAuth> getOauthScopes();

    /**
     * Checks if provided credentials matched with existing ones.
     * @param oauthClientId String value for credentials.
     * @param oauthRedirectUri String value for credentials.
     * @param oauthToken OauthToken value for credentials.
     * @param oauthScopes List of OauthScopePetstoreAuth value for credentials.
     * @return true if credentials matched.
     */
    boolean equals(String oauthClientId, String oauthRedirectUri, OauthToken oauthToken,
            List<OauthScopePetstoreAuth> oauthScopes);

    /**
     * Build an authorization URL for taking the user's consent to access data.
     * @param state An opaque state string
     * @param additionalParameters Additional parameters to add the the authorization URL
     * @return Authorization URL
     */
    String buildAuthorizationUrl(final String state,
            final Map<String, String> additionalParameters);
    
    /**
     * Build an authorization URL for taking the user's consent to access data.
     * @return Authorization URL
     */
    String buildAuthorizationUrl();

    /**
     * Build an authorization URL for taking the user's consent to access data.
     * @param state An opaque state string
     * @return Authorization URL
     */
    String buildAuthorizationUrl(final String state);

    /**
     * Has the OAuth token expired?.
     * @return True if expired
     */
    boolean isTokenExpired();
}
