/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Broker1 type.
 */
public class Broker1 {
    private Integer brokerID;
    private OptionalNullable<BrokerTypeEnum> brokerType;
    private String contact;
    private String phone;
    private String eMail;
    private String fax;
    private String accountNumber;
    private String organization;
    private String street;
    private String locale;
    private String city;
    private String region;
    private String postalCode;
    private String country;
    private String identificationNumber;
    private OptionalNullable<IdentificationNumberTypeEnum> identificationNumberType;

    /**
     * Default constructor.
     */
    public Broker1() {
        brokerID = 0;
    }

    /**
     * Initialization constructor.
     * @param  brokerID  Integer value for brokerID.
     * @param  brokerType  BrokerTypeEnum value for brokerType.
     * @param  contact  String value for contact.
     * @param  phone  String value for phone.
     * @param  eMail  String value for eMail.
     * @param  fax  String value for fax.
     * @param  accountNumber  String value for accountNumber.
     * @param  organization  String value for organization.
     * @param  street  String value for street.
     * @param  locale  String value for locale.
     * @param  city  String value for city.
     * @param  region  String value for region.
     * @param  postalCode  String value for postalCode.
     * @param  country  String value for country.
     * @param  identificationNumber  String value for identificationNumber.
     * @param  identificationNumberType  IdentificationNumberTypeEnum value for
     *         identificationNumberType.
     */
    public Broker1(
            Integer brokerID,
            BrokerTypeEnum brokerType,
            String contact,
            String phone,
            String eMail,
            String fax,
            String accountNumber,
            String organization,
            String street,
            String locale,
            String city,
            String region,
            String postalCode,
            String country,
            String identificationNumber,
            IdentificationNumberTypeEnum identificationNumberType) {
        this.brokerID = brokerID;
        this.brokerType = OptionalNullable.of(brokerType);
        this.contact = contact;
        this.phone = phone;
        this.eMail = eMail;
        this.fax = fax;
        this.accountNumber = accountNumber;
        this.organization = organization;
        this.street = street;
        this.locale = locale;
        this.city = city;
        this.region = region;
        this.postalCode = postalCode;
        this.country = country;
        this.identificationNumber = identificationNumber;
        this.identificationNumberType = OptionalNullable.of(identificationNumberType);
    }

    /**
     * Initialization constructor.
     * @param  brokerID  Integer value for brokerID.
     * @param  brokerType  BrokerTypeEnum value for brokerType.
     * @param  contact  String value for contact.
     * @param  phone  String value for phone.
     * @param  eMail  String value for eMail.
     * @param  fax  String value for fax.
     * @param  accountNumber  String value for accountNumber.
     * @param  organization  String value for organization.
     * @param  street  String value for street.
     * @param  locale  String value for locale.
     * @param  city  String value for city.
     * @param  region  String value for region.
     * @param  postalCode  String value for postalCode.
     * @param  country  String value for country.
     * @param  identificationNumber  String value for identificationNumber.
     * @param  identificationNumberType  IdentificationNumberTypeEnum value for
     *         identificationNumberType.
     */

    protected Broker1(Integer brokerID, OptionalNullable<BrokerTypeEnum> brokerType, String contact,
            String phone, String eMail, String fax, String accountNumber, String organization,
            String street, String locale, String city, String region, String postalCode,
            String country, String identificationNumber,
            OptionalNullable<IdentificationNumberTypeEnum> identificationNumberType) {
        this.brokerID = brokerID;
        this.brokerType = brokerType;
        this.contact = contact;
        this.phone = phone;
        this.eMail = eMail;
        this.fax = fax;
        this.accountNumber = accountNumber;
        this.organization = organization;
        this.street = street;
        this.locale = locale;
        this.city = city;
        this.region = region;
        this.postalCode = postalCode;
        this.country = country;
        this.identificationNumber = identificationNumber;
        this.identificationNumberType = identificationNumberType;
    }

    /**
     * Getter for BrokerID.
     * Export broker who will handle the shipment.
     * @return Returns the Integer
     */
    @JsonGetter("BrokerID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "BrokerID")
    public Integer getBrokerID() {
        return brokerID;
    }

    /**
     * Setter for BrokerID.
     * Export broker who will handle the shipment.
     * @param brokerID Value for Integer
     */
    @JsonSetter("BrokerID")
    public void setBrokerID(Integer brokerID) {
        this.brokerID = brokerID;
    }

    /**
     * Internal Getter for BrokerType.
     * Export broker who will handle the shipment.
     * @return Returns the Internal BrokerTypeEnum
     */
    @JsonGetter("BrokerType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<BrokerTypeEnum> internalGetBrokerType() {
        return this.brokerType;
    }

    /**
     * Getter for BrokerType.
     * Export broker who will handle the shipment.
     * @return Returns the BrokerTypeEnum
     */
    @XmlElement(name = "BrokerType")
    public BrokerTypeEnum getBrokerType() {
        return OptionalNullable.getFrom(brokerType);
    }

    /**
     * Setter for BrokerType.
     * Export broker who will handle the shipment.
     * @param brokerType Value for BrokerTypeEnum
     */
    @JsonSetter("BrokerType")
    public void setBrokerType(BrokerTypeEnum brokerType) {
        this.brokerType = OptionalNullable.of(brokerType);
    }

    /**
     * UnSetter for BrokerType.
     * Export broker who will handle the shipment.
     */
    public void unsetBrokerType() {
        brokerType = null;
    }

    /**
     * Getter for Contact.
     * Broker contact who will handle the shipment.
     * @return Returns the String
     */
    @JsonGetter("Contact")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Contact")
    public String getContact() {
        return contact;
    }

    /**
     * Setter for Contact.
     * Broker contact who will handle the shipment.
     * @param contact Value for String
     */
    @JsonSetter("Contact")
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * Getter for Phone.
     * Export broker phone number.
     * @return Returns the String
     */
    @JsonGetter("Phone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Phone")
    public String getPhone() {
        return phone;
    }

    /**
     * Setter for Phone.
     * Export broker phone number.
     * @param phone Value for String
     */
    @JsonSetter("Phone")
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for EMail.
     * Export broker email address.
     * @return Returns the String
     */
    @JsonGetter("EMail")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "EMail")
    public String getEMail() {
        return eMail;
    }

    /**
     * Setter for EMail.
     * Export broker email address.
     * @param eMail Value for String
     */
    @JsonSetter("EMail")
    public void setEMail(String eMail) {
        this.eMail = eMail;
    }

    /**
     * Getter for Fax.
     * Export broker fax number.
     * @return Returns the String
     */
    @JsonGetter("Fax")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Fax")
    public String getFax() {
        return fax;
    }

    /**
     * Setter for Fax.
     * Export broker fax number.
     * @param fax Value for String
     */
    @JsonSetter("Fax")
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * Getter for AccountNumber.
     * Export broker account number.
     * @return Returns the String
     */
    @JsonGetter("AccountNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "AccountNumber")
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Setter for AccountNumber.
     * Export broker account number.
     * @param accountNumber Value for String
     */
    @JsonSetter("AccountNumber")
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Getter for Organization.
     * Export broker organization name.
     * @return Returns the String
     */
    @JsonGetter("Organization")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Organization")
    public String getOrganization() {
        return organization;
    }

    /**
     * Setter for Organization.
     * Export broker organization name.
     * @param organization Value for String
     */
    @JsonSetter("Organization")
    public void setOrganization(String organization) {
        this.organization = organization;
    }

    /**
     * Getter for Street.
     * Export broker address street.
     * @return Returns the String
     */
    @JsonGetter("Street")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Street")
    public String getStreet() {
        return street;
    }

    /**
     * Setter for Street.
     * Export broker address street.
     * @param street Value for String
     */
    @JsonSetter("Street")
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * Getter for Locale.
     * Export broker address locale.
     * @return Returns the String
     */
    @JsonGetter("Locale")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Locale")
    public String getLocale() {
        return locale;
    }

    /**
     * Setter for Locale.
     * Export broker address locale.
     * @param locale Value for String
     */
    @JsonSetter("Locale")
    public void setLocale(String locale) {
        this.locale = locale;
    }

    /**
     * Getter for City.
     * Export broker address city name.
     * @return Returns the String
     */
    @JsonGetter("City")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "City")
    public String getCity() {
        return city;
    }

    /**
     * Setter for City.
     * Export broker address city name.
     * @param city Value for String
     */
    @JsonSetter("City")
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for Region.
     * Export broker address region.
     * @return Returns the String
     */
    @JsonGetter("Region")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Region")
    public String getRegion() {
        return region;
    }

    /**
     * Setter for Region.
     * Export broker address region.
     * @param region Value for String
     */
    @JsonSetter("Region")
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * Getter for PostalCode.
     * Export broker address postal code.
     * @return Returns the String
     */
    @JsonGetter("PostalCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PostalCode")
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Setter for PostalCode.
     * Export broker address postal code.
     * @param postalCode Value for String
     */
    @JsonSetter("PostalCode")
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * Getter for Country.
     * Export broker address country code.
     * @return Returns the String
     */
    @JsonGetter("Country")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Country")
    public String getCountry() {
        return country;
    }

    /**
     * Setter for Country.
     * Export broker address country code.
     * @param country Value for String
     */
    @JsonSetter("Country")
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for IdentificationNumber.
     * The Tax Identification Number of the individual acting as broker.
     * @return Returns the String
     */
    @JsonGetter("IdentificationNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "IdentificationNumber")
    public String getIdentificationNumber() {
        return identificationNumber;
    }

    /**
     * Setter for IdentificationNumber.
     * The Tax Identification Number of the individual acting as broker.
     * @param identificationNumber Value for String
     */
    @JsonSetter("IdentificationNumber")
    public void setIdentificationNumber(String identificationNumber) {
        this.identificationNumber = identificationNumber;
    }

    /**
     * Internal Getter for IdentificationNumberType.
     * The Tax Identification Number Type of the individual acting as broker.
     * @return Returns the Internal IdentificationNumberTypeEnum
     */
    @JsonGetter("IdentificationNumberType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<IdentificationNumberTypeEnum> internalGetIdentificationNumberType() {
        return this.identificationNumberType;
    }

    /**
     * Getter for IdentificationNumberType.
     * The Tax Identification Number Type of the individual acting as broker.
     * @return Returns the IdentificationNumberTypeEnum
     */
    @XmlElement(name = "IdentificationNumberType")
    public IdentificationNumberTypeEnum getIdentificationNumberType() {
        return OptionalNullable.getFrom(identificationNumberType);
    }

    /**
     * Setter for IdentificationNumberType.
     * The Tax Identification Number Type of the individual acting as broker.
     * @param identificationNumberType Value for IdentificationNumberTypeEnum
     */
    @JsonSetter("IdentificationNumberType")
    public void setIdentificationNumberType(IdentificationNumberTypeEnum identificationNumberType) {
        this.identificationNumberType = OptionalNullable.of(identificationNumberType);
    }

    /**
     * UnSetter for IdentificationNumberType.
     * The Tax Identification Number Type of the individual acting as broker.
     */
    public void unsetIdentificationNumberType() {
        identificationNumberType = null;
    }

    /**
     * Converts this Broker1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Broker1 [" + "brokerID=" + brokerID + ", brokerType=" + brokerType + ", contact="
                + contact + ", phone=" + phone + ", eMail=" + eMail + ", fax=" + fax
                + ", accountNumber=" + accountNumber + ", organization=" + organization
                + ", street=" + street + ", locale=" + locale + ", city=" + city + ", region="
                + region + ", postalCode=" + postalCode + ", country=" + country
                + ", identificationNumber=" + identificationNumber + ", identificationNumberType="
                + identificationNumberType + "]";
    }

    /**
     * Builds a new {@link Broker1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Broker1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .brokerID(getBrokerID())
                .contact(getContact())
                .phone(getPhone())
                .eMail(getEMail())
                .fax(getFax())
                .accountNumber(getAccountNumber())
                .organization(getOrganization())
                .street(getStreet())
                .locale(getLocale())
                .city(getCity())
                .region(getRegion())
                .postalCode(getPostalCode())
                .country(getCountry())
                .identificationNumber(getIdentificationNumber());
        builder.brokerType = internalGetBrokerType();
        builder.identificationNumberType = internalGetIdentificationNumberType();
        return builder;
    }

    /**
     * Class to build instances of {@link Broker1}.
     */
    public static class Builder {
        private Integer brokerID = 0;
        private OptionalNullable<BrokerTypeEnum> brokerType;
        private String contact;
        private String phone;
        private String eMail;
        private String fax;
        private String accountNumber;
        private String organization;
        private String street;
        private String locale;
        private String city;
        private String region;
        private String postalCode;
        private String country;
        private String identificationNumber;
        private OptionalNullable<IdentificationNumberTypeEnum> identificationNumberType;



        /**
         * Setter for brokerID.
         * @param  brokerID  Integer value for brokerID.
         * @return Builder
         */
        public Builder brokerID(Integer brokerID) {
            this.brokerID = brokerID;
            return this;
        }

        /**
         * Setter for brokerType.
         * @param  brokerType  BrokerTypeEnum value for brokerType.
         * @return Builder
         */
        public Builder brokerType(BrokerTypeEnum brokerType) {
            this.brokerType = OptionalNullable.of(brokerType);
            return this;
        }

        /**
         * UnSetter for brokerType.
         * @return Builder
         */
        public Builder unsetBrokerType() {
            brokerType = null;
            return this;
        }

        /**
         * Setter for contact.
         * @param  contact  String value for contact.
         * @return Builder
         */
        public Builder contact(String contact) {
            this.contact = contact;
            return this;
        }

        /**
         * Setter for phone.
         * @param  phone  String value for phone.
         * @return Builder
         */
        public Builder phone(String phone) {
            this.phone = phone;
            return this;
        }

        /**
         * Setter for eMail.
         * @param  eMail  String value for eMail.
         * @return Builder
         */
        public Builder eMail(String eMail) {
            this.eMail = eMail;
            return this;
        }

        /**
         * Setter for fax.
         * @param  fax  String value for fax.
         * @return Builder
         */
        public Builder fax(String fax) {
            this.fax = fax;
            return this;
        }

        /**
         * Setter for accountNumber.
         * @param  accountNumber  String value for accountNumber.
         * @return Builder
         */
        public Builder accountNumber(String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        /**
         * Setter for organization.
         * @param  organization  String value for organization.
         * @return Builder
         */
        public Builder organization(String organization) {
            this.organization = organization;
            return this;
        }

        /**
         * Setter for street.
         * @param  street  String value for street.
         * @return Builder
         */
        public Builder street(String street) {
            this.street = street;
            return this;
        }

        /**
         * Setter for locale.
         * @param  locale  String value for locale.
         * @return Builder
         */
        public Builder locale(String locale) {
            this.locale = locale;
            return this;
        }

        /**
         * Setter for city.
         * @param  city  String value for city.
         * @return Builder
         */
        public Builder city(String city) {
            this.city = city;
            return this;
        }

        /**
         * Setter for region.
         * @param  region  String value for region.
         * @return Builder
         */
        public Builder region(String region) {
            this.region = region;
            return this;
        }

        /**
         * Setter for postalCode.
         * @param  postalCode  String value for postalCode.
         * @return Builder
         */
        public Builder postalCode(String postalCode) {
            this.postalCode = postalCode;
            return this;
        }

        /**
         * Setter for country.
         * @param  country  String value for country.
         * @return Builder
         */
        public Builder country(String country) {
            this.country = country;
            return this;
        }

        /**
         * Setter for identificationNumber.
         * @param  identificationNumber  String value for identificationNumber.
         * @return Builder
         */
        public Builder identificationNumber(String identificationNumber) {
            this.identificationNumber = identificationNumber;
            return this;
        }

        /**
         * Setter for identificationNumberType.
         * @param  identificationNumberType  IdentificationNumberTypeEnum value for
         *         identificationNumberType.
         * @return Builder
         */
        public Builder identificationNumberType(
                IdentificationNumberTypeEnum identificationNumberType) {
            this.identificationNumberType = OptionalNullable.of(identificationNumberType);
            return this;
        }

        /**
         * UnSetter for identificationNumberType.
         * @return Builder
         */
        public Builder unsetIdentificationNumberType() {
            identificationNumberType = null;
            return this;
        }

        /**
         * Builds a new {@link Broker1} object using the set fields.
         * @return {@link Broker1}
         */
        public Broker1 build() {
            return new Broker1(brokerID, brokerType, contact, phone, eMail, fax, accountNumber,
                    organization, street, locale, city, region, postalCode, country,
                    identificationNumber, identificationNumberType);
        }
    }
}
