/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Charges2 type.
 */
public class Charges2 {
    private List<Charge2> charge;

    /**
     * Default constructor.
     */
    public Charges2() {
    }

    /**
     * Initialization constructor.
     * @param  charge  List of Charge2 value for charge.
     */
    public Charges2(
            List<Charge2> charge) {
        this.charge = charge;
    }

    /**
     * Getter for Charge.
     * Container for an individual charge within the group associated with the transaction.
     * @return Returns the List of Charge2
     */
    @JsonGetter("Charge")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Charge")
    public List<Charge2> getCharge() {
        return charge;
    }

    /**
     * Setter for Charge.
     * Container for an individual charge within the group associated with the transaction.
     * @param charge Value for List of Charge2
     */
    @JsonSetter("Charge")
    public void setCharge(List<Charge2> charge) {
        this.charge = charge;
    }

    /**
     * Converts this Charges2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Charges2 [" + "charge=" + charge + "]";
    }

    /**
     * Builds a new {@link Charges2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Charges2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .charge(getCharge());
        return builder;
    }

    /**
     * Class to build instances of {@link Charges2}.
     */
    public static class Builder {
        private List<Charge2> charge;



        /**
         * Setter for charge.
         * @param  charge  List of Charge2 value for charge.
         * @return Builder
         */
        public Builder charge(List<Charge2> charge) {
            this.charge = charge;
            return this;
        }

        /**
         * Builds a new {@link Charges2} object using the set fields.
         * @return {@link Charges2}
         */
        public Charges2 build() {
            return new Charges2(charge);
        }
    }
}
