/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for ChargeGroup5 type.
 */
public class ChargeGroup5 {
    private int chargeGroupType;
    private String chargeGroupDescription;
    private Double chargeGroupValue;
    private String chargeGroupCurrency;
    private Integer chargeGroupISOCurrency;
    private String chargeGroupISOCurrencySymbol;
    private Charges5 charges;

    /**
     * Default constructor.
     */
    public ChargeGroup5() {
        chargeGroupValue = 0d;
        chargeGroupISOCurrency = 0;
    }

    /**
     * Initialization constructor.
     * @param  chargeGroupType  int value for chargeGroupType.
     * @param  chargeGroupDescription  String value for chargeGroupDescription.
     * @param  charges  Charges5 value for charges.
     * @param  chargeGroupValue  Double value for chargeGroupValue.
     * @param  chargeGroupCurrency  String value for chargeGroupCurrency.
     * @param  chargeGroupISOCurrency  Integer value for chargeGroupISOCurrency.
     * @param  chargeGroupISOCurrencySymbol  String value for chargeGroupISOCurrencySymbol.
     */
    public ChargeGroup5(
            int chargeGroupType,
            String chargeGroupDescription,
            Charges5 charges,
            Double chargeGroupValue,
            String chargeGroupCurrency,
            Integer chargeGroupISOCurrency,
            String chargeGroupISOCurrencySymbol) {
        this.chargeGroupType = chargeGroupType;
        this.chargeGroupDescription = chargeGroupDescription;
        this.chargeGroupValue = chargeGroupValue;
        this.chargeGroupCurrency = chargeGroupCurrency;
        this.chargeGroupISOCurrency = chargeGroupISOCurrency;
        this.chargeGroupISOCurrencySymbol = chargeGroupISOCurrencySymbol;
        this.charges = charges;
    }

    /**
     * Getter for ChargeGroupType.
     * An identifier for the type of the charge group.
     * @return Returns the int
     */
    @JsonGetter("ChargeGroupType")
    @XmlElement(name = "ChargeGroupType")
    public int getChargeGroupType() {
        return chargeGroupType;
    }

    /**
     * Setter for ChargeGroupType.
     * An identifier for the type of the charge group.
     * @param chargeGroupType Value for int
     */
    @JsonSetter("ChargeGroupType")
    public void setChargeGroupType(int chargeGroupType) {
        this.chargeGroupType = chargeGroupType;
    }

    /**
     * Getter for ChargeGroupDescription.
     * The description for the group of charges.
     * @return Returns the String
     */
    @JsonGetter("ChargeGroupDescription")
    @XmlElement(name = "ChargeGroupDescription")
    public String getChargeGroupDescription() {
        return chargeGroupDescription;
    }

    /**
     * Setter for ChargeGroupDescription.
     * The description for the group of charges.
     * @param chargeGroupDescription Value for String
     */
    @JsonSetter("ChargeGroupDescription")
    public void setChargeGroupDescription(String chargeGroupDescription) {
        this.chargeGroupDescription = chargeGroupDescription;
    }

    /**
     * Getter for ChargeGroupValue.
     * The value of the charge group associated with the transaction.
     * @return Returns the Double
     */
    @JsonGetter("ChargeGroupValue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ChargeGroupValue")
    public Double getChargeGroupValue() {
        return chargeGroupValue;
    }

    /**
     * Setter for ChargeGroupValue.
     * The value of the charge group associated with the transaction.
     * @param chargeGroupValue Value for Double
     */
    @JsonSetter("ChargeGroupValue")
    public void setChargeGroupValue(Double chargeGroupValue) {
        this.chargeGroupValue = chargeGroupValue;
    }

    /**
     * Getter for ChargeGroupCurrency.
     * A code indicating the type of currency for the charges group.
     * @return Returns the String
     */
    @JsonGetter("ChargeGroupCurrency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ChargeGroupCurrency")
    public String getChargeGroupCurrency() {
        return chargeGroupCurrency;
    }

    /**
     * Setter for ChargeGroupCurrency.
     * A code indicating the type of currency for the charges group.
     * @param chargeGroupCurrency Value for String
     */
    @JsonSetter("ChargeGroupCurrency")
    public void setChargeGroupCurrency(String chargeGroupCurrency) {
        this.chargeGroupCurrency = chargeGroupCurrency;
    }

    /**
     * Getter for ChargeGroupISOCurrency.
     * ISO code for the currency associated with the transaction.
     * @return Returns the Integer
     */
    @JsonGetter("ChargeGroupISOCurrency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ChargeGroupISOCurrency")
    public Integer getChargeGroupISOCurrency() {
        return chargeGroupISOCurrency;
    }

    /**
     * Setter for ChargeGroupISOCurrency.
     * ISO code for the currency associated with the transaction.
     * @param chargeGroupISOCurrency Value for Integer
     */
    @JsonSetter("ChargeGroupISOCurrency")
    public void setChargeGroupISOCurrency(Integer chargeGroupISOCurrency) {
        this.chargeGroupISOCurrency = chargeGroupISOCurrency;
    }

    /**
     * Getter for ChargeGroupISOCurrencySymbol.
     * Currency symbol for the charge group currency.
     * @return Returns the String
     */
    @JsonGetter("ChargeGroupISOCurrencySymbol")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ChargeGroupISOCurrencySymbol")
    public String getChargeGroupISOCurrencySymbol() {
        return chargeGroupISOCurrencySymbol;
    }

    /**
     * Setter for ChargeGroupISOCurrencySymbol.
     * Currency symbol for the charge group currency.
     * @param chargeGroupISOCurrencySymbol Value for String
     */
    @JsonSetter("ChargeGroupISOCurrencySymbol")
    public void setChargeGroupISOCurrencySymbol(String chargeGroupISOCurrencySymbol) {
        this.chargeGroupISOCurrencySymbol = chargeGroupISOCurrencySymbol;
    }

    /**
     * Getter for Charges.
     * Container for all charges within the group associated with the transaction.
     * @return Returns the Charges5
     */
    @JsonGetter("Charges")
    @XmlElement(name = "Charges")
    public Charges5 getCharges() {
        return charges;
    }

    /**
     * Setter for Charges.
     * Container for all charges within the group associated with the transaction.
     * @param charges Value for Charges5
     */
    @JsonSetter("Charges")
    public void setCharges(Charges5 charges) {
        this.charges = charges;
    }

    /**
     * Converts this ChargeGroup5 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ChargeGroup5 [" + "chargeGroupType=" + chargeGroupType + ", chargeGroupDescription="
                + chargeGroupDescription + ", charges=" + charges + ", chargeGroupValue="
                + chargeGroupValue + ", chargeGroupCurrency=" + chargeGroupCurrency
                + ", chargeGroupISOCurrency=" + chargeGroupISOCurrency
                + ", chargeGroupISOCurrencySymbol=" + chargeGroupISOCurrencySymbol + "]";
    }

    /**
     * Builds a new {@link ChargeGroup5.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ChargeGroup5.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(chargeGroupType, chargeGroupDescription, charges)
                .chargeGroupValue(getChargeGroupValue())
                .chargeGroupCurrency(getChargeGroupCurrency())
                .chargeGroupISOCurrency(getChargeGroupISOCurrency())
                .chargeGroupISOCurrencySymbol(getChargeGroupISOCurrencySymbol());
        return builder;
    }

    /**
     * Class to build instances of {@link ChargeGroup5}.
     */
    public static class Builder {
        private int chargeGroupType;
        private String chargeGroupDescription;
        private Charges5 charges;
        private Double chargeGroupValue = 0d;
        private String chargeGroupCurrency;
        private Integer chargeGroupISOCurrency = 0;
        private String chargeGroupISOCurrencySymbol;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  chargeGroupType  int value for chargeGroupType.
         * @param  chargeGroupDescription  String value for chargeGroupDescription.
         * @param  charges  Charges5 value for charges.
         */
        public Builder(int chargeGroupType, String chargeGroupDescription, Charges5 charges) {
            this.chargeGroupType = chargeGroupType;
            this.chargeGroupDescription = chargeGroupDescription;
            this.charges = charges;
        }

        /**
         * Setter for chargeGroupType.
         * @param  chargeGroupType  int value for chargeGroupType.
         * @return Builder
         */
        public Builder chargeGroupType(int chargeGroupType) {
            this.chargeGroupType = chargeGroupType;
            return this;
        }

        /**
         * Setter for chargeGroupDescription.
         * @param  chargeGroupDescription  String value for chargeGroupDescription.
         * @return Builder
         */
        public Builder chargeGroupDescription(String chargeGroupDescription) {
            this.chargeGroupDescription = chargeGroupDescription;
            return this;
        }

        /**
         * Setter for charges.
         * @param  charges  Charges5 value for charges.
         * @return Builder
         */
        public Builder charges(Charges5 charges) {
            this.charges = charges;
            return this;
        }

        /**
         * Setter for chargeGroupValue.
         * @param  chargeGroupValue  Double value for chargeGroupValue.
         * @return Builder
         */
        public Builder chargeGroupValue(Double chargeGroupValue) {
            this.chargeGroupValue = chargeGroupValue;
            return this;
        }

        /**
         * Setter for chargeGroupCurrency.
         * @param  chargeGroupCurrency  String value for chargeGroupCurrency.
         * @return Builder
         */
        public Builder chargeGroupCurrency(String chargeGroupCurrency) {
            this.chargeGroupCurrency = chargeGroupCurrency;
            return this;
        }

        /**
         * Setter for chargeGroupISOCurrency.
         * @param  chargeGroupISOCurrency  Integer value for chargeGroupISOCurrency.
         * @return Builder
         */
        public Builder chargeGroupISOCurrency(Integer chargeGroupISOCurrency) {
            this.chargeGroupISOCurrency = chargeGroupISOCurrency;
            return this;
        }

        /**
         * Setter for chargeGroupISOCurrencySymbol.
         * @param  chargeGroupISOCurrencySymbol  String value for chargeGroupISOCurrencySymbol.
         * @return Builder
         */
        public Builder chargeGroupISOCurrencySymbol(String chargeGroupISOCurrencySymbol) {
            this.chargeGroupISOCurrencySymbol = chargeGroupISOCurrencySymbol;
            return this;
        }

        /**
         * Builds a new {@link ChargeGroup5} object using the set fields.
         * @return {@link ChargeGroup5}
         */
        public ChargeGroup5 build() {
            return new ChargeGroup5(chargeGroupType, chargeGroupDescription, charges,
                    chargeGroupValue, chargeGroupCurrency, chargeGroupISOCurrency,
                    chargeGroupISOCurrencySymbol);
        }
    }
}
