/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for CommercialInvoice type.
 */
public class CommercialInvoice {
    private Double freightCharge;
    private Double insuranceCharge;
    private Double otherCharge;
    private String comments;
    private OptionalNullable<PurposeEnum> purpose;
    private String declarationStatement;
    private String originatorName;
    private String specialInstructions;

    /**
     * Default constructor.
     */
    public CommercialInvoice() {
        freightCharge = 0d;
        insuranceCharge = 0d;
        otherCharge = 0d;
    }

    /**
     * Initialization constructor.
     * @param  freightCharge  Double value for freightCharge.
     * @param  insuranceCharge  Double value for insuranceCharge.
     * @param  otherCharge  Double value for otherCharge.
     * @param  comments  String value for comments.
     * @param  purpose  PurposeEnum value for purpose.
     * @param  declarationStatement  String value for declarationStatement.
     * @param  originatorName  String value for originatorName.
     * @param  specialInstructions  String value for specialInstructions.
     */
    public CommercialInvoice(
            Double freightCharge,
            Double insuranceCharge,
            Double otherCharge,
            String comments,
            PurposeEnum purpose,
            String declarationStatement,
            String originatorName,
            String specialInstructions) {
        this.freightCharge = freightCharge;
        this.insuranceCharge = insuranceCharge;
        this.otherCharge = otherCharge;
        this.comments = comments;
        this.purpose = OptionalNullable.of(purpose);
        this.declarationStatement = declarationStatement;
        this.originatorName = originatorName;
        this.specialInstructions = specialInstructions;
    }

    /**
     * Initialization constructor.
     * @param  freightCharge  Double value for freightCharge.
     * @param  insuranceCharge  Double value for insuranceCharge.
     * @param  otherCharge  Double value for otherCharge.
     * @param  comments  String value for comments.
     * @param  purpose  PurposeEnum value for purpose.
     * @param  declarationStatement  String value for declarationStatement.
     * @param  originatorName  String value for originatorName.
     * @param  specialInstructions  String value for specialInstructions.
     */

    protected CommercialInvoice(Double freightCharge, Double insuranceCharge, Double otherCharge,
            String comments, OptionalNullable<PurposeEnum> purpose, String declarationStatement,
            String originatorName, String specialInstructions) {
        this.freightCharge = freightCharge;
        this.insuranceCharge = insuranceCharge;
        this.otherCharge = otherCharge;
        this.comments = comments;
        this.purpose = purpose;
        this.declarationStatement = declarationStatement;
        this.originatorName = originatorName;
        this.specialInstructions = specialInstructions;
    }

    /**
     * Getter for FreightCharge.
     * The freight charge to be printed on the commercial invoice.
     * @return Returns the Double
     */
    @JsonGetter("FreightCharge")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "FreightCharge")
    public Double getFreightCharge() {
        return freightCharge;
    }

    /**
     * Setter for FreightCharge.
     * The freight charge to be printed on the commercial invoice.
     * @param freightCharge Value for Double
     */
    @JsonSetter("FreightCharge")
    public void setFreightCharge(Double freightCharge) {
        this.freightCharge = freightCharge;
    }

    /**
     * Getter for InsuranceCharge.
     * The insurance charge to be printed on the commercial invoice.
     * @return Returns the Double
     */
    @JsonGetter("InsuranceCharge")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "InsuranceCharge")
    public Double getInsuranceCharge() {
        return insuranceCharge;
    }

    /**
     * Setter for InsuranceCharge.
     * The insurance charge to be printed on the commercial invoice.
     * @param insuranceCharge Value for Double
     */
    @JsonSetter("InsuranceCharge")
    public void setInsuranceCharge(Double insuranceCharge) {
        this.insuranceCharge = insuranceCharge;
    }

    /**
     * Getter for OtherCharge.
     * The unclassified charge to be printed on the commercial invoice.
     * @return Returns the Double
     */
    @JsonGetter("OtherCharge")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OtherCharge")
    public Double getOtherCharge() {
        return otherCharge;
    }

    /**
     * Setter for OtherCharge.
     * The unclassified charge to be printed on the commercial invoice.
     * @param otherCharge Value for Double
     */
    @JsonSetter("OtherCharge")
    public void setOtherCharge(Double otherCharge) {
        this.otherCharge = otherCharge;
    }

    /**
     * Getter for Comments.
     * Comments to be shown on the commercial invoice.
     * @return Returns the String
     */
    @JsonGetter("Comments")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Comments")
    public String getComments() {
        return comments;
    }

    /**
     * Setter for Comments.
     * Comments to be shown on the commercial invoice.
     * @param comments Value for String
     */
    @JsonSetter("Comments")
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * Internal Getter for Purpose.
     * The purpose to be shown on the commercial invoice for the consolidated shipment.
     * @return Returns the Internal PurposeEnum
     */
    @JsonGetter("Purpose")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<PurposeEnum> internalGetPurpose() {
        return this.purpose;
    }

    /**
     * Getter for Purpose.
     * The purpose to be shown on the commercial invoice for the consolidated shipment.
     * @return Returns the PurposeEnum
     */
    @XmlElement(name = "Purpose")
    public PurposeEnum getPurpose() {
        return OptionalNullable.getFrom(purpose);
    }

    /**
     * Setter for Purpose.
     * The purpose to be shown on the commercial invoice for the consolidated shipment.
     * @param purpose Value for PurposeEnum
     */
    @JsonSetter("Purpose")
    public void setPurpose(PurposeEnum purpose) {
        this.purpose = OptionalNullable.of(purpose);
    }

    /**
     * UnSetter for Purpose.
     * The purpose to be shown on the commercial invoice for the consolidated shipment.
     */
    public void unsetPurpose() {
        purpose = null;
    }

    /**
     * Getter for DeclarationStatement.
     * Declaration Statement to be shown on the commercial invoice.
     * @return Returns the String
     */
    @JsonGetter("DeclarationStatement")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "DeclarationStatement")
    public String getDeclarationStatement() {
        return declarationStatement;
    }

    /**
     * Setter for DeclarationStatement.
     * Declaration Statement to be shown on the commercial invoice.
     * @param declarationStatement Value for String
     */
    @JsonSetter("DeclarationStatement")
    public void setDeclarationStatement(String declarationStatement) {
        this.declarationStatement = declarationStatement;
    }

    /**
     * Getter for OriginatorName.
     * Originator Name to be shown on the commercial invoice.
     * @return Returns the String
     */
    @JsonGetter("OriginatorName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OriginatorName")
    public String getOriginatorName() {
        return originatorName;
    }

    /**
     * Setter for OriginatorName.
     * Originator Name to be shown on the commercial invoice.
     * @param originatorName Value for String
     */
    @JsonSetter("OriginatorName")
    public void setOriginatorName(String originatorName) {
        this.originatorName = originatorName;
    }

    /**
     * Getter for SpecialInstructions.
     * Special Instructions to be shown on the commercial invoice.
     * @return Returns the String
     */
    @JsonGetter("SpecialInstructions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "SpecialInstructions")
    public String getSpecialInstructions() {
        return specialInstructions;
    }

    /**
     * Setter for SpecialInstructions.
     * Special Instructions to be shown on the commercial invoice.
     * @param specialInstructions Value for String
     */
    @JsonSetter("SpecialInstructions")
    public void setSpecialInstructions(String specialInstructions) {
        this.specialInstructions = specialInstructions;
    }

    /**
     * Converts this CommercialInvoice into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CommercialInvoice [" + "freightCharge=" + freightCharge + ", insuranceCharge="
                + insuranceCharge + ", otherCharge=" + otherCharge + ", comments=" + comments
                + ", purpose=" + purpose + ", declarationStatement=" + declarationStatement
                + ", originatorName=" + originatorName + ", specialInstructions="
                + specialInstructions + "]";
    }

    /**
     * Builds a new {@link CommercialInvoice.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CommercialInvoice.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .freightCharge(getFreightCharge())
                .insuranceCharge(getInsuranceCharge())
                .otherCharge(getOtherCharge())
                .comments(getComments())
                .declarationStatement(getDeclarationStatement())
                .originatorName(getOriginatorName())
                .specialInstructions(getSpecialInstructions());
        builder.purpose = internalGetPurpose();
        return builder;
    }

    /**
     * Class to build instances of {@link CommercialInvoice}.
     */
    public static class Builder {
        private Double freightCharge = 0d;
        private Double insuranceCharge = 0d;
        private Double otherCharge = 0d;
        private String comments;
        private OptionalNullable<PurposeEnum> purpose;
        private String declarationStatement;
        private String originatorName;
        private String specialInstructions;



        /**
         * Setter for freightCharge.
         * @param  freightCharge  Double value for freightCharge.
         * @return Builder
         */
        public Builder freightCharge(Double freightCharge) {
            this.freightCharge = freightCharge;
            return this;
        }

        /**
         * Setter for insuranceCharge.
         * @param  insuranceCharge  Double value for insuranceCharge.
         * @return Builder
         */
        public Builder insuranceCharge(Double insuranceCharge) {
            this.insuranceCharge = insuranceCharge;
            return this;
        }

        /**
         * Setter for otherCharge.
         * @param  otherCharge  Double value for otherCharge.
         * @return Builder
         */
        public Builder otherCharge(Double otherCharge) {
            this.otherCharge = otherCharge;
            return this;
        }

        /**
         * Setter for comments.
         * @param  comments  String value for comments.
         * @return Builder
         */
        public Builder comments(String comments) {
            this.comments = comments;
            return this;
        }

        /**
         * Setter for purpose.
         * @param  purpose  PurposeEnum value for purpose.
         * @return Builder
         */
        public Builder purpose(PurposeEnum purpose) {
            this.purpose = OptionalNullable.of(purpose);
            return this;
        }

        /**
         * UnSetter for purpose.
         * @return Builder
         */
        public Builder unsetPurpose() {
            purpose = null;
            return this;
        }

        /**
         * Setter for declarationStatement.
         * @param  declarationStatement  String value for declarationStatement.
         * @return Builder
         */
        public Builder declarationStatement(String declarationStatement) {
            this.declarationStatement = declarationStatement;
            return this;
        }

        /**
         * Setter for originatorName.
         * @param  originatorName  String value for originatorName.
         * @return Builder
         */
        public Builder originatorName(String originatorName) {
            this.originatorName = originatorName;
            return this;
        }

        /**
         * Setter for specialInstructions.
         * @param  specialInstructions  String value for specialInstructions.
         * @return Builder
         */
        public Builder specialInstructions(String specialInstructions) {
            this.specialInstructions = specialInstructions;
            return this;
        }

        /**
         * Builds a new {@link CommercialInvoice} object using the set fields.
         * @return {@link CommercialInvoice}
         */
        public CommercialInvoice build() {
            return new CommercialInvoice(freightCharge, insuranceCharge, otherCharge, comments,
                    purpose, declarationStatement, originatorName, specialInstructions);
        }
    }
}
