/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Contents type.
 */
public class Contents {
    private List<Content> content;

    /**
     * Default constructor.
     */
    public Contents() {
    }

    /**
     * Initialization constructor.
     * @param  content  List of Content value for content.
     */
    public Contents(
            List<Content> content) {
        this.content = content;
    }

    /**
     * Getter for Content.
     * Container for a individual content (line item) associated with the transaction.
     * @return Returns the List of Content
     */
    @JsonGetter("Content")
    @XmlElement(name = "Content")
    public List<Content> getContent() {
        return content;
    }

    /**
     * Setter for Content.
     * Container for a individual content (line item) associated with the transaction.
     * @param content Value for List of Content
     */
    @JsonSetter("Content")
    public void setContent(List<Content> content) {
        this.content = content;
    }

    /**
     * Converts this Contents into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Contents [" + "content=" + content + "]";
    }

    /**
     * Builds a new {@link Contents.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Contents.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(content);
        return builder;
    }

    /**
     * Class to build instances of {@link Contents}.
     */
    public static class Builder {
        private List<Content> content;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  content  List of Content value for content.
         */
        public Builder(List<Content> content) {
            this.content = content;
        }

        /**
         * Setter for content.
         * @param  content  List of Content value for content.
         * @return Builder
         */
        public Builder content(List<Content> content) {
            this.content = content;
            return this;
        }

        /**
         * Builds a new {@link Contents} object using the set fields.
         * @return {@link Contents}
         */
        public Contents build() {
            return new Contents(content);
        }
    }
}
