/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Contents6 type.
 */
public class Contents6 {
    private List<Content6> content;

    /**
     * Default constructor.
     */
    public Contents6() {
    }

    /**
     * Initialization constructor.
     * @param  content  List of Content6 value for content.
     */
    public Contents6(
            List<Content6> content) {
        this.content = content;
    }

    /**
     * Getter for Content.
     * Container for a individual content (line item) associated with the transaction.
     * @return Returns the List of Content6
     */
    @JsonGetter("Content")
    @XmlElement(name = "Content")
    public List<Content6> getContent() {
        return content;
    }

    /**
     * Setter for Content.
     * Container for a individual content (line item) associated with the transaction.
     * @param content Value for List of Content6
     */
    @JsonSetter("Content")
    public void setContent(List<Content6> content) {
        this.content = content;
    }

    /**
     * Converts this Contents6 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Contents6 [" + "content=" + content + "]";
    }

    /**
     * Builds a new {@link Contents6.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Contents6.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(content);
        return builder;
    }

    /**
     * Class to build instances of {@link Contents6}.
     */
    public static class Builder {
        private List<Content6> content;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  content  List of Content6 value for content.
         */
        public Builder(List<Content6> content) {
            this.content = content;
        }

        /**
         * Setter for content.
         * @param  content  List of Content6 value for content.
         * @return Builder
         */
        public Builder content(List<Content6> content) {
            this.content = content;
            return this;
        }

        /**
         * Builds a new {@link Contents6} object using the set fields.
         * @return {@link Contents6}
         */
        public Contents6 build() {
            return new Contents6(content);
        }
    }
}
