/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for CorrectedReceiverAddress type.
 */
public class CorrectedReceiverAddress {
    private String street;
    private String locale;
    private String other;
    private String city;
    private String region;
    private String postalCode;
    private String country;
    private Boolean residential;

    /**
     * Default constructor.
     */
    public CorrectedReceiverAddress() {
        residential = false;
    }

    /**
     * Initialization constructor.
     * @param  street  String value for street.
     * @param  locale  String value for locale.
     * @param  other  String value for other.
     * @param  city  String value for city.
     * @param  region  String value for region.
     * @param  postalCode  String value for postalCode.
     * @param  country  String value for country.
     * @param  residential  Boolean value for residential.
     */
    public CorrectedReceiverAddress(
            String street,
            String locale,
            String other,
            String city,
            String region,
            String postalCode,
            String country,
            Boolean residential) {
        this.street = street;
        this.locale = locale;
        this.other = other;
        this.city = city;
        this.region = region;
        this.postalCode = postalCode;
        this.country = country;
        this.residential = residential;
    }

    /**
     * Getter for Street.
     * First line of the address.
     * @return Returns the String
     */
    @JsonGetter("Street")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Street")
    public String getStreet() {
        return street;
    }

    /**
     * Setter for Street.
     * First line of the address.
     * @param street Value for String
     */
    @JsonSetter("Street")
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * Getter for Locale.
     * Second line of the address.
     * @return Returns the String
     */
    @JsonGetter("Locale")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Locale")
    public String getLocale() {
        return locale;
    }

    /**
     * Setter for Locale.
     * Second line of the address.
     * @param locale Value for String
     */
    @JsonSetter("Locale")
    public void setLocale(String locale) {
        this.locale = locale;
    }

    /**
     * Getter for Other.
     * Third line of the address.
     * @return Returns the String
     */
    @JsonGetter("Other")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Other")
    public String getOther() {
        return other;
    }

    /**
     * Setter for Other.
     * Third line of the address.
     * @param other Value for String
     */
    @JsonSetter("Other")
    public void setOther(String other) {
        this.other = other;
    }

    /**
     * Getter for City.
     * City of the address.
     * @return Returns the String
     */
    @JsonGetter("City")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "City")
    public String getCity() {
        return city;
    }

    /**
     * Setter for City.
     * City of the address.
     * @param city Value for String
     */
    @JsonSetter("City")
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for Region.
     * The state or region of the address.
     * @return Returns the String
     */
    @JsonGetter("Region")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Region")
    public String getRegion() {
        return region;
    }

    /**
     * Setter for Region.
     * The state or region of the address.
     * @param region Value for String
     */
    @JsonSetter("Region")
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * Getter for PostalCode.
     * The postal code or zip associated with the address.
     * @return Returns the String
     */
    @JsonGetter("PostalCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PostalCode")
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Setter for PostalCode.
     * The postal code or zip associated with the address.
     * @param postalCode Value for String
     */
    @JsonSetter("PostalCode")
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * Getter for Country.
     * The country code for the address.
     * @return Returns the String
     */
    @JsonGetter("Country")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Country")
    public String getCountry() {
        return country;
    }

    /**
     * Setter for Country.
     * The country code for the address.
     * @param country Value for String
     */
    @JsonSetter("Country")
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for Residential.
     * Indicates whether the address is residential or commercial.
     * @return Returns the Boolean
     */
    @JsonGetter("Residential")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Residential")
    public Boolean getResidential() {
        return residential;
    }

    /**
     * Setter for Residential.
     * Indicates whether the address is residential or commercial.
     * @param residential Value for Boolean
     */
    @JsonSetter("Residential")
    public void setResidential(Boolean residential) {
        this.residential = residential;
    }

    /**
     * Converts this CorrectedReceiverAddress into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CorrectedReceiverAddress [" + "street=" + street + ", locale=" + locale + ", other="
                + other + ", city=" + city + ", region=" + region + ", postalCode=" + postalCode
                + ", country=" + country + ", residential=" + residential + "]";
    }

    /**
     * Builds a new {@link CorrectedReceiverAddress.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CorrectedReceiverAddress.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .street(getStreet())
                .locale(getLocale())
                .other(getOther())
                .city(getCity())
                .region(getRegion())
                .postalCode(getPostalCode())
                .country(getCountry())
                .residential(getResidential());
        return builder;
    }

    /**
     * Class to build instances of {@link CorrectedReceiverAddress}.
     */
    public static class Builder {
        private String street;
        private String locale;
        private String other;
        private String city;
        private String region;
        private String postalCode;
        private String country;
        private Boolean residential = false;



        /**
         * Setter for street.
         * @param  street  String value for street.
         * @return Builder
         */
        public Builder street(String street) {
            this.street = street;
            return this;
        }

        /**
         * Setter for locale.
         * @param  locale  String value for locale.
         * @return Builder
         */
        public Builder locale(String locale) {
            this.locale = locale;
            return this;
        }

        /**
         * Setter for other.
         * @param  other  String value for other.
         * @return Builder
         */
        public Builder other(String other) {
            this.other = other;
            return this;
        }

        /**
         * Setter for city.
         * @param  city  String value for city.
         * @return Builder
         */
        public Builder city(String city) {
            this.city = city;
            return this;
        }

        /**
         * Setter for region.
         * @param  region  String value for region.
         * @return Builder
         */
        public Builder region(String region) {
            this.region = region;
            return this;
        }

        /**
         * Setter for postalCode.
         * @param  postalCode  String value for postalCode.
         * @return Builder
         */
        public Builder postalCode(String postalCode) {
            this.postalCode = postalCode;
            return this;
        }

        /**
         * Setter for country.
         * @param  country  String value for country.
         * @return Builder
         */
        public Builder country(String country) {
            this.country = country;
            return this;
        }

        /**
         * Setter for residential.
         * @param  residential  Boolean value for residential.
         * @return Builder
         */
        public Builder residential(Boolean residential) {
            this.residential = residential;
            return this;
        }

        /**
         * Builds a new {@link CorrectedReceiverAddress} object using the set fields.
         * @return {@link CorrectedReceiverAddress}
         */
        public CorrectedReceiverAddress build() {
            return new CorrectedReceiverAddress(street, locale, other, city, region, postalCode,
                    country, residential);
        }
    }
}
