/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Documents type.
 */
public class Documents {
    private List<Output2> output;

    /**
     * Default constructor.
     */
    public Documents() {
    }

    /**
     * Initialization constructor.
     * @param  output  List of Output2 value for output.
     */
    public Documents(
            List<Output2> output) {
        this.output = output;
    }

    /**
     * Getter for Output.
     * Container for documents to be printed externally from the transaction.
     * @return Returns the List of Output2
     */
    @JsonGetter("Output")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Output")
    public List<Output2> getOutput() {
        return output;
    }

    /**
     * Setter for Output.
     * Container for documents to be printed externally from the transaction.
     * @param output Value for List of Output2
     */
    @JsonSetter("Output")
    public void setOutput(List<Output2> output) {
        this.output = output;
    }

    /**
     * Converts this Documents into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Documents [" + "output=" + output + "]";
    }

    /**
     * Builds a new {@link Documents.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Documents.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .output(getOutput());
        return builder;
    }

    /**
     * Class to build instances of {@link Documents}.
     */
    public static class Builder {
        private List<Output2> output;



        /**
         * Setter for output.
         * @param  output  List of Output2 value for output.
         * @return Builder
         */
        public Builder output(List<Output2> output) {
            this.output = output;
            return this;
        }

        /**
         * Builds a new {@link Documents} object using the set fields.
         * @return {@link Documents}
         */
        public Documents build() {
            return new Documents(output);
        }
    }
}
