/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * ExemptionTypeEnum to be used.
 */
public enum ExemptionTypeEnum {
    @javax.xml.bind.annotation.XmlEnumValue("Unknown")
    UNKNOWN,

    @javax.xml.bind.annotation.XmlEnumValue("EX")
    EX,

    @javax.xml.bind.annotation.XmlEnumValue("CA")
    CA,

    @javax.xml.bind.annotation.XmlEnumValue("SP")
    SP,

    @javax.xml.bind.annotation.XmlEnumValue("VRI")
    VRI,

    @javax.xml.bind.annotation.XmlEnumValue("EC")
    EC;

    private static TreeMap<String, ExemptionTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        UNKNOWN.value = "Unknown";
        EX.value = "EX";
        CA.value = "CA";
        SP.value = "SP";
        VRI.value = "VRI";
        EC.value = "EC";

        valueMap.put("Unknown", UNKNOWN);
        valueMap.put("EX", EX);
        valueMap.put("CA", CA);
        valueMap.put("SP", SP);
        valueMap.put("VRI", VRI);
        valueMap.put("EC", EC);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static ExemptionTypeEnum constructFromString(String toConvert) throws IOException {
        ExemptionTypeEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static ExemptionTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ExemptionTypeEnum values to list of string values.
     * @param toConvert The list of ExemptionTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ExemptionTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ExemptionTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 