/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for External type.
 */
public class External {
    private String startTime;
    private String endTime;
    private double duration;

    /**
     * Default constructor.
     */
    public External() {
    }

    /**
     * Initialization constructor.
     * @param  startTime  String value for startTime.
     * @param  endTime  String value for endTime.
     * @param  duration  double value for duration.
     */
    public External(
            String startTime,
            String endTime,
            double duration) {
        this.startTime = startTime;
        this.endTime = endTime;
        this.duration = duration;
    }

    /**
     * Getter for StartTime.
     * The time the transaction started to be processed by an external system.
     * @return Returns the String
     */
    @JsonGetter("StartTime")
    @XmlElement(name = "StartTime")
    public String getStartTime() {
        return startTime;
    }

    /**
     * Setter for StartTime.
     * The time the transaction started to be processed by an external system.
     * @param startTime Value for String
     */
    @JsonSetter("StartTime")
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * Getter for EndTime.
     * The time the transaction finished processing by an external system.
     * @return Returns the String
     */
    @JsonGetter("EndTime")
    @XmlElement(name = "EndTime")
    public String getEndTime() {
        return endTime;
    }

    /**
     * Setter for EndTime.
     * The time the transaction finished processing by an external system.
     * @param endTime Value for String
     */
    @JsonSetter("EndTime")
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * Getter for Duration.
     * The difference in milliseconds between the processing external start and end times.
     * @return Returns the double
     */
    @JsonGetter("Duration")
    @XmlElement(name = "Duration")
    public double getDuration() {
        return duration;
    }

    /**
     * Setter for Duration.
     * The difference in milliseconds between the processing external start and end times.
     * @param duration Value for double
     */
    @JsonSetter("Duration")
    public void setDuration(double duration) {
        this.duration = duration;
    }

    /**
     * Converts this External into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "External [" + "startTime=" + startTime + ", endTime=" + endTime + ", duration="
                + duration + "]";
    }

    /**
     * Builds a new {@link External.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link External.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(startTime, endTime, duration);
        return builder;
    }

    /**
     * Class to build instances of {@link External}.
     */
    public static class Builder {
        private String startTime;
        private String endTime;
        private double duration;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  startTime  String value for startTime.
         * @param  endTime  String value for endTime.
         * @param  duration  double value for duration.
         */
        public Builder(String startTime, String endTime, double duration) {
            this.startTime = startTime;
            this.endTime = endTime;
            this.duration = duration;
        }

        /**
         * Setter for startTime.
         * @param  startTime  String value for startTime.
         * @return Builder
         */
        public Builder startTime(String startTime) {
            this.startTime = startTime;
            return this;
        }

        /**
         * Setter for endTime.
         * @param  endTime  String value for endTime.
         * @return Builder
         */
        public Builder endTime(String endTime) {
            this.endTime = endTime;
            return this;
        }

        /**
         * Setter for duration.
         * @param  duration  double value for duration.
         * @return Builder
         */
        public Builder duration(double duration) {
            this.duration = duration;
            return this;
        }

        /**
         * Builds a new {@link External} object using the set fields.
         * @return {@link External}
         */
        public External build() {
            return new External(startTime, endTime, duration);
        }
    }
}
