/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Freight1 type.
 */
public class Freight1 {
    private Billing1 billing;
    private Double freightHandlingLength;
    private Double freightHandlingWidth;
    private Double freightHandlingHeight;
    private Double freightHandlingPalletWeight;
    private Boolean mixedFreightParcelMode;
    private String freightClass;
    private String nMFC;
    private String shipAfterTime;
    private String shipBeforeTime;

    /**
     * Default constructor.
     */
    public Freight1() {
        freightHandlingLength = 0d;
        freightHandlingWidth = 0d;
        freightHandlingHeight = 0d;
        freightHandlingPalletWeight = 0d;
        mixedFreightParcelMode = false;
    }

    /**
     * Initialization constructor.
     * @param  billing  Billing1 value for billing.
     * @param  freightHandlingLength  Double value for freightHandlingLength.
     * @param  freightHandlingWidth  Double value for freightHandlingWidth.
     * @param  freightHandlingHeight  Double value for freightHandlingHeight.
     * @param  freightHandlingPalletWeight  Double value for freightHandlingPalletWeight.
     * @param  mixedFreightParcelMode  Boolean value for mixedFreightParcelMode.
     * @param  freightClass  String value for freightClass.
     * @param  nMFC  String value for nMFC.
     * @param  shipAfterTime  String value for shipAfterTime.
     * @param  shipBeforeTime  String value for shipBeforeTime.
     */
    public Freight1(
            Billing1 billing,
            Double freightHandlingLength,
            Double freightHandlingWidth,
            Double freightHandlingHeight,
            Double freightHandlingPalletWeight,
            Boolean mixedFreightParcelMode,
            String freightClass,
            String nMFC,
            String shipAfterTime,
            String shipBeforeTime) {
        this.billing = billing;
        this.freightHandlingLength = freightHandlingLength;
        this.freightHandlingWidth = freightHandlingWidth;
        this.freightHandlingHeight = freightHandlingHeight;
        this.freightHandlingPalletWeight = freightHandlingPalletWeight;
        this.mixedFreightParcelMode = mixedFreightParcelMode;
        this.freightClass = freightClass;
        this.nMFC = nMFC;
        this.shipAfterTime = shipAfterTime;
        this.shipBeforeTime = shipBeforeTime;
    }

    /**
     * Getter for Billing.
     * Container for billing details associated with the transaction.
     * @return Returns the Billing1
     */
    @JsonGetter("Billing")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Billing")
    public Billing1 getBilling() {
        return billing;
    }

    /**
     * Setter for Billing.
     * Container for billing details associated with the transaction.
     * @param billing Value for Billing1
     */
    @JsonSetter("Billing")
    public void setBilling(Billing1 billing) {
        this.billing = billing;
    }

    /**
     * Getter for FreightHandlingLength.
     * The dimensional length of the freight handling type. Only to be used when rate shopping with
     * a rategroup that contains both LTL and Parcel services.
     * @return Returns the Double
     */
    @JsonGetter("FreightHandlingLength")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "FreightHandlingLength")
    public Double getFreightHandlingLength() {
        return freightHandlingLength;
    }

    /**
     * Setter for FreightHandlingLength.
     * The dimensional length of the freight handling type. Only to be used when rate shopping with
     * a rategroup that contains both LTL and Parcel services.
     * @param freightHandlingLength Value for Double
     */
    @JsonSetter("FreightHandlingLength")
    public void setFreightHandlingLength(Double freightHandlingLength) {
        this.freightHandlingLength = freightHandlingLength;
    }

    /**
     * Getter for FreightHandlingWidth.
     * The dimensional width of the freight handling type. Only to be used when rate shopping with a
     * rategroup that contains both LTL and Parcel services.
     * @return Returns the Double
     */
    @JsonGetter("FreightHandlingWidth")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "FreightHandlingWidth")
    public Double getFreightHandlingWidth() {
        return freightHandlingWidth;
    }

    /**
     * Setter for FreightHandlingWidth.
     * The dimensional width of the freight handling type. Only to be used when rate shopping with a
     * rategroup that contains both LTL and Parcel services.
     * @param freightHandlingWidth Value for Double
     */
    @JsonSetter("FreightHandlingWidth")
    public void setFreightHandlingWidth(Double freightHandlingWidth) {
        this.freightHandlingWidth = freightHandlingWidth;
    }

    /**
     * Getter for FreightHandlingHeight.
     * The dimensional height of the freight handling type. Only to be used when rate shopping with
     * a rategroup that contains both LTL and Parcel services.
     * @return Returns the Double
     */
    @JsonGetter("FreightHandlingHeight")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "FreightHandlingHeight")
    public Double getFreightHandlingHeight() {
        return freightHandlingHeight;
    }

    /**
     * Setter for FreightHandlingHeight.
     * The dimensional height of the freight handling type. Only to be used when rate shopping with
     * a rategroup that contains both LTL and Parcel services.
     * @param freightHandlingHeight Value for Double
     */
    @JsonSetter("FreightHandlingHeight")
    public void setFreightHandlingHeight(Double freightHandlingHeight) {
        this.freightHandlingHeight = freightHandlingHeight;
    }

    /**
     * Getter for FreightHandlingPalletWeight.
     * The weight of the pallet. Only to be used when rate shopping with a rategroup that contains
     * both LTL and Parcel services.
     * @return Returns the Double
     */
    @JsonGetter("FreightHandlingPalletWeight")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "FreightHandlingPalletWeight")
    public Double getFreightHandlingPalletWeight() {
        return freightHandlingPalletWeight;
    }

    /**
     * Setter for FreightHandlingPalletWeight.
     * The weight of the pallet. Only to be used when rate shopping with a rategroup that contains
     * both LTL and Parcel services.
     * @param freightHandlingPalletWeight Value for Double
     */
    @JsonSetter("FreightHandlingPalletWeight")
    public void setFreightHandlingPalletWeight(Double freightHandlingPalletWeight) {
        this.freightHandlingPalletWeight = freightHandlingPalletWeight;
    }

    /**
     * Getter for MixedFreightParcelMode.
     * Indicates if the rateshop has a mixture of parcel and freight carriers
     * @return Returns the Boolean
     */
    @JsonGetter("MixedFreightParcelMode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "MixedFreightParcelMode")
    public Boolean getMixedFreightParcelMode() {
        return mixedFreightParcelMode;
    }

    /**
     * Setter for MixedFreightParcelMode.
     * Indicates if the rateshop has a mixture of parcel and freight carriers
     * @param mixedFreightParcelMode Value for Boolean
     */
    @JsonSetter("MixedFreightParcelMode")
    public void setMixedFreightParcelMode(Boolean mixedFreightParcelMode) {
        this.mixedFreightParcelMode = mixedFreightParcelMode;
    }

    /**
     * Getter for FreightClass.
     * The freight class of the package's content.
     * @return Returns the String
     */
    @JsonGetter("FreightClass")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "FreightClass")
    public String getFreightClass() {
        return freightClass;
    }

    /**
     * Setter for FreightClass.
     * The freight class of the package's content.
     * @param freightClass Value for String
     */
    @JsonSetter("FreightClass")
    public void setFreightClass(String freightClass) {
        this.freightClass = freightClass;
    }

    /**
     * Getter for NMFC.
     * The National Motor Freight Classification of the package.
     * @return Returns the String
     */
    @JsonGetter("NMFC")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "NMFC")
    public String getNMFC() {
        return nMFC;
    }

    /**
     * Setter for NMFC.
     * The National Motor Freight Classification of the package.
     * @param nMFC Value for String
     */
    @JsonSetter("NMFC")
    public void setNMFC(String nMFC) {
        this.nMFC = nMFC;
    }

    /**
     * Getter for ShipAfterTime.
     * ShipAfterTime for a a Freight Shipment
     * @return Returns the String
     */
    @JsonGetter("ShipAfterTime")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ShipAfterTime")
    public String getShipAfterTime() {
        return shipAfterTime;
    }

    /**
     * Setter for ShipAfterTime.
     * ShipAfterTime for a a Freight Shipment
     * @param shipAfterTime Value for String
     */
    @JsonSetter("ShipAfterTime")
    public void setShipAfterTime(String shipAfterTime) {
        this.shipAfterTime = shipAfterTime;
    }

    /**
     * Getter for ShipBeforeTime.
     * ShipBeforeTime for a a Freight Shipment
     * @return Returns the String
     */
    @JsonGetter("ShipBeforeTime")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ShipBeforeTime")
    public String getShipBeforeTime() {
        return shipBeforeTime;
    }

    /**
     * Setter for ShipBeforeTime.
     * ShipBeforeTime for a a Freight Shipment
     * @param shipBeforeTime Value for String
     */
    @JsonSetter("ShipBeforeTime")
    public void setShipBeforeTime(String shipBeforeTime) {
        this.shipBeforeTime = shipBeforeTime;
    }

    /**
     * Converts this Freight1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Freight1 [" + "billing=" + billing + ", freightHandlingLength="
                + freightHandlingLength + ", freightHandlingWidth=" + freightHandlingWidth
                + ", freightHandlingHeight=" + freightHandlingHeight
                + ", freightHandlingPalletWeight=" + freightHandlingPalletWeight
                + ", mixedFreightParcelMode=" + mixedFreightParcelMode + ", freightClass="
                + freightClass + ", nMFC=" + nMFC + ", shipAfterTime=" + shipAfterTime
                + ", shipBeforeTime=" + shipBeforeTime + "]";
    }

    /**
     * Builds a new {@link Freight1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Freight1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .billing(getBilling())
                .freightHandlingLength(getFreightHandlingLength())
                .freightHandlingWidth(getFreightHandlingWidth())
                .freightHandlingHeight(getFreightHandlingHeight())
                .freightHandlingPalletWeight(getFreightHandlingPalletWeight())
                .mixedFreightParcelMode(getMixedFreightParcelMode())
                .freightClass(getFreightClass())
                .nMFC(getNMFC())
                .shipAfterTime(getShipAfterTime())
                .shipBeforeTime(getShipBeforeTime());
        return builder;
    }

    /**
     * Class to build instances of {@link Freight1}.
     */
    public static class Builder {
        private Billing1 billing;
        private Double freightHandlingLength = 0d;
        private Double freightHandlingWidth = 0d;
        private Double freightHandlingHeight = 0d;
        private Double freightHandlingPalletWeight = 0d;
        private Boolean mixedFreightParcelMode = false;
        private String freightClass;
        private String nMFC;
        private String shipAfterTime;
        private String shipBeforeTime;



        /**
         * Setter for billing.
         * @param  billing  Billing1 value for billing.
         * @return Builder
         */
        public Builder billing(Billing1 billing) {
            this.billing = billing;
            return this;
        }

        /**
         * Setter for freightHandlingLength.
         * @param  freightHandlingLength  Double value for freightHandlingLength.
         * @return Builder
         */
        public Builder freightHandlingLength(Double freightHandlingLength) {
            this.freightHandlingLength = freightHandlingLength;
            return this;
        }

        /**
         * Setter for freightHandlingWidth.
         * @param  freightHandlingWidth  Double value for freightHandlingWidth.
         * @return Builder
         */
        public Builder freightHandlingWidth(Double freightHandlingWidth) {
            this.freightHandlingWidth = freightHandlingWidth;
            return this;
        }

        /**
         * Setter for freightHandlingHeight.
         * @param  freightHandlingHeight  Double value for freightHandlingHeight.
         * @return Builder
         */
        public Builder freightHandlingHeight(Double freightHandlingHeight) {
            this.freightHandlingHeight = freightHandlingHeight;
            return this;
        }

        /**
         * Setter for freightHandlingPalletWeight.
         * @param  freightHandlingPalletWeight  Double value for freightHandlingPalletWeight.
         * @return Builder
         */
        public Builder freightHandlingPalletWeight(Double freightHandlingPalletWeight) {
            this.freightHandlingPalletWeight = freightHandlingPalletWeight;
            return this;
        }

        /**
         * Setter for mixedFreightParcelMode.
         * @param  mixedFreightParcelMode  Boolean value for mixedFreightParcelMode.
         * @return Builder
         */
        public Builder mixedFreightParcelMode(Boolean mixedFreightParcelMode) {
            this.mixedFreightParcelMode = mixedFreightParcelMode;
            return this;
        }

        /**
         * Setter for freightClass.
         * @param  freightClass  String value for freightClass.
         * @return Builder
         */
        public Builder freightClass(String freightClass) {
            this.freightClass = freightClass;
            return this;
        }

        /**
         * Setter for nMFC.
         * @param  nMFC  String value for nMFC.
         * @return Builder
         */
        public Builder nMFC(String nMFC) {
            this.nMFC = nMFC;
            return this;
        }

        /**
         * Setter for shipAfterTime.
         * @param  shipAfterTime  String value for shipAfterTime.
         * @return Builder
         */
        public Builder shipAfterTime(String shipAfterTime) {
            this.shipAfterTime = shipAfterTime;
            return this;
        }

        /**
         * Setter for shipBeforeTime.
         * @param  shipBeforeTime  String value for shipBeforeTime.
         * @return Builder
         */
        public Builder shipBeforeTime(String shipBeforeTime) {
            this.shipBeforeTime = shipBeforeTime;
            return this;
        }

        /**
         * Builds a new {@link Freight1} object using the set fields.
         * @return {@link Freight1}
         */
        public Freight1 build() {
            return new Freight1(billing, freightHandlingLength, freightHandlingWidth,
                    freightHandlingHeight, freightHandlingPalletWeight, mixedFreightParcelMode,
                    freightClass, nMFC, shipAfterTime, shipBeforeTime);
        }
    }
}
