/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * InternationalControlledExportLicenseTypeEnum to be used.
 */
public enum InternationalControlledExportLicenseTypeEnum {
    @javax.xml.bind.annotation.XmlEnumValue("1")
    ENUM_1,

    @javax.xml.bind.annotation.XmlEnumValue("2")
    ENUM_2,

    @javax.xml.bind.annotation.XmlEnumValue("3")
    ENUM_3,

    @javax.xml.bind.annotation.XmlEnumValue("4")
    ENUM_4,

    @javax.xml.bind.annotation.XmlEnumValue("5")
    ENUM_5,

    @javax.xml.bind.annotation.XmlEnumValue("6")
    ENUM_6,

    @javax.xml.bind.annotation.XmlEnumValue("7")
    ENUM_7,

    @javax.xml.bind.annotation.XmlEnumValue("8")
    ENUM_8,

    @javax.xml.bind.annotation.XmlEnumValue("9")
    ENUM_9,

    @javax.xml.bind.annotation.XmlEnumValue("10")
    ENUM_10,

    @javax.xml.bind.annotation.XmlEnumValue("11")
    ENUM_11;

    private static TreeMap<Integer, InternationalControlledExportLicenseTypeEnum> valueMap = new TreeMap<>();
    private Integer value;

    static {
        ENUM_1.value = 1;
        ENUM_2.value = 2;
        ENUM_3.value = 3;
        ENUM_4.value = 4;
        ENUM_5.value = 5;
        ENUM_6.value = 6;
        ENUM_7.value = 7;
        ENUM_8.value = 8;
        ENUM_9.value = 9;
        ENUM_10.value = 10;
        ENUM_11.value = 11;

        valueMap.put(1, ENUM_1);
        valueMap.put(2, ENUM_2);
        valueMap.put(3, ENUM_3);
        valueMap.put(4, ENUM_4);
        valueMap.put(5, ENUM_5);
        valueMap.put(6, ENUM_6);
        valueMap.put(7, ENUM_7);
        valueMap.put(8, ENUM_8);
        valueMap.put(9, ENUM_9);
        valueMap.put(10, ENUM_10);
        valueMap.put(11, ENUM_11);
    }

    /**
     * Returns the enum member associated with the given integer value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given integer value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static InternationalControlledExportLicenseTypeEnum constructFromInteger(Integer toConvert) throws IOException {
        InternationalControlledExportLicenseTypeEnum enumValue = fromInteger(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given integer value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given integer value.
     */
    public static InternationalControlledExportLicenseTypeEnum fromInteger(Integer toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the integer value associated with the enum member.
     * @return The integer value against enum member.
     */
    @JsonValue
    public Integer value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of InternationalControlledExportLicenseTypeEnum values to list of integer values.
     * @param toConvert The list of InternationalControlledExportLicenseTypeEnum values to convert.
     * @return List of representative integer values.
     */
    public static List<Integer> toValue(List<InternationalControlledExportLicenseTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<Integer> convertedValues = new ArrayList<>();
        for (InternationalControlledExportLicenseTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 