/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for International3 type.
 */
public class International3 {
    private Contents3 contents;

    /**
     * Default constructor.
     */
    public International3() {
    }

    /**
     * Initialization constructor.
     * @param  contents  Contents3 value for contents.
     */
    public International3(
            Contents3 contents) {
        this.contents = contents;
    }

    /**
     * Getter for Contents.
     * Container for all contents (line items) associated with the transaction.
     * @return Returns the Contents3
     */
    @JsonGetter("Contents")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Contents")
    public Contents3 getContents() {
        return contents;
    }

    /**
     * Setter for Contents.
     * Container for all contents (line items) associated with the transaction.
     * @param contents Value for Contents3
     */
    @JsonSetter("Contents")
    public void setContents(Contents3 contents) {
        this.contents = contents;
    }

    /**
     * Converts this International3 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "International3 [" + "contents=" + contents + "]";
    }

    /**
     * Builds a new {@link International3.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link International3.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .contents(getContents());
        return builder;
    }

    /**
     * Class to build instances of {@link International3}.
     */
    public static class Builder {
        private Contents3 contents;



        /**
         * Setter for contents.
         * @param  contents  Contents3 value for contents.
         * @return Builder
         */
        public Builder contents(Contents3 contents) {
            this.contents = contents;
            return this;
        }

        /**
         * Builds a new {@link International3} object using the set fields.
         * @return {@link International3}
         */
        public International3 build() {
            return new International3(contents);
        }
    }
}
