/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for International10 type.
 */
public class International10 {
    private Boolean documentsOnly;
    private Contents8 contents;

    /**
     * Default constructor.
     */
    public International10() {
        documentsOnly = false;
    }

    /**
     * Initialization constructor.
     * @param  documentsOnly  Boolean value for documentsOnly.
     * @param  contents  Contents8 value for contents.
     */
    public International10(
            Boolean documentsOnly,
            Contents8 contents) {
        this.documentsOnly = documentsOnly;
        this.contents = contents;
    }

    /**
     * Getter for DocumentsOnly.
     * Indicates if the item only contained documents.
     * @return Returns the Boolean
     */
    @JsonGetter("DocumentsOnly")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "DocumentsOnly")
    public Boolean getDocumentsOnly() {
        return documentsOnly;
    }

    /**
     * Setter for DocumentsOnly.
     * Indicates if the item only contained documents.
     * @param documentsOnly Value for Boolean
     */
    @JsonSetter("DocumentsOnly")
    public void setDocumentsOnly(Boolean documentsOnly) {
        this.documentsOnly = documentsOnly;
    }

    /**
     * Getter for Contents.
     * Container for all contents (line items) associated with the transaction.
     * @return Returns the Contents8
     */
    @JsonGetter("Contents")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Contents")
    public Contents8 getContents() {
        return contents;
    }

    /**
     * Setter for Contents.
     * Container for all contents (line items) associated with the transaction.
     * @param contents Value for Contents8
     */
    @JsonSetter("Contents")
    public void setContents(Contents8 contents) {
        this.contents = contents;
    }

    /**
     * Converts this International10 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "International10 [" + "documentsOnly=" + documentsOnly + ", contents=" + contents
                + "]";
    }

    /**
     * Builds a new {@link International10.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link International10.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .documentsOnly(getDocumentsOnly())
                .contents(getContents());
        return builder;
    }

    /**
     * Class to build instances of {@link International10}.
     */
    public static class Builder {
        private Boolean documentsOnly = false;
        private Contents8 contents;



        /**
         * Setter for documentsOnly.
         * @param  documentsOnly  Boolean value for documentsOnly.
         * @return Builder
         */
        public Builder documentsOnly(Boolean documentsOnly) {
            this.documentsOnly = documentsOnly;
            return this;
        }

        /**
         * Setter for contents.
         * @param  contents  Contents8 value for contents.
         * @return Builder
         */
        public Builder contents(Contents8 contents) {
            this.contents = contents;
            return this;
        }

        /**
         * Builds a new {@link International10} object using the set fields.
         * @return {@link International10}
         */
        public International10 build() {
            return new International10(documentsOnly, contents);
        }
    }
}
