/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for LabelOriginAddress type.
 */
public class LabelOriginAddress {
    private String name;
    private String companyName;
    private String street;
    private String locale;
    private String city;
    private String region;
    private String postalCode;
    private String country;
    private String phone;
    private String email;
    private Boolean residential;

    /**
     * Default constructor.
     */
    public LabelOriginAddress() {
        residential = false;
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  companyName  String value for companyName.
     * @param  street  String value for street.
     * @param  locale  String value for locale.
     * @param  city  String value for city.
     * @param  region  String value for region.
     * @param  postalCode  String value for postalCode.
     * @param  country  String value for country.
     * @param  phone  String value for phone.
     * @param  email  String value for email.
     * @param  residential  Boolean value for residential.
     */
    public LabelOriginAddress(
            String name,
            String companyName,
            String street,
            String locale,
            String city,
            String region,
            String postalCode,
            String country,
            String phone,
            String email,
            Boolean residential) {
        this.name = name;
        this.companyName = companyName;
        this.street = street;
        this.locale = locale;
        this.city = city;
        this.region = region;
        this.postalCode = postalCode;
        this.country = country;
        this.phone = phone;
        this.email = email;
        this.residential = residential;
    }

    /**
     * Getter for Name.
     * Name of the individual sending the shipment to show on the label.
     * @return Returns the String
     */
    @JsonGetter("Name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Name of the individual sending the shipment to show on the label.
     * @param name Value for String
     */
    @JsonSetter("Name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for CompanyName.
     * The company name associated with the address to show on the label.
     * @return Returns the String
     */
    @JsonGetter("CompanyName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "CompanyName")
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Setter for CompanyName.
     * The company name associated with the address to show on the label.
     * @param companyName Value for String
     */
    @JsonSetter("CompanyName")
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * Getter for Street.
     * First line of the address to show on the label.
     * @return Returns the String
     */
    @JsonGetter("Street")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Street")
    public String getStreet() {
        return street;
    }

    /**
     * Setter for Street.
     * First line of the address to show on the label.
     * @param street Value for String
     */
    @JsonSetter("Street")
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * Getter for Locale.
     * Second line of the address to show on the label.
     * @return Returns the String
     */
    @JsonGetter("Locale")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Locale")
    public String getLocale() {
        return locale;
    }

    /**
     * Setter for Locale.
     * Second line of the address to show on the label.
     * @param locale Value for String
     */
    @JsonSetter("Locale")
    public void setLocale(String locale) {
        this.locale = locale;
    }

    /**
     * Getter for City.
     * City of the address to show on the label.
     * @return Returns the String
     */
    @JsonGetter("City")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "City")
    public String getCity() {
        return city;
    }

    /**
     * Setter for City.
     * City of the address to show on the label.
     * @param city Value for String
     */
    @JsonSetter("City")
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for Region.
     * The state or region of the address to show on the label.
     * @return Returns the String
     */
    @JsonGetter("Region")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Region")
    public String getRegion() {
        return region;
    }

    /**
     * Setter for Region.
     * The state or region of the address to show on the label.
     * @param region Value for String
     */
    @JsonSetter("Region")
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * Getter for PostalCode.
     * The postal code or zip associated with the address to show on the label.
     * @return Returns the String
     */
    @JsonGetter("PostalCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PostalCode")
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Setter for PostalCode.
     * The postal code or zip associated with the address to show on the label.
     * @param postalCode Value for String
     */
    @JsonSetter("PostalCode")
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * Getter for Country.
     * The country code for the address to show on the label.
     * @return Returns the String
     */
    @JsonGetter("Country")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Country")
    public String getCountry() {
        return country;
    }

    /**
     * Setter for Country.
     * The country code for the address to show on the label.
     * @param country Value for String
     */
    @JsonSetter("Country")
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for Phone.
     * The phone number associated with the address to show on the label.
     * @return Returns the String
     */
    @JsonGetter("Phone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Phone")
    public String getPhone() {
        return phone;
    }

    /**
     * Setter for Phone.
     * The phone number associated with the address to show on the label.
     * @param phone Value for String
     */
    @JsonSetter("Phone")
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for Email.
     * An email address for the individual or company to show on the label.
     * @return Returns the String
     */
    @JsonGetter("Email")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Email")
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * An email address for the individual or company to show on the label.
     * @param email Value for String
     */
    @JsonSetter("Email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for Residential.
     * Indicates whether the address is residential or commercial.
     * @return Returns the Boolean
     */
    @JsonGetter("Residential")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Residential")
    public Boolean getResidential() {
        return residential;
    }

    /**
     * Setter for Residential.
     * Indicates whether the address is residential or commercial.
     * @param residential Value for Boolean
     */
    @JsonSetter("Residential")
    public void setResidential(Boolean residential) {
        this.residential = residential;
    }

    /**
     * Converts this LabelOriginAddress into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LabelOriginAddress [" + "name=" + name + ", companyName=" + companyName
                + ", street=" + street + ", locale=" + locale + ", city=" + city + ", region="
                + region + ", postalCode=" + postalCode + ", country=" + country + ", phone="
                + phone + ", email=" + email + ", residential=" + residential + "]";
    }

    /**
     * Builds a new {@link LabelOriginAddress.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LabelOriginAddress.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .name(getName())
                .companyName(getCompanyName())
                .street(getStreet())
                .locale(getLocale())
                .city(getCity())
                .region(getRegion())
                .postalCode(getPostalCode())
                .country(getCountry())
                .phone(getPhone())
                .email(getEmail())
                .residential(getResidential());
        return builder;
    }

    /**
     * Class to build instances of {@link LabelOriginAddress}.
     */
    public static class Builder {
        private String name;
        private String companyName;
        private String street;
        private String locale;
        private String city;
        private String region;
        private String postalCode;
        private String country;
        private String phone;
        private String email;
        private Boolean residential = false;



        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for companyName.
         * @param  companyName  String value for companyName.
         * @return Builder
         */
        public Builder companyName(String companyName) {
            this.companyName = companyName;
            return this;
        }

        /**
         * Setter for street.
         * @param  street  String value for street.
         * @return Builder
         */
        public Builder street(String street) {
            this.street = street;
            return this;
        }

        /**
         * Setter for locale.
         * @param  locale  String value for locale.
         * @return Builder
         */
        public Builder locale(String locale) {
            this.locale = locale;
            return this;
        }

        /**
         * Setter for city.
         * @param  city  String value for city.
         * @return Builder
         */
        public Builder city(String city) {
            this.city = city;
            return this;
        }

        /**
         * Setter for region.
         * @param  region  String value for region.
         * @return Builder
         */
        public Builder region(String region) {
            this.region = region;
            return this;
        }

        /**
         * Setter for postalCode.
         * @param  postalCode  String value for postalCode.
         * @return Builder
         */
        public Builder postalCode(String postalCode) {
            this.postalCode = postalCode;
            return this;
        }

        /**
         * Setter for country.
         * @param  country  String value for country.
         * @return Builder
         */
        public Builder country(String country) {
            this.country = country;
            return this;
        }

        /**
         * Setter for phone.
         * @param  phone  String value for phone.
         * @return Builder
         */
        public Builder phone(String phone) {
            this.phone = phone;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for residential.
         * @param  residential  Boolean value for residential.
         * @return Builder
         */
        public Builder residential(Boolean residential) {
            this.residential = residential;
            return this;
        }

        /**
         * Builds a new {@link LabelOriginAddress} object using the set fields.
         * @return {@link LabelOriginAddress}
         */
        public LabelOriginAddress build() {
            return new LabelOriginAddress(name, companyName, street, locale, city, region,
                    postalCode, country, phone, email, residential);
        }
    }
}
