/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Order2 type.
 */
public class Order2 {
    private Integer orderID;
    private String orderNumber;
    private String releaseNumber;
    private String orderReference1;
    private String orderReference2;
    private String orderReference3;
    private String salesOrderNumber;
    private String purchaseOrderNumber;
    private RecordIdentifiers3 recordIdentifiers;

    /**
     * Default constructor.
     */
    public Order2() {
        orderID = 0;
    }

    /**
     * Initialization constructor.
     * @param  orderID  Integer value for orderID.
     * @param  orderNumber  String value for orderNumber.
     * @param  releaseNumber  String value for releaseNumber.
     * @param  orderReference1  String value for orderReference1.
     * @param  orderReference2  String value for orderReference2.
     * @param  orderReference3  String value for orderReference3.
     * @param  salesOrderNumber  String value for salesOrderNumber.
     * @param  purchaseOrderNumber  String value for purchaseOrderNumber.
     * @param  recordIdentifiers  RecordIdentifiers3 value for recordIdentifiers.
     */
    public Order2(
            Integer orderID,
            String orderNumber,
            String releaseNumber,
            String orderReference1,
            String orderReference2,
            String orderReference3,
            String salesOrderNumber,
            String purchaseOrderNumber,
            RecordIdentifiers3 recordIdentifiers) {
        this.orderID = orderID;
        this.orderNumber = orderNumber;
        this.releaseNumber = releaseNumber;
        this.orderReference1 = orderReference1;
        this.orderReference2 = orderReference2;
        this.orderReference3 = orderReference3;
        this.salesOrderNumber = salesOrderNumber;
        this.purchaseOrderNumber = purchaseOrderNumber;
        this.recordIdentifiers = recordIdentifiers;
    }

    /**
     * Getter for OrderID.
     * Identifier of the order being shipped.
     * @return Returns the Integer
     */
    @JsonGetter("OrderID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OrderID")
    public Integer getOrderID() {
        return orderID;
    }

    /**
     * Setter for OrderID.
     * Identifier of the order being shipped.
     * @param orderID Value for Integer
     */
    @JsonSetter("OrderID")
    public void setOrderID(Integer orderID) {
        this.orderID = orderID;
    }

    /**
     * Getter for OrderNumber.
     * Number of the order being shipped.
     * @return Returns the String
     */
    @JsonGetter("OrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OrderNumber")
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * Setter for OrderNumber.
     * Number of the order being shipped.
     * @param orderNumber Value for String
     */
    @JsonSetter("OrderNumber")
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * Getter for ReleaseNumber.
     * Release number of the order being shipped.
     * @return Returns the String
     */
    @JsonGetter("ReleaseNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ReleaseNumber")
    public String getReleaseNumber() {
        return releaseNumber;
    }

    /**
     * Setter for ReleaseNumber.
     * Release number of the order being shipped.
     * @param releaseNumber Value for String
     */
    @JsonSetter("ReleaseNumber")
    public void setReleaseNumber(String releaseNumber) {
        this.releaseNumber = releaseNumber;
    }

    /**
     * Getter for OrderReference1.
     * First order reference number.
     * @return Returns the String
     */
    @JsonGetter("OrderReference1")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OrderReference1")
    public String getOrderReference1() {
        return orderReference1;
    }

    /**
     * Setter for OrderReference1.
     * First order reference number.
     * @param orderReference1 Value for String
     */
    @JsonSetter("OrderReference1")
    public void setOrderReference1(String orderReference1) {
        this.orderReference1 = orderReference1;
    }

    /**
     * Getter for OrderReference2.
     * Second order reference number.
     * @return Returns the String
     */
    @JsonGetter("OrderReference2")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OrderReference2")
    public String getOrderReference2() {
        return orderReference2;
    }

    /**
     * Setter for OrderReference2.
     * Second order reference number.
     * @param orderReference2 Value for String
     */
    @JsonSetter("OrderReference2")
    public void setOrderReference2(String orderReference2) {
        this.orderReference2 = orderReference2;
    }

    /**
     * Getter for OrderReference3.
     * Third order reference number.
     * @return Returns the String
     */
    @JsonGetter("OrderReference3")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OrderReference3")
    public String getOrderReference3() {
        return orderReference3;
    }

    /**
     * Setter for OrderReference3.
     * Third order reference number.
     * @param orderReference3 Value for String
     */
    @JsonSetter("OrderReference3")
    public void setOrderReference3(String orderReference3) {
        this.orderReference3 = orderReference3;
    }

    /**
     * Getter for SalesOrderNumber.
     * Sales order number of the order being shipped.
     * @return Returns the String
     */
    @JsonGetter("SalesOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "SalesOrderNumber")
    public String getSalesOrderNumber() {
        return salesOrderNumber;
    }

    /**
     * Setter for SalesOrderNumber.
     * Sales order number of the order being shipped.
     * @param salesOrderNumber Value for String
     */
    @JsonSetter("SalesOrderNumber")
    public void setSalesOrderNumber(String salesOrderNumber) {
        this.salesOrderNumber = salesOrderNumber;
    }

    /**
     * Getter for PurchaseOrderNumber.
     * Purchase order number of the order being shipped.
     * @return Returns the String
     */
    @JsonGetter("PurchaseOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PurchaseOrderNumber")
    public String getPurchaseOrderNumber() {
        return purchaseOrderNumber;
    }

    /**
     * Setter for PurchaseOrderNumber.
     * Purchase order number of the order being shipped.
     * @param purchaseOrderNumber Value for String
     */
    @JsonSetter("PurchaseOrderNumber")
    public void setPurchaseOrderNumber(String purchaseOrderNumber) {
        this.purchaseOrderNumber = purchaseOrderNumber;
    }

    /**
     * Getter for RecordIdentifiers.
     * Outer container for transaction identifiers.
     * @return Returns the RecordIdentifiers3
     */
    @JsonGetter("RecordIdentifiers")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "RecordIdentifiers")
    public RecordIdentifiers3 getRecordIdentifiers() {
        return recordIdentifiers;
    }

    /**
     * Setter for RecordIdentifiers.
     * Outer container for transaction identifiers.
     * @param recordIdentifiers Value for RecordIdentifiers3
     */
    @JsonSetter("RecordIdentifiers")
    public void setRecordIdentifiers(RecordIdentifiers3 recordIdentifiers) {
        this.recordIdentifiers = recordIdentifiers;
    }

    /**
     * Converts this Order2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Order2 [" + "orderID=" + orderID + ", orderNumber=" + orderNumber
                + ", releaseNumber=" + releaseNumber + ", orderReference1=" + orderReference1
                + ", orderReference2=" + orderReference2 + ", orderReference3=" + orderReference3
                + ", salesOrderNumber=" + salesOrderNumber + ", purchaseOrderNumber="
                + purchaseOrderNumber + ", recordIdentifiers=" + recordIdentifiers + "]";
    }

    /**
     * Builds a new {@link Order2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Order2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .orderID(getOrderID())
                .orderNumber(getOrderNumber())
                .releaseNumber(getReleaseNumber())
                .orderReference1(getOrderReference1())
                .orderReference2(getOrderReference2())
                .orderReference3(getOrderReference3())
                .salesOrderNumber(getSalesOrderNumber())
                .purchaseOrderNumber(getPurchaseOrderNumber())
                .recordIdentifiers(getRecordIdentifiers());
        return builder;
    }

    /**
     * Class to build instances of {@link Order2}.
     */
    public static class Builder {
        private Integer orderID = 0;
        private String orderNumber;
        private String releaseNumber;
        private String orderReference1;
        private String orderReference2;
        private String orderReference3;
        private String salesOrderNumber;
        private String purchaseOrderNumber;
        private RecordIdentifiers3 recordIdentifiers;



        /**
         * Setter for orderID.
         * @param  orderID  Integer value for orderID.
         * @return Builder
         */
        public Builder orderID(Integer orderID) {
            this.orderID = orderID;
            return this;
        }

        /**
         * Setter for orderNumber.
         * @param  orderNumber  String value for orderNumber.
         * @return Builder
         */
        public Builder orderNumber(String orderNumber) {
            this.orderNumber = orderNumber;
            return this;
        }

        /**
         * Setter for releaseNumber.
         * @param  releaseNumber  String value for releaseNumber.
         * @return Builder
         */
        public Builder releaseNumber(String releaseNumber) {
            this.releaseNumber = releaseNumber;
            return this;
        }

        /**
         * Setter for orderReference1.
         * @param  orderReference1  String value for orderReference1.
         * @return Builder
         */
        public Builder orderReference1(String orderReference1) {
            this.orderReference1 = orderReference1;
            return this;
        }

        /**
         * Setter for orderReference2.
         * @param  orderReference2  String value for orderReference2.
         * @return Builder
         */
        public Builder orderReference2(String orderReference2) {
            this.orderReference2 = orderReference2;
            return this;
        }

        /**
         * Setter for orderReference3.
         * @param  orderReference3  String value for orderReference3.
         * @return Builder
         */
        public Builder orderReference3(String orderReference3) {
            this.orderReference3 = orderReference3;
            return this;
        }

        /**
         * Setter for salesOrderNumber.
         * @param  salesOrderNumber  String value for salesOrderNumber.
         * @return Builder
         */
        public Builder salesOrderNumber(String salesOrderNumber) {
            this.salesOrderNumber = salesOrderNumber;
            return this;
        }

        /**
         * Setter for purchaseOrderNumber.
         * @param  purchaseOrderNumber  String value for purchaseOrderNumber.
         * @return Builder
         */
        public Builder purchaseOrderNumber(String purchaseOrderNumber) {
            this.purchaseOrderNumber = purchaseOrderNumber;
            return this;
        }

        /**
         * Setter for recordIdentifiers.
         * @param  recordIdentifiers  RecordIdentifiers3 value for recordIdentifiers.
         * @return Builder
         */
        public Builder recordIdentifiers(RecordIdentifiers3 recordIdentifiers) {
            this.recordIdentifiers = recordIdentifiers;
            return this;
        }

        /**
         * Builds a new {@link Order2} object using the set fields.
         * @return {@link Order2}
         */
        public Order2 build() {
            return new Order2(orderID, orderNumber, releaseNumber, orderReference1, orderReference2,
                    orderReference3, salesOrderNumber, purchaseOrderNumber, recordIdentifiers);
        }
    }
}
