/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Order type.
 */
public class Order {
    private Integer orderID;
    private PickLists pickLists;
    private String orderNumber;

    /**
     * Default constructor.
     */
    public Order() {
        orderID = 0;
    }

    /**
     * Initialization constructor.
     * @param  orderID  Integer value for orderID.
     * @param  pickLists  PickLists value for pickLists.
     * @param  orderNumber  String value for orderNumber.
     */
    public Order(
            Integer orderID,
            PickLists pickLists,
            String orderNumber) {
        this.orderID = orderID;
        this.pickLists = pickLists;
        this.orderNumber = orderNumber;
    }

    /**
     * Getter for OrderID.
     * Identifier of the order being rated.
     * @return Returns the Integer
     */
    @JsonGetter("OrderID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OrderID")
    public Integer getOrderID() {
        return orderID;
    }

    /**
     * Setter for OrderID.
     * Identifier of the order being rated.
     * @param orderID Value for Integer
     */
    @JsonSetter("OrderID")
    public void setOrderID(Integer orderID) {
        this.orderID = orderID;
    }

    /**
     * Getter for PickLists.
     * Container all order picklists.
     * @return Returns the PickLists
     */
    @JsonGetter("PickLists")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PickLists")
    public PickLists getPickLists() {
        return pickLists;
    }

    /**
     * Setter for PickLists.
     * Container all order picklists.
     * @param pickLists Value for PickLists
     */
    @JsonSetter("PickLists")
    public void setPickLists(PickLists pickLists) {
        this.pickLists = pickLists;
    }

    /**
     * Getter for OrderNumber.
     * Order number of the order being rated.
     * @return Returns the String
     */
    @JsonGetter("OrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OrderNumber")
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * Setter for OrderNumber.
     * Order number of the order being rated.
     * @param orderNumber Value for String
     */
    @JsonSetter("OrderNumber")
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * Converts this Order into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Order [" + "orderID=" + orderID + ", pickLists=" + pickLists + ", orderNumber="
                + orderNumber + "]";
    }

    /**
     * Builds a new {@link Order.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Order.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .orderID(getOrderID())
                .pickLists(getPickLists())
                .orderNumber(getOrderNumber());
        return builder;
    }

    /**
     * Class to build instances of {@link Order}.
     */
    public static class Builder {
        private Integer orderID = 0;
        private PickLists pickLists;
        private String orderNumber;



        /**
         * Setter for orderID.
         * @param  orderID  Integer value for orderID.
         * @return Builder
         */
        public Builder orderID(Integer orderID) {
            this.orderID = orderID;
            return this;
        }

        /**
         * Setter for pickLists.
         * @param  pickLists  PickLists value for pickLists.
         * @return Builder
         */
        public Builder pickLists(PickLists pickLists) {
            this.pickLists = pickLists;
            return this;
        }

        /**
         * Setter for orderNumber.
         * @param  orderNumber  String value for orderNumber.
         * @return Builder
         */
        public Builder orderNumber(String orderNumber) {
            this.orderNumber = orderNumber;
            return this;
        }

        /**
         * Builds a new {@link Order} object using the set fields.
         * @return {@link Order}
         */
        public Order build() {
            return new Order(orderID, pickLists, orderNumber);
        }
    }
}
