/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Outputs type.
 */
public class Outputs {
    private List<Output> output;

    /**
     * Default constructor.
     */
    public Outputs() {
    }

    /**
     * Initialization constructor.
     * @param  output  List of Output value for output.
     */
    public Outputs(
            List<Output> output) {
        this.output = output;
    }

    /**
     * Getter for Output.
     * Container for an output the transaction should generate or customize the printing of.
     * @return Returns the List of Output
     */
    @JsonGetter("Output")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Output")
    public List<Output> getOutput() {
        return output;
    }

    /**
     * Setter for Output.
     * Container for an output the transaction should generate or customize the printing of.
     * @param output Value for List of Output
     */
    @JsonSetter("Output")
    public void setOutput(List<Output> output) {
        this.output = output;
    }

    /**
     * Converts this Outputs into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Outputs [" + "output=" + output + "]";
    }

    /**
     * Builds a new {@link Outputs.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Outputs.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .output(getOutput());
        return builder;
    }

    /**
     * Class to build instances of {@link Outputs}.
     */
    public static class Builder {
        private List<Output> output;



        /**
         * Setter for output.
         * @param  output  List of Output value for output.
         * @return Builder
         */
        public Builder output(List<Output> output) {
            this.output = output;
            return this;
        }

        /**
         * Builds a new {@link Outputs} object using the set fields.
         * @return {@link Outputs}
         */
        public Outputs build() {
            return new Outputs(output);
        }
    }
}
