/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Packages7 type.
 */
public class Packages7 {
    private List<Package8> mPackage;

    /**
     * Default constructor.
     */
    public Packages7() {
    }

    /**
     * Initialization constructor.
     * @param  mPackage  List of Package8 value for mPackage.
     */
    public Packages7(
            List<Package8> mPackage) {
        this.mPackage = mPackage;
    }

    /**
     * Getter for Package.
     * Container for an individual package associated with the transaction.
     * @return Returns the List of Package8
     */
    @JsonGetter("Package")
    @XmlElement(name = "Package")
    public List<Package8> getPackage() {
        return mPackage;
    }

    /**
     * Setter for Package.
     * Container for an individual package associated with the transaction.
     * @param mPackage Value for List of Package8
     */
    @JsonSetter("Package")
    public void setPackage(List<Package8> mPackage) {
        this.mPackage = mPackage;
    }

    /**
     * Converts this Packages7 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Packages7 [" + "mPackage=" + mPackage + "]";
    }

    /**
     * Builds a new {@link Packages7.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Packages7.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(mPackage);
        return builder;
    }

    /**
     * Class to build instances of {@link Packages7}.
     */
    public static class Builder {
        private List<Package8> mPackage;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  mPackage  List of Package8 value for mPackage.
         */
        public Builder(List<Package8> mPackage) {
            this.mPackage = mPackage;
        }

        /**
         * Setter for mPackage.
         * @param  mPackage  List of Package8 value for mPackage.
         * @return Builder
         */
        public Builder mPackage(List<Package8> mPackage) {
            this.mPackage = mPackage;
            return this;
        }

        /**
         * Builds a new {@link Packages7} object using the set fields.
         * @return {@link Packages7}
         */
        public Packages7 build() {
            return new Packages7(mPackage);
        }
    }
}
