/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Package13 type.
 */
public class Package13 {
    private Integer packageID;
    private String wayBillNumber;

    /**
     * Default constructor.
     */
    public Package13() {
        packageID = 0;
    }

    /**
     * Initialization constructor.
     * @param  packageID  Integer value for packageID.
     * @param  wayBillNumber  String value for wayBillNumber.
     */
    public Package13(
            Integer packageID,
            String wayBillNumber) {
        this.packageID = packageID;
        this.wayBillNumber = wayBillNumber;
    }

    /**
     * Getter for PackageID.
     * Identifier of the package to void. Must submit shipment identifier, shipment group
     * identifier, package identifier or tracking number.
     * @return Returns the Integer
     */
    @JsonGetter("PackageID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PackageID")
    public Integer getPackageID() {
        return packageID;
    }

    /**
     * Setter for PackageID.
     * Identifier of the package to void. Must submit shipment identifier, shipment group
     * identifier, package identifier or tracking number.
     * @param packageID Value for Integer
     */
    @JsonSetter("PackageID")
    public void setPackageID(Integer packageID) {
        this.packageID = packageID;
    }

    /**
     * Getter for WayBillNumber.
     * Tracking Number of the package to void. Must submit shipment identifier, shipment group
     * identifier, package identifier or tracking number.
     * @return Returns the String
     */
    @JsonGetter("WayBillNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "WayBillNumber")
    public String getWayBillNumber() {
        return wayBillNumber;
    }

    /**
     * Setter for WayBillNumber.
     * Tracking Number of the package to void. Must submit shipment identifier, shipment group
     * identifier, package identifier or tracking number.
     * @param wayBillNumber Value for String
     */
    @JsonSetter("WayBillNumber")
    public void setWayBillNumber(String wayBillNumber) {
        this.wayBillNumber = wayBillNumber;
    }

    /**
     * Converts this Package13 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Package13 [" + "packageID=" + packageID + ", wayBillNumber=" + wayBillNumber + "]";
    }

    /**
     * Builds a new {@link Package13.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Package13.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .packageID(getPackageID())
                .wayBillNumber(getWayBillNumber());
        return builder;
    }

    /**
     * Class to build instances of {@link Package13}.
     */
    public static class Builder {
        private Integer packageID = 0;
        private String wayBillNumber;



        /**
         * Setter for packageID.
         * @param  packageID  Integer value for packageID.
         * @return Builder
         */
        public Builder packageID(Integer packageID) {
            this.packageID = packageID;
            return this;
        }

        /**
         * Setter for wayBillNumber.
         * @param  wayBillNumber  String value for wayBillNumber.
         * @return Builder
         */
        public Builder wayBillNumber(String wayBillNumber) {
            this.wayBillNumber = wayBillNumber;
            return this;
        }

        /**
         * Builds a new {@link Package13} object using the set fields.
         * @return {@link Package13}
         */
        public Package13 build() {
            return new Package13(packageID, wayBillNumber);
        }
    }
}
