/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for PackageType type.
 */
public class PackageType {
    private int iD;
    private String description;

    /**
     * Default constructor.
     */
    public PackageType() {
    }

    /**
     * Initialization constructor.
     * @param  iD  int value for iD.
     * @param  description  String value for description.
     */
    public PackageType(
            int iD,
            String description) {
        this.iD = iD;
        this.description = description;
    }

    /**
     * Getter for ID.
     * Numeric identifier for the carrier package type.
     * @return Returns the int
     */
    @JsonGetter("ID")
    @XmlElement(name = "ID")
    public int getID() {
        return iD;
    }

    /**
     * Setter for ID.
     * Numeric identifier for the carrier package type.
     * @param iD Value for int
     */
    @JsonSetter("ID")
    public void setID(int iD) {
        this.iD = iD;
    }

    /**
     * Getter for Description.
     * The name for the carrier package type.
     * @return Returns the String
     */
    @JsonGetter("Description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Description")
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * The name for the carrier package type.
     * @param description Value for String
     */
    @JsonSetter("Description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Converts this PackageType into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PackageType [" + "iD=" + iD + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link PackageType.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PackageType.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(iD)
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link PackageType}.
     */
    public static class Builder {
        private int iD;
        private String description;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  iD  int value for iD.
         */
        public Builder(int iD) {
            this.iD = iD;
        }

        /**
         * Setter for iD.
         * @param  iD  int value for iD.
         * @return Builder
         */
        public Builder iD(int iD) {
            this.iD = iD;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link PackageType} object using the set fields.
         * @return {@link PackageType}
         */
        public PackageType build() {
            return new PackageType(iD, description);
        }
    }
}
