/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Package6 type.
 */
public class Package6 {
    private Status status;
    private Boolean additionalHandling;
    private Integer oversize;
    private Integer packageType;
    private String freightClass;
    private String shipperReference;
    private String packageReference;
    private International7 international;

    /**
     * Default constructor.
     */
    public Package6() {
        additionalHandling = false;
        oversize = 0;
        packageType = 0;
    }

    /**
     * Initialization constructor.
     * @param  status  Status value for status.
     * @param  additionalHandling  Boolean value for additionalHandling.
     * @param  oversize  Integer value for oversize.
     * @param  packageType  Integer value for packageType.
     * @param  freightClass  String value for freightClass.
     * @param  shipperReference  String value for shipperReference.
     * @param  packageReference  String value for packageReference.
     * @param  international  International7 value for international.
     */
    public Package6(
            Status status,
            Boolean additionalHandling,
            Integer oversize,
            Integer packageType,
            String freightClass,
            String shipperReference,
            String packageReference,
            International7 international) {
        this.status = status;
        this.additionalHandling = additionalHandling;
        this.oversize = oversize;
        this.packageType = packageType;
        this.freightClass = freightClass;
        this.shipperReference = shipperReference;
        this.packageReference = packageReference;
        this.international = international;
    }

    /**
     * Getter for Status.
     * Container for transaction errors and warning elements.
     * @return Returns the Status
     */
    @JsonGetter("Status")
    @XmlElement(name = "Status")
    public Status getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Container for transaction errors and warning elements.
     * @param status Value for Status
     */
    @JsonSetter("Status")
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * Getter for AdditionalHandling.
     * Indicates that extra handling measures are required when loading the package.
     * @return Returns the Boolean
     */
    @JsonGetter("AdditionalHandling")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "AdditionalHandling")
    public Boolean getAdditionalHandling() {
        return additionalHandling;
    }

    /**
     * Setter for AdditionalHandling.
     * Indicates that extra handling measures are required when loading the package.
     * @param additionalHandling Value for Boolean
     */
    @JsonSetter("AdditionalHandling")
    public void setAdditionalHandling(Boolean additionalHandling) {
        this.additionalHandling = additionalHandling;
    }

    /**
     * Getter for Oversize.
     * Indicates if the item is over standard size dimensions.
     * @return Returns the Integer
     */
    @JsonGetter("Oversize")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Oversize")
    public Integer getOversize() {
        return oversize;
    }

    /**
     * Setter for Oversize.
     * Indicates if the item is over standard size dimensions.
     * @param oversize Value for Integer
     */
    @JsonSetter("Oversize")
    public void setOversize(Integer oversize) {
        this.oversize = oversize;
    }

    /**
     * Getter for PackageType.
     * Numeric identifier for the carrier package type.
     * @return Returns the Integer
     */
    @JsonGetter("PackageType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PackageType")
    public Integer getPackageType() {
        return packageType;
    }

    /**
     * Setter for PackageType.
     * Numeric identifier for the carrier package type.
     * @param packageType Value for Integer
     */
    @JsonSetter("PackageType")
    public void setPackageType(Integer packageType) {
        this.packageType = packageType;
    }

    /**
     * Getter for FreightClass.
     * The freight class of the package's content.
     * @return Returns the String
     */
    @JsonGetter("FreightClass")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "FreightClass")
    public String getFreightClass() {
        return freightClass;
    }

    /**
     * Setter for FreightClass.
     * The freight class of the package's content.
     * @param freightClass Value for String
     */
    @JsonSetter("FreightClass")
    public void setFreightClass(String freightClass) {
        this.freightClass = freightClass;
    }

    /**
     * Getter for ShipperReference.
     * Primary shipping reference number.
     * @return Returns the String
     */
    @JsonGetter("ShipperReference")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ShipperReference")
    public String getShipperReference() {
        return shipperReference;
    }

    /**
     * Setter for ShipperReference.
     * Primary shipping reference number.
     * @param shipperReference Value for String
     */
    @JsonSetter("ShipperReference")
    public void setShipperReference(String shipperReference) {
        this.shipperReference = shipperReference;
    }

    /**
     * Getter for PackageReference.
     * Package reference number, which will be echoed back in the response.
     * @return Returns the String
     */
    @JsonGetter("PackageReference")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PackageReference")
    public String getPackageReference() {
        return packageReference;
    }

    /**
     * Setter for PackageReference.
     * Package reference number, which will be echoed back in the response.
     * @param packageReference Value for String
     */
    @JsonSetter("PackageReference")
    public void setPackageReference(String packageReference) {
        this.packageReference = packageReference;
    }

    /**
     * Getter for International.
     * Container for international details associated with the shipment.
     * @return Returns the International7
     */
    @JsonGetter("International")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "International")
    public International7 getInternational() {
        return international;
    }

    /**
     * Setter for International.
     * Container for international details associated with the shipment.
     * @param international Value for International7
     */
    @JsonSetter("International")
    public void setInternational(International7 international) {
        this.international = international;
    }

    /**
     * Converts this Package6 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Package6 [" + "status=" + status + ", additionalHandling=" + additionalHandling
                + ", oversize=" + oversize + ", packageType=" + packageType + ", freightClass="
                + freightClass + ", shipperReference=" + shipperReference + ", packageReference="
                + packageReference + ", international=" + international + "]";
    }

    /**
     * Builds a new {@link Package6.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Package6.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status)
                .additionalHandling(getAdditionalHandling())
                .oversize(getOversize())
                .packageType(getPackageType())
                .freightClass(getFreightClass())
                .shipperReference(getShipperReference())
                .packageReference(getPackageReference())
                .international(getInternational());
        return builder;
    }

    /**
     * Class to build instances of {@link Package6}.
     */
    public static class Builder {
        private Status status;
        private Boolean additionalHandling = false;
        private Integer oversize = 0;
        private Integer packageType = 0;
        private String freightClass;
        private String shipperReference;
        private String packageReference;
        private International7 international;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  Status value for status.
         */
        public Builder(Status status) {
            this.status = status;
        }

        /**
         * Setter for status.
         * @param  status  Status value for status.
         * @return Builder
         */
        public Builder status(Status status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for additionalHandling.
         * @param  additionalHandling  Boolean value for additionalHandling.
         * @return Builder
         */
        public Builder additionalHandling(Boolean additionalHandling) {
            this.additionalHandling = additionalHandling;
            return this;
        }

        /**
         * Setter for oversize.
         * @param  oversize  Integer value for oversize.
         * @return Builder
         */
        public Builder oversize(Integer oversize) {
            this.oversize = oversize;
            return this;
        }

        /**
         * Setter for packageType.
         * @param  packageType  Integer value for packageType.
         * @return Builder
         */
        public Builder packageType(Integer packageType) {
            this.packageType = packageType;
            return this;
        }

        /**
         * Setter for freightClass.
         * @param  freightClass  String value for freightClass.
         * @return Builder
         */
        public Builder freightClass(String freightClass) {
            this.freightClass = freightClass;
            return this;
        }

        /**
         * Setter for shipperReference.
         * @param  shipperReference  String value for shipperReference.
         * @return Builder
         */
        public Builder shipperReference(String shipperReference) {
            this.shipperReference = shipperReference;
            return this;
        }

        /**
         * Setter for packageReference.
         * @param  packageReference  String value for packageReference.
         * @return Builder
         */
        public Builder packageReference(String packageReference) {
            this.packageReference = packageReference;
            return this;
        }

        /**
         * Setter for international.
         * @param  international  International7 value for international.
         * @return Builder
         */
        public Builder international(International7 international) {
            this.international = international;
            return this;
        }

        /**
         * Builds a new {@link Package6} object using the set fields.
         * @return {@link Package6}
         */
        public Package6 build() {
            return new Package6(status, additionalHandling, oversize, packageType, freightClass,
                    shipperReference, packageReference, international);
        }
    }
}
