/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for PickLists type.
 */
public class PickLists {
    private List<PickList> pickList;

    /**
     * Default constructor.
     */
    public PickLists() {
    }

    /**
     * Initialization constructor.
     * @param  pickList  List of PickList value for pickList.
     */
    public PickLists(
            List<PickList> pickList) {
        this.pickList = pickList;
    }

    /**
     * Getter for PickList.
     * Container for an individual picklist.
     * @return Returns the List of PickList
     */
    @JsonGetter("PickList")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PickList")
    public List<PickList> getPickList() {
        return pickList;
    }

    /**
     * Setter for PickList.
     * Container for an individual picklist.
     * @param pickList Value for List of PickList
     */
    @JsonSetter("PickList")
    public void setPickList(List<PickList> pickList) {
        this.pickList = pickList;
    }

    /**
     * Converts this PickLists into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PickLists [" + "pickList=" + pickList + "]";
    }

    /**
     * Builds a new {@link PickLists.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PickLists.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .pickList(getPickList());
        return builder;
    }

    /**
     * Class to build instances of {@link PickLists}.
     */
    public static class Builder {
        private List<PickList> pickList;



        /**
         * Setter for pickList.
         * @param  pickList  List of PickList value for pickList.
         * @return Builder
         */
        public Builder pickList(List<PickList> pickList) {
            this.pickList = pickList;
            return this;
        }

        /**
         * Builds a new {@link PickLists} object using the set fields.
         * @return {@link PickLists}
         */
        public PickLists build() {
            return new PickLists(pickList);
        }
    }
}
