/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for PickLists1 type.
 */
public class PickLists1 {
    private List<PickList1> pickList;

    /**
     * Default constructor.
     */
    public PickLists1() {
    }

    /**
     * Initialization constructor.
     * @param  pickList  List of PickList1 value for pickList.
     */
    public PickLists1(
            List<PickList1> pickList) {
        this.pickList = pickList;
    }

    /**
     * Getter for PickList.
     * Container for an individual picklist.
     * @return Returns the List of PickList1
     */
    @JsonGetter("PickList")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PickList")
    public List<PickList1> getPickList() {
        return pickList;
    }

    /**
     * Setter for PickList.
     * Container for an individual picklist.
     * @param pickList Value for List of PickList1
     */
    @JsonSetter("PickList")
    public void setPickList(List<PickList1> pickList) {
        this.pickList = pickList;
    }

    /**
     * Converts this PickLists1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PickLists1 [" + "pickList=" + pickList + "]";
    }

    /**
     * Builds a new {@link PickLists1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PickLists1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .pickList(getPickList());
        return builder;
    }

    /**
     * Class to build instances of {@link PickLists1}.
     */
    public static class Builder {
        private List<PickList1> pickList;



        /**
         * Setter for pickList.
         * @param  pickList  List of PickList1 value for pickList.
         * @return Builder
         */
        public Builder pickList(List<PickList1> pickList) {
            this.pickList = pickList;
            return this;
        }

        /**
         * Builds a new {@link PickLists1} object using the set fields.
         * @return {@link PickLists1}
         */
        public PickLists1 build() {
            return new PickLists1(pickList);
        }
    }
}
