/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for PierbridgeAddressValidationRequest type.
 */
public class PierbridgeAddressValidationRequest {
    private String transactionIdentifier;
    private String controlIdentifier;
    private String userName;
    private Integer carrier;
    private Boolean live;
    private Address address;
    private PersonalShipping personalShipping;
    private Diagnostics diagnostics;
    private Identification identification;

    /**
     * Default constructor.
     */
    public PierbridgeAddressValidationRequest() {
        carrier = 0;
        live = false;
    }

    /**
     * Initialization constructor.
     * @param  userName  String value for userName.
     * @param  address  Address value for address.
     * @param  transactionIdentifier  String value for transactionIdentifier.
     * @param  controlIdentifier  String value for controlIdentifier.
     * @param  carrier  Integer value for carrier.
     * @param  live  Boolean value for live.
     * @param  personalShipping  PersonalShipping value for personalShipping.
     * @param  diagnostics  Diagnostics value for diagnostics.
     * @param  identification  Identification value for identification.
     */
    public PierbridgeAddressValidationRequest(
            String userName,
            Address address,
            String transactionIdentifier,
            String controlIdentifier,
            Integer carrier,
            Boolean live,
            PersonalShipping personalShipping,
            Diagnostics diagnostics,
            Identification identification) {
        this.transactionIdentifier = transactionIdentifier;
        this.controlIdentifier = controlIdentifier;
        this.userName = userName;
        this.carrier = carrier;
        this.live = live;
        this.address = address;
        this.personalShipping = personalShipping;
        this.diagnostics = diagnostics;
        this.identification = identification;
    }

    /**
     * Getter for TransactionIdentifier.
     * A unique identifier for the transaction, this value is not used during processing and will be
     * returned in the response.
     * @return Returns the String
     */
    @JsonGetter("TransactionIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "TransactionIdentifier")
    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Setter for TransactionIdentifier.
     * A unique identifier for the transaction, this value is not used during processing and will be
     * returned in the response.
     * @param transactionIdentifier Value for String
     */
    @JsonSetter("TransactionIdentifier")
    public void setTransactionIdentifier(String transactionIdentifier) {
        this.transactionIdentifier = transactionIdentifier;
    }

    /**
     * Getter for ControlIdentifier.
     * A reference to a control which generated the request, this value is not used during
     * processing and will be returned in the response.
     * @return Returns the String
     */
    @JsonGetter("ControlIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ControlIdentifier")
    public String getControlIdentifier() {
        return controlIdentifier;
    }

    /**
     * Setter for ControlIdentifier.
     * A reference to a control which generated the request, this value is not used during
     * processing and will be returned in the response.
     * @param controlIdentifier Value for String
     */
    @JsonSetter("ControlIdentifier")
    public void setControlIdentifier(String controlIdentifier) {
        this.controlIdentifier = controlIdentifier;
    }

    /**
     * Getter for UserName.
     * The user name to use when processing the transaction.
     * @return Returns the String
     */
    @JsonGetter("UserName")
    @XmlElement(name = "UserName")
    public String getUserName() {
        return userName;
    }

    /**
     * Setter for UserName.
     * The user name to use when processing the transaction.
     * @param userName Value for String
     */
    @JsonSetter("UserName")
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Getter for Carrier.
     * Numeric identifier for the carrier.
     * @return Returns the Integer
     */
    @JsonGetter("Carrier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Carrier")
    public Integer getCarrier() {
        return carrier;
    }

    /**
     * Setter for Carrier.
     * Numeric identifier for the carrier.
     * @param carrier Value for Integer
     */
    @JsonSetter("Carrier")
    public void setCarrier(Integer carrier) {
        this.carrier = carrier;
    }

    /**
     * Getter for Live.
     * Indicates whether the transaction is a test or live. Defaults to system configured value if
     * not submitted.
     * @return Returns the Boolean
     */
    @JsonGetter("Live")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Live")
    public Boolean getLive() {
        return live;
    }

    /**
     * Setter for Live.
     * Indicates whether the transaction is a test or live. Defaults to system configured value if
     * not submitted.
     * @param live Value for Boolean
     */
    @JsonSetter("Live")
    public void setLive(Boolean live) {
        this.live = live;
    }

    /**
     * Getter for Address.
     * Container for an address.
     * @return Returns the Address
     */
    @JsonGetter("Address")
    @XmlElement(name = "Address")
    public Address getAddress() {
        return address;
    }

    /**
     * Setter for Address.
     * Container for an address.
     * @param address Value for Address
     */
    @JsonSetter("Address")
    public void setAddress(Address address) {
        this.address = address;
    }

    /**
     * Getter for PersonalShipping.
     * Container for personal shipping elements.
     * @return Returns the PersonalShipping
     */
    @JsonGetter("PersonalShipping")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PersonalShipping")
    public PersonalShipping getPersonalShipping() {
        return personalShipping;
    }

    /**
     * Setter for PersonalShipping.
     * Container for personal shipping elements.
     * @param personalShipping Value for PersonalShipping
     */
    @JsonSetter("PersonalShipping")
    public void setPersonalShipping(PersonalShipping personalShipping) {
        this.personalShipping = personalShipping;
    }

    /**
     * Getter for Diagnostics.
     * Container for logging and diagnostic override elements.
     * @return Returns the Diagnostics
     */
    @JsonGetter("Diagnostics")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Diagnostics")
    public Diagnostics getDiagnostics() {
        return diagnostics;
    }

    /**
     * Setter for Diagnostics.
     * Container for logging and diagnostic override elements.
     * @param diagnostics Value for Diagnostics
     */
    @JsonSetter("Diagnostics")
    public void setDiagnostics(Diagnostics diagnostics) {
        this.diagnostics = diagnostics;
    }

    /**
     * Getter for Identification.
     * Container for client identification elements.
     * @return Returns the Identification
     */
    @JsonGetter("Identification")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Identification")
    public Identification getIdentification() {
        return identification;
    }

    /**
     * Setter for Identification.
     * Container for client identification elements.
     * @param identification Value for Identification
     */
    @JsonSetter("Identification")
    public void setIdentification(Identification identification) {
        this.identification = identification;
    }

    /**
     * Converts this PierbridgeAddressValidationRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PierbridgeAddressValidationRequest [" + "userName=" + userName + ", address="
                + address + ", transactionIdentifier=" + transactionIdentifier
                + ", controlIdentifier=" + controlIdentifier + ", carrier=" + carrier + ", live="
                + live + ", personalShipping=" + personalShipping + ", diagnostics=" + diagnostics
                + ", identification=" + identification + "]";
    }

    /**
     * Builds a new {@link PierbridgeAddressValidationRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PierbridgeAddressValidationRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(userName, address)
                .transactionIdentifier(getTransactionIdentifier())
                .controlIdentifier(getControlIdentifier())
                .carrier(getCarrier())
                .live(getLive())
                .personalShipping(getPersonalShipping())
                .diagnostics(getDiagnostics())
                .identification(getIdentification());
        return builder;
    }

    /**
     * Class to build instances of {@link PierbridgeAddressValidationRequest}.
     */
    public static class Builder {
        private String userName;
        private Address address;
        private String transactionIdentifier;
        private String controlIdentifier;
        private Integer carrier = 0;
        private Boolean live = false;
        private PersonalShipping personalShipping;
        private Diagnostics diagnostics;
        private Identification identification;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  userName  String value for userName.
         * @param  address  Address value for address.
         */
        public Builder(String userName, Address address) {
            this.userName = userName;
            this.address = address;
        }

        /**
         * Setter for userName.
         * @param  userName  String value for userName.
         * @return Builder
         */
        public Builder userName(String userName) {
            this.userName = userName;
            return this;
        }

        /**
         * Setter for address.
         * @param  address  Address value for address.
         * @return Builder
         */
        public Builder address(Address address) {
            this.address = address;
            return this;
        }

        /**
         * Setter for transactionIdentifier.
         * @param  transactionIdentifier  String value for transactionIdentifier.
         * @return Builder
         */
        public Builder transactionIdentifier(String transactionIdentifier) {
            this.transactionIdentifier = transactionIdentifier;
            return this;
        }

        /**
         * Setter for controlIdentifier.
         * @param  controlIdentifier  String value for controlIdentifier.
         * @return Builder
         */
        public Builder controlIdentifier(String controlIdentifier) {
            this.controlIdentifier = controlIdentifier;
            return this;
        }

        /**
         * Setter for carrier.
         * @param  carrier  Integer value for carrier.
         * @return Builder
         */
        public Builder carrier(Integer carrier) {
            this.carrier = carrier;
            return this;
        }

        /**
         * Setter for live.
         * @param  live  Boolean value for live.
         * @return Builder
         */
        public Builder live(Boolean live) {
            this.live = live;
            return this;
        }

        /**
         * Setter for personalShipping.
         * @param  personalShipping  PersonalShipping value for personalShipping.
         * @return Builder
         */
        public Builder personalShipping(PersonalShipping personalShipping) {
            this.personalShipping = personalShipping;
            return this;
        }

        /**
         * Setter for diagnostics.
         * @param  diagnostics  Diagnostics value for diagnostics.
         * @return Builder
         */
        public Builder diagnostics(Diagnostics diagnostics) {
            this.diagnostics = diagnostics;
            return this;
        }

        /**
         * Setter for identification.
         * @param  identification  Identification value for identification.
         * @return Builder
         */
        public Builder identification(Identification identification) {
            this.identification = identification;
            return this;
        }

        /**
         * Builds a new {@link PierbridgeAddressValidationRequest} object using the set fields.
         * @return {@link PierbridgeAddressValidationRequest}
         */
        public PierbridgeAddressValidationRequest build() {
            return new PierbridgeAddressValidationRequest(userName, address, transactionIdentifier,
                    controlIdentifier, carrier, live, personalShipping, diagnostics,
                    identification);
        }
    }
}
