/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for PierbridgeVoidResponse type.
 */
public class PierbridgeVoidResponse {
    private String transactionIdentifier;
    private String controlIdentifier;
    private Integer carrier;
    private String carrierName;
    private String carrierScac;
    private String pickListNumber;
    private String purchaseOrderNumber;
    private String salesOrderNumber;
    private String accountNumber;
    private Boolean allPackagesVoided;
    private RecordIdentifiers7 recordIdentifiers;
    private Packages13 packages;
    private Status status;
    private Processing processing;

    /**
     * Default constructor.
     */
    public PierbridgeVoidResponse() {
        carrier = 0;
    }

    /**
     * Initialization constructor.
     * @param  status  Status value for status.
     * @param  processing  Processing value for processing.
     * @param  transactionIdentifier  String value for transactionIdentifier.
     * @param  controlIdentifier  String value for controlIdentifier.
     * @param  carrier  Integer value for carrier.
     * @param  carrierName  String value for carrierName.
     * @param  carrierScac  String value for carrierScac.
     * @param  pickListNumber  String value for pickListNumber.
     * @param  purchaseOrderNumber  String value for purchaseOrderNumber.
     * @param  salesOrderNumber  String value for salesOrderNumber.
     * @param  accountNumber  String value for accountNumber.
     * @param  allPackagesVoided  Boolean value for allPackagesVoided.
     * @param  recordIdentifiers  RecordIdentifiers7 value for recordIdentifiers.
     * @param  packages  Packages13 value for packages.
     */
    public PierbridgeVoidResponse(
            Status status,
            Processing processing,
            String transactionIdentifier,
            String controlIdentifier,
            Integer carrier,
            String carrierName,
            String carrierScac,
            String pickListNumber,
            String purchaseOrderNumber,
            String salesOrderNumber,
            String accountNumber,
            Boolean allPackagesVoided,
            RecordIdentifiers7 recordIdentifiers,
            Packages13 packages) {
        this.transactionIdentifier = transactionIdentifier;
        this.controlIdentifier = controlIdentifier;
        this.carrier = carrier;
        this.carrierName = carrierName;
        this.carrierScac = carrierScac;
        this.pickListNumber = pickListNumber;
        this.purchaseOrderNumber = purchaseOrderNumber;
        this.salesOrderNumber = salesOrderNumber;
        this.accountNumber = accountNumber;
        this.allPackagesVoided = allPackagesVoided;
        this.recordIdentifiers = recordIdentifiers;
        this.packages = packages;
        this.status = status;
        this.processing = processing;
    }

    /**
     * Getter for TransactionIdentifier.
     * The unique identifier for the transaction given in the request.
     * @return Returns the String
     */
    @JsonGetter("TransactionIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "TransactionIdentifier")
    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Setter for TransactionIdentifier.
     * The unique identifier for the transaction given in the request.
     * @param transactionIdentifier Value for String
     */
    @JsonSetter("TransactionIdentifier")
    public void setTransactionIdentifier(String transactionIdentifier) {
        this.transactionIdentifier = transactionIdentifier;
    }

    /**
     * Getter for ControlIdentifier.
     * The control reference for the transaction given in the request.
     * @return Returns the String
     */
    @JsonGetter("ControlIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ControlIdentifier")
    public String getControlIdentifier() {
        return controlIdentifier;
    }

    /**
     * Setter for ControlIdentifier.
     * The control reference for the transaction given in the request.
     * @param controlIdentifier Value for String
     */
    @JsonSetter("ControlIdentifier")
    public void setControlIdentifier(String controlIdentifier) {
        this.controlIdentifier = controlIdentifier;
    }

    /**
     * Getter for Carrier.
     * Numeric identifier for the carrier.
     * @return Returns the Integer
     */
    @JsonGetter("Carrier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Carrier")
    public Integer getCarrier() {
        return carrier;
    }

    /**
     * Setter for Carrier.
     * Numeric identifier for the carrier.
     * @param carrier Value for Integer
     */
    @JsonSetter("Carrier")
    public void setCarrier(Integer carrier) {
        this.carrier = carrier;
    }

    /**
     * Getter for CarrierName.
     * The name for the carrier.
     * @return Returns the String
     */
    @JsonGetter("CarrierName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "CarrierName")
    public String getCarrierName() {
        return carrierName;
    }

    /**
     * Setter for CarrierName.
     * The name for the carrier.
     * @param carrierName Value for String
     */
    @JsonSetter("CarrierName")
    public void setCarrierName(String carrierName) {
        this.carrierName = carrierName;
    }

    /**
     * Getter for CarrierScac.
     * The NMFTA (National Motor Freight Traffic Association) Standard Carrier Alpha Code of the
     * carrier.
     * @return Returns the String
     */
    @JsonGetter("CarrierScac")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "CarrierScac")
    public String getCarrierScac() {
        return carrierScac;
    }

    /**
     * Setter for CarrierScac.
     * The NMFTA (National Motor Freight Traffic Association) Standard Carrier Alpha Code of the
     * carrier.
     * @param carrierScac Value for String
     */
    @JsonSetter("CarrierScac")
    public void setCarrierScac(String carrierScac) {
        this.carrierScac = carrierScac;
    }

    /**
     * Getter for PickListNumber.
     * The pick list number, used to identify the pick list.
     * @return Returns the String
     */
    @JsonGetter("PickListNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PickListNumber")
    public String getPickListNumber() {
        return pickListNumber;
    }

    /**
     * Setter for PickListNumber.
     * The pick list number, used to identify the pick list.
     * @param pickListNumber Value for String
     */
    @JsonSetter("PickListNumber")
    public void setPickListNumber(String pickListNumber) {
        this.pickListNumber = pickListNumber;
    }

    /**
     * Getter for PurchaseOrderNumber.
     * Purchase order number associated with the transaction.
     * @return Returns the String
     */
    @JsonGetter("PurchaseOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PurchaseOrderNumber")
    public String getPurchaseOrderNumber() {
        return purchaseOrderNumber;
    }

    /**
     * Setter for PurchaseOrderNumber.
     * Purchase order number associated with the transaction.
     * @param purchaseOrderNumber Value for String
     */
    @JsonSetter("PurchaseOrderNumber")
    public void setPurchaseOrderNumber(String purchaseOrderNumber) {
        this.purchaseOrderNumber = purchaseOrderNumber;
    }

    /**
     * Getter for SalesOrderNumber.
     * Sales order number associated with the transaction.
     * @return Returns the String
     */
    @JsonGetter("SalesOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "SalesOrderNumber")
    public String getSalesOrderNumber() {
        return salesOrderNumber;
    }

    /**
     * Setter for SalesOrderNumber.
     * Sales order number associated with the transaction.
     * @param salesOrderNumber Value for String
     */
    @JsonSetter("SalesOrderNumber")
    public void setSalesOrderNumber(String salesOrderNumber) {
        this.salesOrderNumber = salesOrderNumber;
    }

    /**
     * Getter for AccountNumber.
     * Number of the account used during the void.
     * @return Returns the String
     */
    @JsonGetter("AccountNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "AccountNumber")
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Setter for AccountNumber.
     * Number of the account used during the void.
     * @param accountNumber Value for String
     */
    @JsonSetter("AccountNumber")
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Getter for AllPackagesVoided.
     * Indicates if all the packages in a shipment were voided.
     * @return Returns the Boolean
     */
    @JsonGetter("AllPackagesVoided")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "AllPackagesVoided")
    public Boolean getAllPackagesVoided() {
        return allPackagesVoided;
    }

    /**
     * Setter for AllPackagesVoided.
     * Indicates if all the packages in a shipment were voided.
     * @param allPackagesVoided Value for Boolean
     */
    @JsonSetter("AllPackagesVoided")
    public void setAllPackagesVoided(Boolean allPackagesVoided) {
        this.allPackagesVoided = allPackagesVoided;
    }

    /**
     * Getter for RecordIdentifiers.
     * Outer container for transaction identifiers.
     * @return Returns the RecordIdentifiers7
     */
    @JsonGetter("RecordIdentifiers")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "RecordIdentifiers")
    public RecordIdentifiers7 getRecordIdentifiers() {
        return recordIdentifiers;
    }

    /**
     * Setter for RecordIdentifiers.
     * Outer container for transaction identifiers.
     * @param recordIdentifiers Value for RecordIdentifiers7
     */
    @JsonSetter("RecordIdentifiers")
    public void setRecordIdentifiers(RecordIdentifiers7 recordIdentifiers) {
        this.recordIdentifiers = recordIdentifiers;
    }

    /**
     * Getter for Packages.
     * Container for all packages associated with the transaction.
     * @return Returns the Packages13
     */
    @JsonGetter("Packages")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Packages")
    public Packages13 getPackages() {
        return packages;
    }

    /**
     * Setter for Packages.
     * Container for all packages associated with the transaction.
     * @param packages Value for Packages13
     */
    @JsonSetter("Packages")
    public void setPackages(Packages13 packages) {
        this.packages = packages;
    }

    /**
     * Getter for Status.
     * Container for transaction errors and warning elements.
     * @return Returns the Status
     */
    @JsonGetter("Status")
    @XmlElement(name = "Status")
    public Status getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Container for transaction errors and warning elements.
     * @param status Value for Status
     */
    @JsonSetter("Status")
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * Getter for Processing.
     * Container element for transaction processing statistics.
     * @return Returns the Processing
     */
    @JsonGetter("Processing")
    @XmlElement(name = "Processing")
    public Processing getProcessing() {
        return processing;
    }

    /**
     * Setter for Processing.
     * Container element for transaction processing statistics.
     * @param processing Value for Processing
     */
    @JsonSetter("Processing")
    public void setProcessing(Processing processing) {
        this.processing = processing;
    }

    /**
     * Converts this PierbridgeVoidResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PierbridgeVoidResponse [" + "status=" + status + ", processing=" + processing
                + ", transactionIdentifier=" + transactionIdentifier + ", controlIdentifier="
                + controlIdentifier + ", carrier=" + carrier + ", carrierName=" + carrierName
                + ", carrierScac=" + carrierScac + ", pickListNumber=" + pickListNumber
                + ", purchaseOrderNumber=" + purchaseOrderNumber + ", salesOrderNumber="
                + salesOrderNumber + ", accountNumber=" + accountNumber + ", allPackagesVoided="
                + allPackagesVoided + ", recordIdentifiers=" + recordIdentifiers + ", packages="
                + packages + "]";
    }

    /**
     * Builds a new {@link PierbridgeVoidResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PierbridgeVoidResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status, processing)
                .transactionIdentifier(getTransactionIdentifier())
                .controlIdentifier(getControlIdentifier())
                .carrier(getCarrier())
                .carrierName(getCarrierName())
                .carrierScac(getCarrierScac())
                .pickListNumber(getPickListNumber())
                .purchaseOrderNumber(getPurchaseOrderNumber())
                .salesOrderNumber(getSalesOrderNumber())
                .accountNumber(getAccountNumber())
                .allPackagesVoided(getAllPackagesVoided())
                .recordIdentifiers(getRecordIdentifiers())
                .packages(getPackages());
        return builder;
    }

    /**
     * Class to build instances of {@link PierbridgeVoidResponse}.
     */
    public static class Builder {
        private Status status;
        private Processing processing;
        private String transactionIdentifier;
        private String controlIdentifier;
        private Integer carrier = 0;
        private String carrierName;
        private String carrierScac;
        private String pickListNumber;
        private String purchaseOrderNumber;
        private String salesOrderNumber;
        private String accountNumber;
        private Boolean allPackagesVoided;
        private RecordIdentifiers7 recordIdentifiers;
        private Packages13 packages;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  Status value for status.
         * @param  processing  Processing value for processing.
         */
        public Builder(Status status, Processing processing) {
            this.status = status;
            this.processing = processing;
        }

        /**
         * Setter for status.
         * @param  status  Status value for status.
         * @return Builder
         */
        public Builder status(Status status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for processing.
         * @param  processing  Processing value for processing.
         * @return Builder
         */
        public Builder processing(Processing processing) {
            this.processing = processing;
            return this;
        }

        /**
         * Setter for transactionIdentifier.
         * @param  transactionIdentifier  String value for transactionIdentifier.
         * @return Builder
         */
        public Builder transactionIdentifier(String transactionIdentifier) {
            this.transactionIdentifier = transactionIdentifier;
            return this;
        }

        /**
         * Setter for controlIdentifier.
         * @param  controlIdentifier  String value for controlIdentifier.
         * @return Builder
         */
        public Builder controlIdentifier(String controlIdentifier) {
            this.controlIdentifier = controlIdentifier;
            return this;
        }

        /**
         * Setter for carrier.
         * @param  carrier  Integer value for carrier.
         * @return Builder
         */
        public Builder carrier(Integer carrier) {
            this.carrier = carrier;
            return this;
        }

        /**
         * Setter for carrierName.
         * @param  carrierName  String value for carrierName.
         * @return Builder
         */
        public Builder carrierName(String carrierName) {
            this.carrierName = carrierName;
            return this;
        }

        /**
         * Setter for carrierScac.
         * @param  carrierScac  String value for carrierScac.
         * @return Builder
         */
        public Builder carrierScac(String carrierScac) {
            this.carrierScac = carrierScac;
            return this;
        }

        /**
         * Setter for pickListNumber.
         * @param  pickListNumber  String value for pickListNumber.
         * @return Builder
         */
        public Builder pickListNumber(String pickListNumber) {
            this.pickListNumber = pickListNumber;
            return this;
        }

        /**
         * Setter for purchaseOrderNumber.
         * @param  purchaseOrderNumber  String value for purchaseOrderNumber.
         * @return Builder
         */
        public Builder purchaseOrderNumber(String purchaseOrderNumber) {
            this.purchaseOrderNumber = purchaseOrderNumber;
            return this;
        }

        /**
         * Setter for salesOrderNumber.
         * @param  salesOrderNumber  String value for salesOrderNumber.
         * @return Builder
         */
        public Builder salesOrderNumber(String salesOrderNumber) {
            this.salesOrderNumber = salesOrderNumber;
            return this;
        }

        /**
         * Setter for accountNumber.
         * @param  accountNumber  String value for accountNumber.
         * @return Builder
         */
        public Builder accountNumber(String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        /**
         * Setter for allPackagesVoided.
         * @param  allPackagesVoided  Boolean value for allPackagesVoided.
         * @return Builder
         */
        public Builder allPackagesVoided(Boolean allPackagesVoided) {
            this.allPackagesVoided = allPackagesVoided;
            return this;
        }

        /**
         * Setter for recordIdentifiers.
         * @param  recordIdentifiers  RecordIdentifiers7 value for recordIdentifiers.
         * @return Builder
         */
        public Builder recordIdentifiers(RecordIdentifiers7 recordIdentifiers) {
            this.recordIdentifiers = recordIdentifiers;
            return this;
        }

        /**
         * Setter for packages.
         * @param  packages  Packages13 value for packages.
         * @return Builder
         */
        public Builder packages(Packages13 packages) {
            this.packages = packages;
            return this;
        }

        /**
         * Builds a new {@link PierbridgeVoidResponse} object using the set fields.
         * @return {@link PierbridgeVoidResponse}
         */
        public PierbridgeVoidResponse build() {
            return new PierbridgeVoidResponse(status, processing, transactionIdentifier,
                    controlIdentifier, carrier, carrierName, carrierScac, pickListNumber,
                    purchaseOrderNumber, salesOrderNumber, accountNumber, allPackagesVoided,
                    recordIdentifiers, packages);
        }
    }
}
