/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Rate2 type.
 */
public class Rate2 {
    private String rateType;
    private String totalAccessorialCharges;
    private String totalShippingCharges;
    private String totalCharges;

    /**
     * Default constructor.
     */
    public Rate2() {
    }

    /**
     * Initialization constructor.
     * @param  rateType  String value for rateType.
     * @param  totalAccessorialCharges  String value for totalAccessorialCharges.
     * @param  totalShippingCharges  String value for totalShippingCharges.
     * @param  totalCharges  String value for totalCharges.
     */
    public Rate2(
            String rateType,
            String totalAccessorialCharges,
            String totalShippingCharges,
            String totalCharges) {
        this.rateType = rateType;
        this.totalAccessorialCharges = totalAccessorialCharges;
        this.totalShippingCharges = totalShippingCharges;
        this.totalCharges = totalCharges;
    }

    /**
     * Getter for RateType.
     * An identifier for the type of rate.
     * @return Returns the String
     */
    @JsonGetter("RateType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "RateType")
    public String getRateType() {
        return rateType;
    }

    /**
     * Setter for RateType.
     * An identifier for the type of rate.
     * @param rateType Value for String
     */
    @JsonSetter("RateType")
    public void setRateType(String rateType) {
        this.rateType = rateType;
    }

    /**
     * Getter for TotalAccessorialCharges.
     * Total accessorial charge at package level for the rate type.
     * @return Returns the String
     */
    @JsonGetter("TotalAccessorialCharges")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "TotalAccessorialCharges")
    public String getTotalAccessorialCharges() {
        return totalAccessorialCharges;
    }

    /**
     * Setter for TotalAccessorialCharges.
     * Total accessorial charge at package level for the rate type.
     * @param totalAccessorialCharges Value for String
     */
    @JsonSetter("TotalAccessorialCharges")
    public void setTotalAccessorialCharges(String totalAccessorialCharges) {
        this.totalAccessorialCharges = totalAccessorialCharges;
    }

    /**
     * Getter for TotalShippingCharges.
     * Total shipping charge at package level for the rate type.
     * @return Returns the String
     */
    @JsonGetter("TotalShippingCharges")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "TotalShippingCharges")
    public String getTotalShippingCharges() {
        return totalShippingCharges;
    }

    /**
     * Setter for TotalShippingCharges.
     * Total shipping charge at package level for the rate type.
     * @param totalShippingCharges Value for String
     */
    @JsonSetter("TotalShippingCharges")
    public void setTotalShippingCharges(String totalShippingCharges) {
        this.totalShippingCharges = totalShippingCharges;
    }

    /**
     * Getter for TotalCharges.
     * Total charge at package level for the rate type.
     * @return Returns the String
     */
    @JsonGetter("TotalCharges")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "TotalCharges")
    public String getTotalCharges() {
        return totalCharges;
    }

    /**
     * Setter for TotalCharges.
     * Total charge at package level for the rate type.
     * @param totalCharges Value for String
     */
    @JsonSetter("TotalCharges")
    public void setTotalCharges(String totalCharges) {
        this.totalCharges = totalCharges;
    }

    /**
     * Converts this Rate2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Rate2 [" + "rateType=" + rateType + ", totalAccessorialCharges="
                + totalAccessorialCharges + ", totalShippingCharges=" + totalShippingCharges
                + ", totalCharges=" + totalCharges + "]";
    }

    /**
     * Builds a new {@link Rate2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Rate2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .rateType(getRateType())
                .totalAccessorialCharges(getTotalAccessorialCharges())
                .totalShippingCharges(getTotalShippingCharges())
                .totalCharges(getTotalCharges());
        return builder;
    }

    /**
     * Class to build instances of {@link Rate2}.
     */
    public static class Builder {
        private String rateType;
        private String totalAccessorialCharges;
        private String totalShippingCharges;
        private String totalCharges;



        /**
         * Setter for rateType.
         * @param  rateType  String value for rateType.
         * @return Builder
         */
        public Builder rateType(String rateType) {
            this.rateType = rateType;
            return this;
        }

        /**
         * Setter for totalAccessorialCharges.
         * @param  totalAccessorialCharges  String value for totalAccessorialCharges.
         * @return Builder
         */
        public Builder totalAccessorialCharges(String totalAccessorialCharges) {
            this.totalAccessorialCharges = totalAccessorialCharges;
            return this;
        }

        /**
         * Setter for totalShippingCharges.
         * @param  totalShippingCharges  String value for totalShippingCharges.
         * @return Builder
         */
        public Builder totalShippingCharges(String totalShippingCharges) {
            this.totalShippingCharges = totalShippingCharges;
            return this;
        }

        /**
         * Setter for totalCharges.
         * @param  totalCharges  String value for totalCharges.
         * @return Builder
         */
        public Builder totalCharges(String totalCharges) {
            this.totalCharges = totalCharges;
            return this;
        }

        /**
         * Builds a new {@link Rate2} object using the set fields.
         * @return {@link Rate2}
         */
        public Rate2 build() {
            return new Rate2(rateType, totalAccessorialCharges, totalShippingCharges, totalCharges);
        }
    }
}
