/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Rate4 type.
 */
public class Rate4 {
    private Integer rateType;
    private String rateDescription;
    private Double rateWeight;
    private String quoteID;
    private String optionID;
    private String shipDate;
    private String deliveryDate;
    private Boolean displayRate;
    private Boolean updateRate;
    private ChargeGroups2 chargeGroups;

    /**
     * Default constructor.
     */
    public Rate4() {
        rateType = 0;
        rateWeight = 0d;
        displayRate = false;
        updateRate = false;
    }

    /**
     * Initialization constructor.
     * @param  rateType  Integer value for rateType.
     * @param  rateDescription  String value for rateDescription.
     * @param  rateWeight  Double value for rateWeight.
     * @param  quoteID  String value for quoteID.
     * @param  optionID  String value for optionID.
     * @param  shipDate  String value for shipDate.
     * @param  deliveryDate  String value for deliveryDate.
     * @param  displayRate  Boolean value for displayRate.
     * @param  updateRate  Boolean value for updateRate.
     * @param  chargeGroups  ChargeGroups2 value for chargeGroups.
     */
    public Rate4(
            Integer rateType,
            String rateDescription,
            Double rateWeight,
            String quoteID,
            String optionID,
            String shipDate,
            String deliveryDate,
            Boolean displayRate,
            Boolean updateRate,
            ChargeGroups2 chargeGroups) {
        this.rateType = rateType;
        this.rateDescription = rateDescription;
        this.rateWeight = rateWeight;
        this.quoteID = quoteID;
        this.optionID = optionID;
        this.shipDate = shipDate;
        this.deliveryDate = deliveryDate;
        this.displayRate = displayRate;
        this.updateRate = updateRate;
        this.chargeGroups = chargeGroups;
    }

    /**
     * Getter for RateType.
     * Numeric identifier for the rate type.
     * @return Returns the Integer
     */
    @JsonGetter("RateType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "RateType")
    public Integer getRateType() {
        return rateType;
    }

    /**
     * Setter for RateType.
     * Numeric identifier for the rate type.
     * @param rateType Value for Integer
     */
    @JsonSetter("RateType")
    public void setRateType(Integer rateType) {
        this.rateType = rateType;
    }

    /**
     * Getter for RateDescription.
     * Free form description for the rate type.
     * @return Returns the String
     */
    @JsonGetter("RateDescription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "RateDescription")
    public String getRateDescription() {
        return rateDescription;
    }

    /**
     * Setter for RateDescription.
     * Free form description for the rate type.
     * @param rateDescription Value for String
     */
    @JsonSetter("RateDescription")
    public void setRateDescription(String rateDescription) {
        this.rateDescription = rateDescription;
    }

    /**
     * Getter for RateWeight.
     * The rated weight for the package.
     * @return Returns the Double
     */
    @JsonGetter("RateWeight")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "RateWeight")
    public Double getRateWeight() {
        return rateWeight;
    }

    /**
     * Setter for RateWeight.
     * The rated weight for the package.
     * @param rateWeight Value for Double
     */
    @JsonSetter("RateWeight")
    public void setRateWeight(Double rateWeight) {
        this.rateWeight = rateWeight;
    }

    /**
     * Getter for QuoteID.
     * The unique quote identifier for freight based transactions.
     * @return Returns the String
     */
    @JsonGetter("QuoteID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "QuoteID")
    public String getQuoteID() {
        return quoteID;
    }

    /**
     * Setter for QuoteID.
     * The unique quote identifier for freight based transactions.
     * @param quoteID Value for String
     */
    @JsonSetter("QuoteID")
    public void setQuoteID(String quoteID) {
        this.quoteID = quoteID;
    }

    /**
     * Getter for OptionID.
     * The unique option identifier for freight based transactions.
     * @return Returns the String
     */
    @JsonGetter("OptionID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OptionID")
    public String getOptionID() {
        return optionID;
    }

    /**
     * Setter for OptionID.
     * The unique option identifier for freight based transactions.
     * @param optionID Value for String
     */
    @JsonSetter("OptionID")
    public void setOptionID(String optionID) {
        this.optionID = optionID;
    }

    /**
     * Getter for ShipDate.
     * Date the items are to be shipped. Defaults to current date if not submitted.
     * @return Returns the String
     */
    @JsonGetter("ShipDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ShipDate")
    public String getShipDate() {
        return shipDate;
    }

    /**
     * Setter for ShipDate.
     * Date the items are to be shipped. Defaults to current date if not submitted.
     * @param shipDate Value for String
     */
    @JsonSetter("ShipDate")
    public void setShipDate(String shipDate) {
        this.shipDate = shipDate;
    }

    /**
     * Getter for DeliveryDate.
     * The requested delivery date for the shipment.
     * @return Returns the String
     */
    @JsonGetter("DeliveryDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "DeliveryDate")
    public String getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Setter for DeliveryDate.
     * The requested delivery date for the shipment.
     * @param deliveryDate Value for String
     */
    @JsonSetter("DeliveryDate")
    public void setDeliveryDate(String deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * Getter for DisplayRate.
     * Indicates if the rate is marked for display to the user.
     * @return Returns the Boolean
     */
    @JsonGetter("DisplayRate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "DisplayRate")
    public Boolean getDisplayRate() {
        return displayRate;
    }

    /**
     * Setter for DisplayRate.
     * Indicates if the rate is marked for display to the user.
     * @param displayRate Value for Boolean
     */
    @JsonSetter("DisplayRate")
    public void setDisplayRate(Boolean displayRate) {
        this.displayRate = displayRate;
    }

    /**
     * Getter for UpdateRate.
     * Indicates if the rate is used during updates back to customer host systems.
     * @return Returns the Boolean
     */
    @JsonGetter("UpdateRate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "UpdateRate")
    public Boolean getUpdateRate() {
        return updateRate;
    }

    /**
     * Setter for UpdateRate.
     * Indicates if the rate is used during updates back to customer host systems.
     * @param updateRate Value for Boolean
     */
    @JsonSetter("UpdateRate")
    public void setUpdateRate(Boolean updateRate) {
        this.updateRate = updateRate;
    }

    /**
     * Getter for ChargeGroups.
     * Container for all charge groups associated with the transaction.
     * @return Returns the ChargeGroups2
     */
    @JsonGetter("ChargeGroups")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ChargeGroups")
    public ChargeGroups2 getChargeGroups() {
        return chargeGroups;
    }

    /**
     * Setter for ChargeGroups.
     * Container for all charge groups associated with the transaction.
     * @param chargeGroups Value for ChargeGroups2
     */
    @JsonSetter("ChargeGroups")
    public void setChargeGroups(ChargeGroups2 chargeGroups) {
        this.chargeGroups = chargeGroups;
    }

    /**
     * Converts this Rate4 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Rate4 [" + "rateType=" + rateType + ", rateDescription=" + rateDescription
                + ", rateWeight=" + rateWeight + ", quoteID=" + quoteID + ", optionID=" + optionID
                + ", shipDate=" + shipDate + ", deliveryDate=" + deliveryDate + ", displayRate="
                + displayRate + ", updateRate=" + updateRate + ", chargeGroups=" + chargeGroups
                + "]";
    }

    /**
     * Builds a new {@link Rate4.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Rate4.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .rateType(getRateType())
                .rateDescription(getRateDescription())
                .rateWeight(getRateWeight())
                .quoteID(getQuoteID())
                .optionID(getOptionID())
                .shipDate(getShipDate())
                .deliveryDate(getDeliveryDate())
                .displayRate(getDisplayRate())
                .updateRate(getUpdateRate())
                .chargeGroups(getChargeGroups());
        return builder;
    }

    /**
     * Class to build instances of {@link Rate4}.
     */
    public static class Builder {
        private Integer rateType = 0;
        private String rateDescription;
        private Double rateWeight = 0d;
        private String quoteID;
        private String optionID;
        private String shipDate;
        private String deliveryDate;
        private Boolean displayRate = false;
        private Boolean updateRate = false;
        private ChargeGroups2 chargeGroups;



        /**
         * Setter for rateType.
         * @param  rateType  Integer value for rateType.
         * @return Builder
         */
        public Builder rateType(Integer rateType) {
            this.rateType = rateType;
            return this;
        }

        /**
         * Setter for rateDescription.
         * @param  rateDescription  String value for rateDescription.
         * @return Builder
         */
        public Builder rateDescription(String rateDescription) {
            this.rateDescription = rateDescription;
            return this;
        }

        /**
         * Setter for rateWeight.
         * @param  rateWeight  Double value for rateWeight.
         * @return Builder
         */
        public Builder rateWeight(Double rateWeight) {
            this.rateWeight = rateWeight;
            return this;
        }

        /**
         * Setter for quoteID.
         * @param  quoteID  String value for quoteID.
         * @return Builder
         */
        public Builder quoteID(String quoteID) {
            this.quoteID = quoteID;
            return this;
        }

        /**
         * Setter for optionID.
         * @param  optionID  String value for optionID.
         * @return Builder
         */
        public Builder optionID(String optionID) {
            this.optionID = optionID;
            return this;
        }

        /**
         * Setter for shipDate.
         * @param  shipDate  String value for shipDate.
         * @return Builder
         */
        public Builder shipDate(String shipDate) {
            this.shipDate = shipDate;
            return this;
        }

        /**
         * Setter for deliveryDate.
         * @param  deliveryDate  String value for deliveryDate.
         * @return Builder
         */
        public Builder deliveryDate(String deliveryDate) {
            this.deliveryDate = deliveryDate;
            return this;
        }

        /**
         * Setter for displayRate.
         * @param  displayRate  Boolean value for displayRate.
         * @return Builder
         */
        public Builder displayRate(Boolean displayRate) {
            this.displayRate = displayRate;
            return this;
        }

        /**
         * Setter for updateRate.
         * @param  updateRate  Boolean value for updateRate.
         * @return Builder
         */
        public Builder updateRate(Boolean updateRate) {
            this.updateRate = updateRate;
            return this;
        }

        /**
         * Setter for chargeGroups.
         * @param  chargeGroups  ChargeGroups2 value for chargeGroups.
         * @return Builder
         */
        public Builder chargeGroups(ChargeGroups2 chargeGroups) {
            this.chargeGroups = chargeGroups;
            return this;
        }

        /**
         * Builds a new {@link Rate4} object using the set fields.
         * @return {@link Rate4}
         */
        public Rate4 build() {
            return new Rate4(rateType, rateDescription, rateWeight, quoteID, optionID, shipDate,
                    deliveryDate, displayRate, updateRate, chargeGroups);
        }
    }
}
