/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Receiver4 type.
 */
public class Receiver4 {
    private String accountNumber;
    private String companyName;
    private String street;
    private String locale;
    private String other;
    private String city;
    private String region;
    private String postalCode;
    private String country;
    private Boolean residential;
    private Boolean modified;
    private String externalReceiverID;
    private String departmentName;
    private String iDNumber;
    private OptionalNullable<IDTypeEnum> iDType;
    private String taxNumber;
    private OptionalNullable<TaxTypeEnum> taxType;

    /**
     * Default constructor.
     */
    public Receiver4() {
        residential = false;
        modified = false;
    }

    /**
     * Initialization constructor.
     * @param  street  String value for street.
     * @param  city  String value for city.
     * @param  region  String value for region.
     * @param  postalCode  String value for postalCode.
     * @param  country  String value for country.
     * @param  accountNumber  String value for accountNumber.
     * @param  companyName  String value for companyName.
     * @param  locale  String value for locale.
     * @param  other  String value for other.
     * @param  residential  Boolean value for residential.
     * @param  modified  Boolean value for modified.
     * @param  externalReceiverID  String value for externalReceiverID.
     * @param  departmentName  String value for departmentName.
     * @param  iDNumber  String value for iDNumber.
     * @param  iDType  IDTypeEnum value for iDType.
     * @param  taxNumber  String value for taxNumber.
     * @param  taxType  TaxTypeEnum value for taxType.
     */
    public Receiver4(
            String street,
            String city,
            String region,
            String postalCode,
            String country,
            String accountNumber,
            String companyName,
            String locale,
            String other,
            Boolean residential,
            Boolean modified,
            String externalReceiverID,
            String departmentName,
            String iDNumber,
            IDTypeEnum iDType,
            String taxNumber,
            TaxTypeEnum taxType) {
        this.accountNumber = accountNumber;
        this.companyName = companyName;
        this.street = street;
        this.locale = locale;
        this.other = other;
        this.city = city;
        this.region = region;
        this.postalCode = postalCode;
        this.country = country;
        this.residential = residential;
        this.modified = modified;
        this.externalReceiverID = externalReceiverID;
        this.departmentName = departmentName;
        this.iDNumber = iDNumber;
        this.iDType = OptionalNullable.of(iDType);
        this.taxNumber = taxNumber;
        this.taxType = OptionalNullable.of(taxType);
    }

    /**
     * Initialization constructor.
     * @param  street  String value for street.
     * @param  city  String value for city.
     * @param  region  String value for region.
     * @param  postalCode  String value for postalCode.
     * @param  country  String value for country.
     * @param  accountNumber  String value for accountNumber.
     * @param  companyName  String value for companyName.
     * @param  locale  String value for locale.
     * @param  other  String value for other.
     * @param  residential  Boolean value for residential.
     * @param  modified  Boolean value for modified.
     * @param  externalReceiverID  String value for externalReceiverID.
     * @param  departmentName  String value for departmentName.
     * @param  iDNumber  String value for iDNumber.
     * @param  iDType  IDTypeEnum value for iDType.
     * @param  taxNumber  String value for taxNumber.
     * @param  taxType  TaxTypeEnum value for taxType.
     */

    protected Receiver4(String street, String city, String region, String postalCode,
            String country, String accountNumber, String companyName, String locale, String other,
            Boolean residential, Boolean modified, String externalReceiverID, String departmentName,
            String iDNumber, OptionalNullable<IDTypeEnum> iDType, String taxNumber,
            OptionalNullable<TaxTypeEnum> taxType) {
        this.accountNumber = accountNumber;
        this.companyName = companyName;
        this.street = street;
        this.locale = locale;
        this.other = other;
        this.city = city;
        this.region = region;
        this.postalCode = postalCode;
        this.country = country;
        this.residential = residential;
        this.modified = modified;
        this.externalReceiverID = externalReceiverID;
        this.departmentName = departmentName;
        this.iDNumber = iDNumber;
        this.iDType = iDType;
        this.taxNumber = taxNumber;
        this.taxType = taxType;
    }

    /**
     * Getter for AccountNumber.
     * The receivers account number.
     * @return Returns the String
     */
    @JsonGetter("AccountNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "AccountNumber")
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Setter for AccountNumber.
     * The receivers account number.
     * @param accountNumber Value for String
     */
    @JsonSetter("AccountNumber")
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Getter for CompanyName.
     * The company name associated with the address.
     * @return Returns the String
     */
    @JsonGetter("CompanyName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "CompanyName")
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Setter for CompanyName.
     * The company name associated with the address.
     * @param companyName Value for String
     */
    @JsonSetter("CompanyName")
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * Getter for Street.
     * First line of the address.
     * @return Returns the String
     */
    @JsonGetter("Street")
    @XmlElement(name = "Street")
    public String getStreet() {
        return street;
    }

    /**
     * Setter for Street.
     * First line of the address.
     * @param street Value for String
     */
    @JsonSetter("Street")
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * Getter for Locale.
     * Second line of the address.
     * @return Returns the String
     */
    @JsonGetter("Locale")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Locale")
    public String getLocale() {
        return locale;
    }

    /**
     * Setter for Locale.
     * Second line of the address.
     * @param locale Value for String
     */
    @JsonSetter("Locale")
    public void setLocale(String locale) {
        this.locale = locale;
    }

    /**
     * Getter for Other.
     * Third line of the address.
     * @return Returns the String
     */
    @JsonGetter("Other")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Other")
    public String getOther() {
        return other;
    }

    /**
     * Setter for Other.
     * Third line of the address.
     * @param other Value for String
     */
    @JsonSetter("Other")
    public void setOther(String other) {
        this.other = other;
    }

    /**
     * Getter for City.
     * City of the address.
     * @return Returns the String
     */
    @JsonGetter("City")
    @XmlElement(name = "City")
    public String getCity() {
        return city;
    }

    /**
     * Setter for City.
     * City of the address.
     * @param city Value for String
     */
    @JsonSetter("City")
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for Region.
     * The state or region of the address.
     * @return Returns the String
     */
    @JsonGetter("Region")
    @XmlElement(name = "Region")
    public String getRegion() {
        return region;
    }

    /**
     * Setter for Region.
     * The state or region of the address.
     * @param region Value for String
     */
    @JsonSetter("Region")
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * Getter for PostalCode.
     * The postal code or zip associated with the address.
     * @return Returns the String
     */
    @JsonGetter("PostalCode")
    @XmlElement(name = "PostalCode")
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Setter for PostalCode.
     * The postal code or zip associated with the address.
     * @param postalCode Value for String
     */
    @JsonSetter("PostalCode")
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * Getter for Country.
     * The country code for the address.
     * @return Returns the String
     */
    @JsonGetter("Country")
    @XmlElement(name = "Country")
    public String getCountry() {
        return country;
    }

    /**
     * Setter for Country.
     * The country code for the address.
     * @param country Value for String
     */
    @JsonSetter("Country")
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for Residential.
     * Indicates whether the address is residential or commercial.
     * @return Returns the Boolean
     */
    @JsonGetter("Residential")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Residential")
    public Boolean getResidential() {
        return residential;
    }

    /**
     * Setter for Residential.
     * Indicates whether the address is residential or commercial.
     * @param residential Value for Boolean
     */
    @JsonSetter("Residential")
    public void setResidential(Boolean residential) {
        this.residential = residential;
    }

    /**
     * Getter for Modified.
     * Indicates whether the address to be shipped to has been modified. Defaults to not modified if
     * not submitted.
     * @return Returns the Boolean
     */
    @JsonGetter("Modified")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Modified")
    public Boolean getModified() {
        return modified;
    }

    /**
     * Setter for Modified.
     * Indicates whether the address to be shipped to has been modified. Defaults to not modified if
     * not submitted.
     * @param modified Value for Boolean
     */
    @JsonSetter("Modified")
    public void setModified(Boolean modified) {
        this.modified = modified;
    }

    /**
     * Getter for ExternalReceiverID.
     * Identifier value used to identify the receiver in an external system.
     * @return Returns the String
     */
    @JsonGetter("ExternalReceiverID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ExternalReceiverID")
    public String getExternalReceiverID() {
        return externalReceiverID;
    }

    /**
     * Setter for ExternalReceiverID.
     * Identifier value used to identify the receiver in an external system.
     * @param externalReceiverID Value for String
     */
    @JsonSetter("ExternalReceiverID")
    public void setExternalReceiverID(String externalReceiverID) {
        this.externalReceiverID = externalReceiverID;
    }

    /**
     * Getter for DepartmentName.
     * Name of the department that the shipment is to be delivered to. Only used for special
     * 'In-building' deliveries.
     * @return Returns the String
     */
    @JsonGetter("DepartmentName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "DepartmentName")
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * Setter for DepartmentName.
     * Name of the department that the shipment is to be delivered to. Only used for special
     * 'In-building' deliveries.
     * @param departmentName Value for String
     */
    @JsonSetter("DepartmentName")
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    /**
     * Getter for IDNumber.
     * Identification number of receiver.
     * @return Returns the String
     */
    @JsonGetter("IDNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "IDNumber")
    public String getIDNumber() {
        return iDNumber;
    }

    /**
     * Setter for IDNumber.
     * Identification number of receiver.
     * @param iDNumber Value for String
     */
    @JsonSetter("IDNumber")
    public void setIDNumber(String iDNumber) {
        this.iDNumber = iDNumber;
    }

    /**
     * Internal Getter for IDType.
     * ID Number Type
     * @return Returns the Internal IDTypeEnum
     */
    @JsonGetter("IDType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<IDTypeEnum> internalGetIDType() {
        return this.iDType;
    }

    /**
     * Getter for IDType.
     * ID Number Type
     * @return Returns the IDTypeEnum
     */
    @XmlElement(name = "IDType")
    public IDTypeEnum getIDType() {
        return OptionalNullable.getFrom(iDType);
    }

    /**
     * Setter for IDType.
     * ID Number Type
     * @param iDType Value for IDTypeEnum
     */
    @JsonSetter("IDType")
    public void setIDType(IDTypeEnum iDType) {
        this.iDType = OptionalNullable.of(iDType);
    }

    /**
     * UnSetter for IDType.
     * ID Number Type
     */
    public void unsetIDType() {
        iDType = null;
    }

    /**
     * Getter for TaxNumber.
     * Tax identification number of receiver.
     * @return Returns the String
     */
    @JsonGetter("TaxNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "TaxNumber")
    public String getTaxNumber() {
        return taxNumber;
    }

    /**
     * Setter for TaxNumber.
     * Tax identification number of receiver.
     * @param taxNumber Value for String
     */
    @JsonSetter("TaxNumber")
    public void setTaxNumber(String taxNumber) {
        this.taxNumber = taxNumber;
    }

    /**
     * Internal Getter for TaxType.
     * Tax Number Type
     * @return Returns the Internal TaxTypeEnum
     */
    @JsonGetter("TaxType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<TaxTypeEnum> internalGetTaxType() {
        return this.taxType;
    }

    /**
     * Getter for TaxType.
     * Tax Number Type
     * @return Returns the TaxTypeEnum
     */
    @XmlElement(name = "TaxType")
    public TaxTypeEnum getTaxType() {
        return OptionalNullable.getFrom(taxType);
    }

    /**
     * Setter for TaxType.
     * Tax Number Type
     * @param taxType Value for TaxTypeEnum
     */
    @JsonSetter("TaxType")
    public void setTaxType(TaxTypeEnum taxType) {
        this.taxType = OptionalNullable.of(taxType);
    }

    /**
     * UnSetter for TaxType.
     * Tax Number Type
     */
    public void unsetTaxType() {
        taxType = null;
    }

    /**
     * Converts this Receiver4 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Receiver4 [" + "street=" + street + ", city=" + city + ", region=" + region
                + ", postalCode=" + postalCode + ", country=" + country + ", accountNumber="
                + accountNumber + ", companyName=" + companyName + ", locale=" + locale + ", other="
                + other + ", residential=" + residential + ", modified=" + modified
                + ", externalReceiverID=" + externalReceiverID + ", departmentName="
                + departmentName + ", iDNumber=" + iDNumber + ", iDType=" + iDType + ", taxNumber="
                + taxNumber + ", taxType=" + taxType + "]";
    }

    /**
     * Builds a new {@link Receiver4.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Receiver4.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(street, city, region, postalCode, country)
                .accountNumber(getAccountNumber())
                .companyName(getCompanyName())
                .locale(getLocale())
                .other(getOther())
                .residential(getResidential())
                .modified(getModified())
                .externalReceiverID(getExternalReceiverID())
                .departmentName(getDepartmentName())
                .iDNumber(getIDNumber())
                .taxNumber(getTaxNumber());
        builder.iDType = internalGetIDType();
        builder.taxType = internalGetTaxType();
        return builder;
    }

    /**
     * Class to build instances of {@link Receiver4}.
     */
    public static class Builder {
        private String street;
        private String city;
        private String region;
        private String postalCode;
        private String country;
        private String accountNumber;
        private String companyName;
        private String locale;
        private String other;
        private Boolean residential = false;
        private Boolean modified = false;
        private String externalReceiverID;
        private String departmentName;
        private String iDNumber;
        private OptionalNullable<IDTypeEnum> iDType;
        private String taxNumber;
        private OptionalNullable<TaxTypeEnum> taxType;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  street  String value for street.
         * @param  city  String value for city.
         * @param  region  String value for region.
         * @param  postalCode  String value for postalCode.
         * @param  country  String value for country.
         */
        public Builder(String street, String city, String region, String postalCode,
                String country) {
            this.street = street;
            this.city = city;
            this.region = region;
            this.postalCode = postalCode;
            this.country = country;
        }

        /**
         * Setter for street.
         * @param  street  String value for street.
         * @return Builder
         */
        public Builder street(String street) {
            this.street = street;
            return this;
        }

        /**
         * Setter for city.
         * @param  city  String value for city.
         * @return Builder
         */
        public Builder city(String city) {
            this.city = city;
            return this;
        }

        /**
         * Setter for region.
         * @param  region  String value for region.
         * @return Builder
         */
        public Builder region(String region) {
            this.region = region;
            return this;
        }

        /**
         * Setter for postalCode.
         * @param  postalCode  String value for postalCode.
         * @return Builder
         */
        public Builder postalCode(String postalCode) {
            this.postalCode = postalCode;
            return this;
        }

        /**
         * Setter for country.
         * @param  country  String value for country.
         * @return Builder
         */
        public Builder country(String country) {
            this.country = country;
            return this;
        }

        /**
         * Setter for accountNumber.
         * @param  accountNumber  String value for accountNumber.
         * @return Builder
         */
        public Builder accountNumber(String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        /**
         * Setter for companyName.
         * @param  companyName  String value for companyName.
         * @return Builder
         */
        public Builder companyName(String companyName) {
            this.companyName = companyName;
            return this;
        }

        /**
         * Setter for locale.
         * @param  locale  String value for locale.
         * @return Builder
         */
        public Builder locale(String locale) {
            this.locale = locale;
            return this;
        }

        /**
         * Setter for other.
         * @param  other  String value for other.
         * @return Builder
         */
        public Builder other(String other) {
            this.other = other;
            return this;
        }

        /**
         * Setter for residential.
         * @param  residential  Boolean value for residential.
         * @return Builder
         */
        public Builder residential(Boolean residential) {
            this.residential = residential;
            return this;
        }

        /**
         * Setter for modified.
         * @param  modified  Boolean value for modified.
         * @return Builder
         */
        public Builder modified(Boolean modified) {
            this.modified = modified;
            return this;
        }

        /**
         * Setter for externalReceiverID.
         * @param  externalReceiverID  String value for externalReceiverID.
         * @return Builder
         */
        public Builder externalReceiverID(String externalReceiverID) {
            this.externalReceiverID = externalReceiverID;
            return this;
        }

        /**
         * Setter for departmentName.
         * @param  departmentName  String value for departmentName.
         * @return Builder
         */
        public Builder departmentName(String departmentName) {
            this.departmentName = departmentName;
            return this;
        }

        /**
         * Setter for iDNumber.
         * @param  iDNumber  String value for iDNumber.
         * @return Builder
         */
        public Builder iDNumber(String iDNumber) {
            this.iDNumber = iDNumber;
            return this;
        }

        /**
         * Setter for iDType.
         * @param  iDType  IDTypeEnum value for iDType.
         * @return Builder
         */
        public Builder iDType(IDTypeEnum iDType) {
            this.iDType = OptionalNullable.of(iDType);
            return this;
        }

        /**
         * UnSetter for iDType.
         * @return Builder
         */
        public Builder unsetIDType() {
            iDType = null;
            return this;
        }

        /**
         * Setter for taxNumber.
         * @param  taxNumber  String value for taxNumber.
         * @return Builder
         */
        public Builder taxNumber(String taxNumber) {
            this.taxNumber = taxNumber;
            return this;
        }

        /**
         * Setter for taxType.
         * @param  taxType  TaxTypeEnum value for taxType.
         * @return Builder
         */
        public Builder taxType(TaxTypeEnum taxType) {
            this.taxType = OptionalNullable.of(taxType);
            return this;
        }

        /**
         * UnSetter for taxType.
         * @return Builder
         */
        public Builder unsetTaxType() {
            taxType = null;
            return this;
        }

        /**
         * Builds a new {@link Receiver4} object using the set fields.
         * @return {@link Receiver4}
         */
        public Receiver4 build() {
            return new Receiver4(street, city, region, postalCode, country, accountNumber,
                    companyName, locale, other, residential, modified, externalReceiverID,
                    departmentName, iDNumber, iDType, taxNumber, taxType);
        }
    }
}
