/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for RecordIdentifiers7 type.
 */
public class RecordIdentifiers7 {
    private List<RecordIdentifier5> recordIdentifier;

    /**
     * Default constructor.
     */
    public RecordIdentifiers7() {
    }

    /**
     * Initialization constructor.
     * @param  recordIdentifier  List of RecordIdentifier5 value for recordIdentifier.
     */
    public RecordIdentifiers7(
            List<RecordIdentifier5> recordIdentifier) {
        this.recordIdentifier = recordIdentifier;
    }

    /**
     * Getter for RecordIdentifier.
     * Inner container for transaction identifiers.
     * @return Returns the List of RecordIdentifier5
     */
    @JsonGetter("RecordIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "RecordIdentifier")
    public List<RecordIdentifier5> getRecordIdentifier() {
        return recordIdentifier;
    }

    /**
     * Setter for RecordIdentifier.
     * Inner container for transaction identifiers.
     * @param recordIdentifier Value for List of RecordIdentifier5
     */
    @JsonSetter("RecordIdentifier")
    public void setRecordIdentifier(List<RecordIdentifier5> recordIdentifier) {
        this.recordIdentifier = recordIdentifier;
    }

    /**
     * Converts this RecordIdentifiers7 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RecordIdentifiers7 [" + "recordIdentifier=" + recordIdentifier + "]";
    }

    /**
     * Builds a new {@link RecordIdentifiers7.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RecordIdentifiers7.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .recordIdentifier(getRecordIdentifier());
        return builder;
    }

    /**
     * Class to build instances of {@link RecordIdentifiers7}.
     */
    public static class Builder {
        private List<RecordIdentifier5> recordIdentifier;



        /**
         * Setter for recordIdentifier.
         * @param  recordIdentifier  List of RecordIdentifier5 value for recordIdentifier.
         * @return Builder
         */
        public Builder recordIdentifier(List<RecordIdentifier5> recordIdentifier) {
            this.recordIdentifier = recordIdentifier;
            return this;
        }

        /**
         * Builds a new {@link RecordIdentifiers7} object using the set fields.
         * @return {@link RecordIdentifiers7}
         */
        public RecordIdentifiers7 build() {
            return new RecordIdentifiers7(recordIdentifier);
        }
    }
}
