/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for RecordIdentifier type.
 */
public class RecordIdentifier {
    private Keys keys;

    /**
     * Default constructor.
     */
    public RecordIdentifier() {
    }

    /**
     * Initialization constructor.
     * @param  keys  Keys value for keys.
     */
    public RecordIdentifier(
            Keys keys) {
        this.keys = keys;
    }

    /**
     * Getter for Keys.
     * Container for transaction identifiers to be stored.
     * @return Returns the Keys
     */
    @JsonGetter("Keys")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Keys")
    public Keys getKeys() {
        return keys;
    }

    /**
     * Setter for Keys.
     * Container for transaction identifiers to be stored.
     * @param keys Value for Keys
     */
    @JsonSetter("Keys")
    public void setKeys(Keys keys) {
        this.keys = keys;
    }

    /**
     * Converts this RecordIdentifier into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RecordIdentifier [" + "keys=" + keys + "]";
    }

    /**
     * Builds a new {@link RecordIdentifier.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RecordIdentifier.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .keys(getKeys());
        return builder;
    }

    /**
     * Class to build instances of {@link RecordIdentifier}.
     */
    public static class Builder {
        private Keys keys;



        /**
         * Setter for keys.
         * @param  keys  Keys value for keys.
         * @return Builder
         */
        public Builder keys(Keys keys) {
            this.keys = keys;
            return this;
        }

        /**
         * Builds a new {@link RecordIdentifier} object using the set fields.
         * @return {@link RecordIdentifier}
         */
        public RecordIdentifier build() {
            return new RecordIdentifier(keys);
        }
    }
}
