/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for RecordIdentifiers1 type.
 */
public class RecordIdentifiers1 {
    private RecordIdentifier recordIdentifier;

    /**
     * Default constructor.
     */
    public RecordIdentifiers1() {
    }

    /**
     * Initialization constructor.
     * @param  recordIdentifier  RecordIdentifier value for recordIdentifier.
     */
    public RecordIdentifiers1(
            RecordIdentifier recordIdentifier) {
        this.recordIdentifier = recordIdentifier;
    }

    /**
     * Getter for RecordIdentifier.
     * Inner container for transaction identifiers.
     * @return Returns the RecordIdentifier
     */
    @JsonGetter("RecordIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "RecordIdentifier")
    public RecordIdentifier getRecordIdentifier() {
        return recordIdentifier;
    }

    /**
     * Setter for RecordIdentifier.
     * Inner container for transaction identifiers.
     * @param recordIdentifier Value for RecordIdentifier
     */
    @JsonSetter("RecordIdentifier")
    public void setRecordIdentifier(RecordIdentifier recordIdentifier) {
        this.recordIdentifier = recordIdentifier;
    }

    /**
     * Converts this RecordIdentifiers1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RecordIdentifiers1 [" + "recordIdentifier=" + recordIdentifier + "]";
    }

    /**
     * Builds a new {@link RecordIdentifiers1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RecordIdentifiers1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .recordIdentifier(getRecordIdentifier());
        return builder;
    }

    /**
     * Class to build instances of {@link RecordIdentifiers1}.
     */
    public static class Builder {
        private RecordIdentifier recordIdentifier;



        /**
         * Setter for recordIdentifier.
         * @param  recordIdentifier  RecordIdentifier value for recordIdentifier.
         * @return Builder
         */
        public Builder recordIdentifier(RecordIdentifier recordIdentifier) {
            this.recordIdentifier = recordIdentifier;
            return this;
        }

        /**
         * Builds a new {@link RecordIdentifiers1} object using the set fields.
         * @return {@link RecordIdentifiers1}
         */
        public RecordIdentifiers1 build() {
            return new RecordIdentifiers1(recordIdentifier);
        }
    }
}
