/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for RecordIdentifier1 type.
 */
public class RecordIdentifier1 {
    private int recordIdentifierID;
    private Keys keys;

    /**
     * Default constructor.
     */
    public RecordIdentifier1() {
    }

    /**
     * Initialization constructor.
     * @param  recordIdentifierID  int value for recordIdentifierID.
     * @param  keys  Keys value for keys.
     */
    public RecordIdentifier1(
            int recordIdentifierID,
            Keys keys) {
        this.recordIdentifierID = recordIdentifierID;
        this.keys = keys;
    }

    /**
     * Getter for RecordIdentifierID.
     * Unique identifier for the record identifier record.
     * @return Returns the int
     */
    @JsonGetter("RecordIdentifierID")
    @XmlElement(name = "RecordIdentifierID")
    public int getRecordIdentifierID() {
        return recordIdentifierID;
    }

    /**
     * Setter for RecordIdentifierID.
     * Unique identifier for the record identifier record.
     * @param recordIdentifierID Value for int
     */
    @JsonSetter("RecordIdentifierID")
    public void setRecordIdentifierID(int recordIdentifierID) {
        this.recordIdentifierID = recordIdentifierID;
    }

    /**
     * Getter for Keys.
     * Container for transaction identifiers to be stored.
     * @return Returns the Keys
     */
    @JsonGetter("Keys")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Keys")
    public Keys getKeys() {
        return keys;
    }

    /**
     * Setter for Keys.
     * Container for transaction identifiers to be stored.
     * @param keys Value for Keys
     */
    @JsonSetter("Keys")
    public void setKeys(Keys keys) {
        this.keys = keys;
    }

    /**
     * Converts this RecordIdentifier1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RecordIdentifier1 [" + "recordIdentifierID=" + recordIdentifierID + ", keys=" + keys
                + "]";
    }

    /**
     * Builds a new {@link RecordIdentifier1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RecordIdentifier1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(recordIdentifierID)
                .keys(getKeys());
        return builder;
    }

    /**
     * Class to build instances of {@link RecordIdentifier1}.
     */
    public static class Builder {
        private int recordIdentifierID;
        private Keys keys;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  recordIdentifierID  int value for recordIdentifierID.
         */
        public Builder(int recordIdentifierID) {
            this.recordIdentifierID = recordIdentifierID;
        }

        /**
         * Setter for recordIdentifierID.
         * @param  recordIdentifierID  int value for recordIdentifierID.
         * @return Builder
         */
        public Builder recordIdentifierID(int recordIdentifierID) {
            this.recordIdentifierID = recordIdentifierID;
            return this;
        }

        /**
         * Setter for keys.
         * @param  keys  Keys value for keys.
         * @return Builder
         */
        public Builder keys(Keys keys) {
            this.keys = keys;
            return this;
        }

        /**
         * Builds a new {@link RecordIdentifier1} object using the set fields.
         * @return {@link RecordIdentifier1}
         */
        public RecordIdentifier1 build() {
            return new RecordIdentifier1(recordIdentifierID, keys);
        }
    }
}
