/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for ThirdPartyHazardous4 type.
 */
public class ThirdPartyHazardous4 {
    private Materials2 materials;
    private String materialKey;
    private String nameKey;
    private String innerPackagingType;
    private String packageInstructionType;
    private Boolean reportableQuantity;
    private Boolean mixture;
    private Boolean solution;
    private Boolean solid;
    private Boolean molten;
    private Boolean liquid;
    private Boolean stabilized;
    private Boolean waste;
    private Boolean hot;
    private Boolean marinePollutant;
    private Boolean maritimeOnly;
    private Boolean elevatedTemperature;
    private Boolean empty;
    private Boolean isMaterialNonHazmat;
    private Boolean isMaterialNotInPackage;
    private Boolean isInnerPackagingLiquid;
    private Boolean showMarinePollutantLabel;
    private Boolean showOrientationLabel;
    private String customInnerPackagingType;
    private String authorization;
    private String ergNumber;
    private String additionalQuantityInformation;
    private String toxicInhalationHazardZone;
    private String otherRequiredInformation;
    private String emptyPackageType;

    /**
     * Default constructor.
     */
    public ThirdPartyHazardous4() {
        reportableQuantity = false;
        mixture = false;
        solution = false;
        solid = false;
        molten = false;
        liquid = false;
        stabilized = false;
        waste = false;
        hot = false;
        marinePollutant = false;
        maritimeOnly = false;
        elevatedTemperature = false;
        empty = false;
        isMaterialNonHazmat = false;
        isMaterialNotInPackage = false;
        isInnerPackagingLiquid = false;
        showMarinePollutantLabel = false;
        showOrientationLabel = false;
    }

    /**
     * Initialization constructor.
     * @param  materials  Materials2 value for materials.
     * @param  materialKey  String value for materialKey.
     * @param  nameKey  String value for nameKey.
     * @param  innerPackagingType  String value for innerPackagingType.
     * @param  packageInstructionType  String value for packageInstructionType.
     * @param  reportableQuantity  Boolean value for reportableQuantity.
     * @param  mixture  Boolean value for mixture.
     * @param  solution  Boolean value for solution.
     * @param  solid  Boolean value for solid.
     * @param  molten  Boolean value for molten.
     * @param  liquid  Boolean value for liquid.
     * @param  stabilized  Boolean value for stabilized.
     * @param  waste  Boolean value for waste.
     * @param  hot  Boolean value for hot.
     * @param  marinePollutant  Boolean value for marinePollutant.
     * @param  maritimeOnly  Boolean value for maritimeOnly.
     * @param  elevatedTemperature  Boolean value for elevatedTemperature.
     * @param  empty  Boolean value for empty.
     * @param  isMaterialNonHazmat  Boolean value for isMaterialNonHazmat.
     * @param  isMaterialNotInPackage  Boolean value for isMaterialNotInPackage.
     * @param  isInnerPackagingLiquid  Boolean value for isInnerPackagingLiquid.
     * @param  showMarinePollutantLabel  Boolean value for showMarinePollutantLabel.
     * @param  showOrientationLabel  Boolean value for showOrientationLabel.
     * @param  customInnerPackagingType  String value for customInnerPackagingType.
     * @param  authorization  String value for authorization.
     * @param  ergNumber  String value for ergNumber.
     * @param  additionalQuantityInformation  String value for additionalQuantityInformation.
     * @param  toxicInhalationHazardZone  String value for toxicInhalationHazardZone.
     * @param  otherRequiredInformation  String value for otherRequiredInformation.
     * @param  emptyPackageType  String value for emptyPackageType.
     */
    public ThirdPartyHazardous4(
            Materials2 materials,
            String materialKey,
            String nameKey,
            String innerPackagingType,
            String packageInstructionType,
            Boolean reportableQuantity,
            Boolean mixture,
            Boolean solution,
            Boolean solid,
            Boolean molten,
            Boolean liquid,
            Boolean stabilized,
            Boolean waste,
            Boolean hot,
            Boolean marinePollutant,
            Boolean maritimeOnly,
            Boolean elevatedTemperature,
            Boolean empty,
            Boolean isMaterialNonHazmat,
            Boolean isMaterialNotInPackage,
            Boolean isInnerPackagingLiquid,
            Boolean showMarinePollutantLabel,
            Boolean showOrientationLabel,
            String customInnerPackagingType,
            String authorization,
            String ergNumber,
            String additionalQuantityInformation,
            String toxicInhalationHazardZone,
            String otherRequiredInformation,
            String emptyPackageType) {
        this.materials = materials;
        this.materialKey = materialKey;
        this.nameKey = nameKey;
        this.innerPackagingType = innerPackagingType;
        this.packageInstructionType = packageInstructionType;
        this.reportableQuantity = reportableQuantity;
        this.mixture = mixture;
        this.solution = solution;
        this.solid = solid;
        this.molten = molten;
        this.liquid = liquid;
        this.stabilized = stabilized;
        this.waste = waste;
        this.hot = hot;
        this.marinePollutant = marinePollutant;
        this.maritimeOnly = maritimeOnly;
        this.elevatedTemperature = elevatedTemperature;
        this.empty = empty;
        this.isMaterialNonHazmat = isMaterialNonHazmat;
        this.isMaterialNotInPackage = isMaterialNotInPackage;
        this.isInnerPackagingLiquid = isInnerPackagingLiquid;
        this.showMarinePollutantLabel = showMarinePollutantLabel;
        this.showOrientationLabel = showOrientationLabel;
        this.customInnerPackagingType = customInnerPackagingType;
        this.authorization = authorization;
        this.ergNumber = ergNumber;
        this.additionalQuantityInformation = additionalQuantityInformation;
        this.toxicInhalationHazardZone = toxicInhalationHazardZone;
        this.otherRequiredInformation = otherRequiredInformation;
        this.emptyPackageType = emptyPackageType;
    }

    /**
     * Getter for Materials.
     * Container for all material details.
     * @return Returns the Materials2
     */
    @JsonGetter("Materials")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Materials")
    public Materials2 getMaterials() {
        return materials;
    }

    /**
     * Setter for Materials.
     * Container for all material details.
     * @param materials Value for Materials2
     */
    @JsonSetter("Materials")
    public void setMaterials(Materials2 materials) {
        this.materials = materials;
    }

    /**
     * Getter for MaterialKey.
     * Hazardous material key for the product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("MaterialKey")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "MaterialKey")
    public String getMaterialKey() {
        return materialKey;
    }

    /**
     * Setter for MaterialKey.
     * Hazardous material key for the product for 3rd party hazardous partner.
     * @param materialKey Value for String
     */
    @JsonSetter("MaterialKey")
    public void setMaterialKey(String materialKey) {
        this.materialKey = materialKey;
    }

    /**
     * Getter for NameKey.
     * Hazardous name key for the product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("NameKey")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "NameKey")
    public String getNameKey() {
        return nameKey;
    }

    /**
     * Setter for NameKey.
     * Hazardous name key for the product for 3rd party hazardous partner.
     * @param nameKey Value for String
     */
    @JsonSetter("NameKey")
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    /**
     * Getter for InnerPackagingType.
     * Hazardous inner packaging type for the product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("InnerPackagingType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "InnerPackagingType")
    public String getInnerPackagingType() {
        return innerPackagingType;
    }

    /**
     * Setter for InnerPackagingType.
     * Hazardous inner packaging type for the product for 3rd party hazardous partner.
     * @param innerPackagingType Value for String
     */
    @JsonSetter("InnerPackagingType")
    public void setInnerPackagingType(String innerPackagingType) {
        this.innerPackagingType = innerPackagingType;
    }

    /**
     * Getter for PackageInstructionType.
     * Hazardous packaging instruction type for the product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("PackageInstructionType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "PackageInstructionType")
    public String getPackageInstructionType() {
        return packageInstructionType;
    }

    /**
     * Setter for PackageInstructionType.
     * Hazardous packaging instruction type for the product for 3rd party hazardous partner.
     * @param packageInstructionType Value for String
     */
    @JsonSetter("PackageInstructionType")
    public void setPackageInstructionType(String packageInstructionType) {
        this.packageInstructionType = packageInstructionType;
    }

    /**
     * Getter for ReportableQuantity.
     * Hazardous product quantity is reportable for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("ReportableQuantity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ReportableQuantity")
    public Boolean getReportableQuantity() {
        return reportableQuantity;
    }

    /**
     * Setter for ReportableQuantity.
     * Hazardous product quantity is reportable for 3rd party hazardous partner.
     * @param reportableQuantity Value for Boolean
     */
    @JsonSetter("ReportableQuantity")
    public void setReportableQuantity(Boolean reportableQuantity) {
        this.reportableQuantity = reportableQuantity;
    }

    /**
     * Getter for Mixture.
     * Hazardous product is mixture for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("Mixture")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Mixture")
    public Boolean getMixture() {
        return mixture;
    }

    /**
     * Setter for Mixture.
     * Hazardous product is mixture for 3rd party hazardous partner.
     * @param mixture Value for Boolean
     */
    @JsonSetter("Mixture")
    public void setMixture(Boolean mixture) {
        this.mixture = mixture;
    }

    /**
     * Getter for Solution.
     * Hazardous product is solution for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("Solution")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Solution")
    public Boolean getSolution() {
        return solution;
    }

    /**
     * Setter for Solution.
     * Hazardous product is solution for 3rd party hazardous partner.
     * @param solution Value for Boolean
     */
    @JsonSetter("Solution")
    public void setSolution(Boolean solution) {
        this.solution = solution;
    }

    /**
     * Getter for Solid.
     * Hazardous product is solid for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("Solid")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Solid")
    public Boolean getSolid() {
        return solid;
    }

    /**
     * Setter for Solid.
     * Hazardous product is solid for 3rd party hazardous partner.
     * @param solid Value for Boolean
     */
    @JsonSetter("Solid")
    public void setSolid(Boolean solid) {
        this.solid = solid;
    }

    /**
     * Getter for Molten.
     * Hazardous product is molten for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("Molten")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Molten")
    public Boolean getMolten() {
        return molten;
    }

    /**
     * Setter for Molten.
     * Hazardous product is molten for 3rd party hazardous partner.
     * @param molten Value for Boolean
     */
    @JsonSetter("Molten")
    public void setMolten(Boolean molten) {
        this.molten = molten;
    }

    /**
     * Getter for Liquid.
     * Hazardous product is liquid for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("Liquid")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Liquid")
    public Boolean getLiquid() {
        return liquid;
    }

    /**
     * Setter for Liquid.
     * Hazardous product is liquid for 3rd party hazardous partner.
     * @param liquid Value for Boolean
     */
    @JsonSetter("Liquid")
    public void setLiquid(Boolean liquid) {
        this.liquid = liquid;
    }

    /**
     * Getter for Stabilized.
     * Hazardous product is stabilized for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("Stabilized")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Stabilized")
    public Boolean getStabilized() {
        return stabilized;
    }

    /**
     * Setter for Stabilized.
     * Hazardous product is stabilized for 3rd party hazardous partner.
     * @param stabilized Value for Boolean
     */
    @JsonSetter("Stabilized")
    public void setStabilized(Boolean stabilized) {
        this.stabilized = stabilized;
    }

    /**
     * Getter for Waste.
     * Hazardous product is waste for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("Waste")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Waste")
    public Boolean getWaste() {
        return waste;
    }

    /**
     * Setter for Waste.
     * Hazardous product is waste for 3rd party hazardous partner.
     * @param waste Value for Boolean
     */
    @JsonSetter("Waste")
    public void setWaste(Boolean waste) {
        this.waste = waste;
    }

    /**
     * Getter for Hot.
     * Hazardous product is hot for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("Hot")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Hot")
    public Boolean getHot() {
        return hot;
    }

    /**
     * Setter for Hot.
     * Hazardous product is hot for 3rd party hazardous partner.
     * @param hot Value for Boolean
     */
    @JsonSetter("Hot")
    public void setHot(Boolean hot) {
        this.hot = hot;
    }

    /**
     * Getter for MarinePollutant.
     * Hazardous product is a marine pollutant for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("MarinePollutant")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "MarinePollutant")
    public Boolean getMarinePollutant() {
        return marinePollutant;
    }

    /**
     * Setter for MarinePollutant.
     * Hazardous product is a marine pollutant for 3rd party hazardous partner.
     * @param marinePollutant Value for Boolean
     */
    @JsonSetter("MarinePollutant")
    public void setMarinePollutant(Boolean marinePollutant) {
        this.marinePollutant = marinePollutant;
    }

    /**
     * Getter for MaritimeOnly.
     * Hazardous product is a maritime only for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("MaritimeOnly")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "MaritimeOnly")
    public Boolean getMaritimeOnly() {
        return maritimeOnly;
    }

    /**
     * Setter for MaritimeOnly.
     * Hazardous product is a maritime only for 3rd party hazardous partner.
     * @param maritimeOnly Value for Boolean
     */
    @JsonSetter("MaritimeOnly")
    public void setMaritimeOnly(Boolean maritimeOnly) {
        this.maritimeOnly = maritimeOnly;
    }

    /**
     * Getter for ElevatedTemperature.
     * Hazardous productis at elevated temperature for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("ElevatedTemperature")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ElevatedTemperature")
    public Boolean getElevatedTemperature() {
        return elevatedTemperature;
    }

    /**
     * Setter for ElevatedTemperature.
     * Hazardous productis at elevated temperature for 3rd party hazardous partner.
     * @param elevatedTemperature Value for Boolean
     */
    @JsonSetter("ElevatedTemperature")
    public void setElevatedTemperature(Boolean elevatedTemperature) {
        this.elevatedTemperature = elevatedTemperature;
    }

    /**
     * Getter for Empty.
     * Hazardous product container is empty for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("Empty")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Empty")
    public Boolean getEmpty() {
        return empty;
    }

    /**
     * Setter for Empty.
     * Hazardous product container is empty for 3rd party hazardous partner.
     * @param empty Value for Boolean
     */
    @JsonSetter("Empty")
    public void setEmpty(Boolean empty) {
        this.empty = empty;
    }

    /**
     * Getter for IsMaterialNonHazmat.
     * Marks material as NonHazardous for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("IsMaterialNonHazmat")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "IsMaterialNonHazmat")
    public Boolean getIsMaterialNonHazmat() {
        return isMaterialNonHazmat;
    }

    /**
     * Setter for IsMaterialNonHazmat.
     * Marks material as NonHazardous for 3rd party hazardous partner.
     * @param isMaterialNonHazmat Value for Boolean
     */
    @JsonSetter("IsMaterialNonHazmat")
    public void setIsMaterialNonHazmat(Boolean isMaterialNonHazmat) {
        this.isMaterialNonHazmat = isMaterialNonHazmat;
    }

    /**
     * Getter for IsMaterialNotInPackage.
     * Hazardous product not packaged for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("IsMaterialNotInPackage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "IsMaterialNotInPackage")
    public Boolean getIsMaterialNotInPackage() {
        return isMaterialNotInPackage;
    }

    /**
     * Setter for IsMaterialNotInPackage.
     * Hazardous product not packaged for 3rd party hazardous partner.
     * @param isMaterialNotInPackage Value for Boolean
     */
    @JsonSetter("IsMaterialNotInPackage")
    public void setIsMaterialNotInPackage(Boolean isMaterialNotInPackage) {
        this.isMaterialNotInPackage = isMaterialNotInPackage;
    }

    /**
     * Getter for IsInnerPackagingLiquid.
     * Hazardous product is in liquid packaging for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("IsInnerPackagingLiquid")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "IsInnerPackagingLiquid")
    public Boolean getIsInnerPackagingLiquid() {
        return isInnerPackagingLiquid;
    }

    /**
     * Setter for IsInnerPackagingLiquid.
     * Hazardous product is in liquid packaging for 3rd party hazardous partner.
     * @param isInnerPackagingLiquid Value for Boolean
     */
    @JsonSetter("IsInnerPackagingLiquid")
    public void setIsInnerPackagingLiquid(Boolean isInnerPackagingLiquid) {
        this.isInnerPackagingLiquid = isInnerPackagingLiquid;
    }

    /**
     * Getter for ShowMarinePollutantLabel.
     * Hazardous product show marine pollutant label for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("ShowMarinePollutantLabel")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ShowMarinePollutantLabel")
    public Boolean getShowMarinePollutantLabel() {
        return showMarinePollutantLabel;
    }

    /**
     * Setter for ShowMarinePollutantLabel.
     * Hazardous product show marine pollutant label for 3rd party hazardous partner.
     * @param showMarinePollutantLabel Value for Boolean
     */
    @JsonSetter("ShowMarinePollutantLabel")
    public void setShowMarinePollutantLabel(Boolean showMarinePollutantLabel) {
        this.showMarinePollutantLabel = showMarinePollutantLabel;
    }

    /**
     * Getter for ShowOrientationLabel.
     * Show orientation label for hazardous product for 3rd party hazardous partner.
     * @return Returns the Boolean
     */
    @JsonGetter("ShowOrientationLabel")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ShowOrientationLabel")
    public Boolean getShowOrientationLabel() {
        return showOrientationLabel;
    }

    /**
     * Setter for ShowOrientationLabel.
     * Show orientation label for hazardous product for 3rd party hazardous partner.
     * @param showOrientationLabel Value for Boolean
     */
    @JsonSetter("ShowOrientationLabel")
    public void setShowOrientationLabel(Boolean showOrientationLabel) {
        this.showOrientationLabel = showOrientationLabel;
    }

    /**
     * Getter for CustomInnerPackagingType.
     * Custom inner packaging type for Hazardous product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("CustomInnerPackagingType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "CustomInnerPackagingType")
    public String getCustomInnerPackagingType() {
        return customInnerPackagingType;
    }

    /**
     * Setter for CustomInnerPackagingType.
     * Custom inner packaging type for Hazardous product for 3rd party hazardous partner.
     * @param customInnerPackagingType Value for String
     */
    @JsonSetter("CustomInnerPackagingType")
    public void setCustomInnerPackagingType(String customInnerPackagingType) {
        this.customInnerPackagingType = customInnerPackagingType;
    }

    /**
     * Getter for Authorization.
     * Hazardous Authorization for the product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("Authorization")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Authorization")
    public String getAuthorization() {
        return authorization;
    }

    /**
     * Setter for Authorization.
     * Hazardous Authorization for the product for 3rd party hazardous partner.
     * @param authorization Value for String
     */
    @JsonSetter("Authorization")
    public void setAuthorization(String authorization) {
        this.authorization = authorization;
    }

    /**
     * Getter for ErgNumber.
     * Hazardous ErgNumber for the product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("ErgNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ErgNumber")
    public String getErgNumber() {
        return ergNumber;
    }

    /**
     * Setter for ErgNumber.
     * Hazardous ErgNumber for the product for 3rd party hazardous partner.
     * @param ergNumber Value for String
     */
    @JsonSetter("ErgNumber")
    public void setErgNumber(String ergNumber) {
        this.ergNumber = ergNumber;
    }

    /**
     * Getter for AdditionalQuantityInformation.
     * Hazardous additional quantity information for the product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("AdditionalQuantityInformation")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "AdditionalQuantityInformation")
    public String getAdditionalQuantityInformation() {
        return additionalQuantityInformation;
    }

    /**
     * Setter for AdditionalQuantityInformation.
     * Hazardous additional quantity information for the product for 3rd party hazardous partner.
     * @param additionalQuantityInformation Value for String
     */
    @JsonSetter("AdditionalQuantityInformation")
    public void setAdditionalQuantityInformation(String additionalQuantityInformation) {
        this.additionalQuantityInformation = additionalQuantityInformation;
    }

    /**
     * Getter for ToxicInhalationHazardZone.
     * Toxic Inhalation Hazard Zone for the product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("ToxicInhalationHazardZone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "ToxicInhalationHazardZone")
    public String getToxicInhalationHazardZone() {
        return toxicInhalationHazardZone;
    }

    /**
     * Setter for ToxicInhalationHazardZone.
     * Toxic Inhalation Hazard Zone for the product for 3rd party hazardous partner.
     * @param toxicInhalationHazardZone Value for String
     */
    @JsonSetter("ToxicInhalationHazardZone")
    public void setToxicInhalationHazardZone(String toxicInhalationHazardZone) {
        this.toxicInhalationHazardZone = toxicInhalationHazardZone;
    }

    /**
     * Getter for OtherRequiredInformation.
     * Other required information for hazardous product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("OtherRequiredInformation")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "OtherRequiredInformation")
    public String getOtherRequiredInformation() {
        return otherRequiredInformation;
    }

    /**
     * Setter for OtherRequiredInformation.
     * Other required information for hazardous product for 3rd party hazardous partner.
     * @param otherRequiredInformation Value for String
     */
    @JsonSetter("OtherRequiredInformation")
    public void setOtherRequiredInformation(String otherRequiredInformation) {
        this.otherRequiredInformation = otherRequiredInformation;
    }

    /**
     * Getter for EmptyPackageType.
     * Empty package type for hazardous product for 3rd party hazardous partner.
     * @return Returns the String
     */
    @JsonGetter("EmptyPackageType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "EmptyPackageType")
    public String getEmptyPackageType() {
        return emptyPackageType;
    }

    /**
     * Setter for EmptyPackageType.
     * Empty package type for hazardous product for 3rd party hazardous partner.
     * @param emptyPackageType Value for String
     */
    @JsonSetter("EmptyPackageType")
    public void setEmptyPackageType(String emptyPackageType) {
        this.emptyPackageType = emptyPackageType;
    }

    /**
     * Converts this ThirdPartyHazardous4 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ThirdPartyHazardous4 [" + "materials=" + materials + ", materialKey=" + materialKey
                + ", nameKey=" + nameKey + ", innerPackagingType=" + innerPackagingType
                + ", packageInstructionType=" + packageInstructionType + ", reportableQuantity="
                + reportableQuantity + ", mixture=" + mixture + ", solution=" + solution
                + ", solid=" + solid + ", molten=" + molten + ", liquid=" + liquid + ", stabilized="
                + stabilized + ", waste=" + waste + ", hot=" + hot + ", marinePollutant="
                + marinePollutant + ", maritimeOnly=" + maritimeOnly + ", elevatedTemperature="
                + elevatedTemperature + ", empty=" + empty + ", isMaterialNonHazmat="
                + isMaterialNonHazmat + ", isMaterialNotInPackage=" + isMaterialNotInPackage
                + ", isInnerPackagingLiquid=" + isInnerPackagingLiquid
                + ", showMarinePollutantLabel=" + showMarinePollutantLabel
                + ", showOrientationLabel=" + showOrientationLabel + ", customInnerPackagingType="
                + customInnerPackagingType + ", authorization=" + authorization + ", ergNumber="
                + ergNumber + ", additionalQuantityInformation=" + additionalQuantityInformation
                + ", toxicInhalationHazardZone=" + toxicInhalationHazardZone
                + ", otherRequiredInformation=" + otherRequiredInformation + ", emptyPackageType="
                + emptyPackageType + "]";
    }

    /**
     * Builds a new {@link ThirdPartyHazardous4.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ThirdPartyHazardous4.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .materials(getMaterials())
                .materialKey(getMaterialKey())
                .nameKey(getNameKey())
                .innerPackagingType(getInnerPackagingType())
                .packageInstructionType(getPackageInstructionType())
                .reportableQuantity(getReportableQuantity())
                .mixture(getMixture())
                .solution(getSolution())
                .solid(getSolid())
                .molten(getMolten())
                .liquid(getLiquid())
                .stabilized(getStabilized())
                .waste(getWaste())
                .hot(getHot())
                .marinePollutant(getMarinePollutant())
                .maritimeOnly(getMaritimeOnly())
                .elevatedTemperature(getElevatedTemperature())
                .empty(getEmpty())
                .isMaterialNonHazmat(getIsMaterialNonHazmat())
                .isMaterialNotInPackage(getIsMaterialNotInPackage())
                .isInnerPackagingLiquid(getIsInnerPackagingLiquid())
                .showMarinePollutantLabel(getShowMarinePollutantLabel())
                .showOrientationLabel(getShowOrientationLabel())
                .customInnerPackagingType(getCustomInnerPackagingType())
                .authorization(getAuthorization())
                .ergNumber(getErgNumber())
                .additionalQuantityInformation(getAdditionalQuantityInformation())
                .toxicInhalationHazardZone(getToxicInhalationHazardZone())
                .otherRequiredInformation(getOtherRequiredInformation())
                .emptyPackageType(getEmptyPackageType());
        return builder;
    }

    /**
     * Class to build instances of {@link ThirdPartyHazardous4}.
     */
    public static class Builder {
        private Materials2 materials;
        private String materialKey;
        private String nameKey;
        private String innerPackagingType;
        private String packageInstructionType;
        private Boolean reportableQuantity = false;
        private Boolean mixture = false;
        private Boolean solution = false;
        private Boolean solid = false;
        private Boolean molten = false;
        private Boolean liquid = false;
        private Boolean stabilized = false;
        private Boolean waste = false;
        private Boolean hot = false;
        private Boolean marinePollutant = false;
        private Boolean maritimeOnly = false;
        private Boolean elevatedTemperature = false;
        private Boolean empty = false;
        private Boolean isMaterialNonHazmat = false;
        private Boolean isMaterialNotInPackage = false;
        private Boolean isInnerPackagingLiquid = false;
        private Boolean showMarinePollutantLabel = false;
        private Boolean showOrientationLabel = false;
        private String customInnerPackagingType;
        private String authorization;
        private String ergNumber;
        private String additionalQuantityInformation;
        private String toxicInhalationHazardZone;
        private String otherRequiredInformation;
        private String emptyPackageType;



        /**
         * Setter for materials.
         * @param  materials  Materials2 value for materials.
         * @return Builder
         */
        public Builder materials(Materials2 materials) {
            this.materials = materials;
            return this;
        }

        /**
         * Setter for materialKey.
         * @param  materialKey  String value for materialKey.
         * @return Builder
         */
        public Builder materialKey(String materialKey) {
            this.materialKey = materialKey;
            return this;
        }

        /**
         * Setter for nameKey.
         * @param  nameKey  String value for nameKey.
         * @return Builder
         */
        public Builder nameKey(String nameKey) {
            this.nameKey = nameKey;
            return this;
        }

        /**
         * Setter for innerPackagingType.
         * @param  innerPackagingType  String value for innerPackagingType.
         * @return Builder
         */
        public Builder innerPackagingType(String innerPackagingType) {
            this.innerPackagingType = innerPackagingType;
            return this;
        }

        /**
         * Setter for packageInstructionType.
         * @param  packageInstructionType  String value for packageInstructionType.
         * @return Builder
         */
        public Builder packageInstructionType(String packageInstructionType) {
            this.packageInstructionType = packageInstructionType;
            return this;
        }

        /**
         * Setter for reportableQuantity.
         * @param  reportableQuantity  Boolean value for reportableQuantity.
         * @return Builder
         */
        public Builder reportableQuantity(Boolean reportableQuantity) {
            this.reportableQuantity = reportableQuantity;
            return this;
        }

        /**
         * Setter for mixture.
         * @param  mixture  Boolean value for mixture.
         * @return Builder
         */
        public Builder mixture(Boolean mixture) {
            this.mixture = mixture;
            return this;
        }

        /**
         * Setter for solution.
         * @param  solution  Boolean value for solution.
         * @return Builder
         */
        public Builder solution(Boolean solution) {
            this.solution = solution;
            return this;
        }

        /**
         * Setter for solid.
         * @param  solid  Boolean value for solid.
         * @return Builder
         */
        public Builder solid(Boolean solid) {
            this.solid = solid;
            return this;
        }

        /**
         * Setter for molten.
         * @param  molten  Boolean value for molten.
         * @return Builder
         */
        public Builder molten(Boolean molten) {
            this.molten = molten;
            return this;
        }

        /**
         * Setter for liquid.
         * @param  liquid  Boolean value for liquid.
         * @return Builder
         */
        public Builder liquid(Boolean liquid) {
            this.liquid = liquid;
            return this;
        }

        /**
         * Setter for stabilized.
         * @param  stabilized  Boolean value for stabilized.
         * @return Builder
         */
        public Builder stabilized(Boolean stabilized) {
            this.stabilized = stabilized;
            return this;
        }

        /**
         * Setter for waste.
         * @param  waste  Boolean value for waste.
         * @return Builder
         */
        public Builder waste(Boolean waste) {
            this.waste = waste;
            return this;
        }

        /**
         * Setter for hot.
         * @param  hot  Boolean value for hot.
         * @return Builder
         */
        public Builder hot(Boolean hot) {
            this.hot = hot;
            return this;
        }

        /**
         * Setter for marinePollutant.
         * @param  marinePollutant  Boolean value for marinePollutant.
         * @return Builder
         */
        public Builder marinePollutant(Boolean marinePollutant) {
            this.marinePollutant = marinePollutant;
            return this;
        }

        /**
         * Setter for maritimeOnly.
         * @param  maritimeOnly  Boolean value for maritimeOnly.
         * @return Builder
         */
        public Builder maritimeOnly(Boolean maritimeOnly) {
            this.maritimeOnly = maritimeOnly;
            return this;
        }

        /**
         * Setter for elevatedTemperature.
         * @param  elevatedTemperature  Boolean value for elevatedTemperature.
         * @return Builder
         */
        public Builder elevatedTemperature(Boolean elevatedTemperature) {
            this.elevatedTemperature = elevatedTemperature;
            return this;
        }

        /**
         * Setter for empty.
         * @param  empty  Boolean value for empty.
         * @return Builder
         */
        public Builder empty(Boolean empty) {
            this.empty = empty;
            return this;
        }

        /**
         * Setter for isMaterialNonHazmat.
         * @param  isMaterialNonHazmat  Boolean value for isMaterialNonHazmat.
         * @return Builder
         */
        public Builder isMaterialNonHazmat(Boolean isMaterialNonHazmat) {
            this.isMaterialNonHazmat = isMaterialNonHazmat;
            return this;
        }

        /**
         * Setter for isMaterialNotInPackage.
         * @param  isMaterialNotInPackage  Boolean value for isMaterialNotInPackage.
         * @return Builder
         */
        public Builder isMaterialNotInPackage(Boolean isMaterialNotInPackage) {
            this.isMaterialNotInPackage = isMaterialNotInPackage;
            return this;
        }

        /**
         * Setter for isInnerPackagingLiquid.
         * @param  isInnerPackagingLiquid  Boolean value for isInnerPackagingLiquid.
         * @return Builder
         */
        public Builder isInnerPackagingLiquid(Boolean isInnerPackagingLiquid) {
            this.isInnerPackagingLiquid = isInnerPackagingLiquid;
            return this;
        }

        /**
         * Setter for showMarinePollutantLabel.
         * @param  showMarinePollutantLabel  Boolean value for showMarinePollutantLabel.
         * @return Builder
         */
        public Builder showMarinePollutantLabel(Boolean showMarinePollutantLabel) {
            this.showMarinePollutantLabel = showMarinePollutantLabel;
            return this;
        }

        /**
         * Setter for showOrientationLabel.
         * @param  showOrientationLabel  Boolean value for showOrientationLabel.
         * @return Builder
         */
        public Builder showOrientationLabel(Boolean showOrientationLabel) {
            this.showOrientationLabel = showOrientationLabel;
            return this;
        }

        /**
         * Setter for customInnerPackagingType.
         * @param  customInnerPackagingType  String value for customInnerPackagingType.
         * @return Builder
         */
        public Builder customInnerPackagingType(String customInnerPackagingType) {
            this.customInnerPackagingType = customInnerPackagingType;
            return this;
        }

        /**
         * Setter for authorization.
         * @param  authorization  String value for authorization.
         * @return Builder
         */
        public Builder authorization(String authorization) {
            this.authorization = authorization;
            return this;
        }

        /**
         * Setter for ergNumber.
         * @param  ergNumber  String value for ergNumber.
         * @return Builder
         */
        public Builder ergNumber(String ergNumber) {
            this.ergNumber = ergNumber;
            return this;
        }

        /**
         * Setter for additionalQuantityInformation.
         * @param  additionalQuantityInformation  String value for additionalQuantityInformation.
         * @return Builder
         */
        public Builder additionalQuantityInformation(String additionalQuantityInformation) {
            this.additionalQuantityInformation = additionalQuantityInformation;
            return this;
        }

        /**
         * Setter for toxicInhalationHazardZone.
         * @param  toxicInhalationHazardZone  String value for toxicInhalationHazardZone.
         * @return Builder
         */
        public Builder toxicInhalationHazardZone(String toxicInhalationHazardZone) {
            this.toxicInhalationHazardZone = toxicInhalationHazardZone;
            return this;
        }

        /**
         * Setter for otherRequiredInformation.
         * @param  otherRequiredInformation  String value for otherRequiredInformation.
         * @return Builder
         */
        public Builder otherRequiredInformation(String otherRequiredInformation) {
            this.otherRequiredInformation = otherRequiredInformation;
            return this;
        }

        /**
         * Setter for emptyPackageType.
         * @param  emptyPackageType  String value for emptyPackageType.
         * @return Builder
         */
        public Builder emptyPackageType(String emptyPackageType) {
            this.emptyPackageType = emptyPackageType;
            return this;
        }

        /**
         * Builds a new {@link ThirdPartyHazardous4} object using the set fields.
         * @return {@link ThirdPartyHazardous4}
         */
        public ThirdPartyHazardous4 build() {
            return new ThirdPartyHazardous4(materials, materialKey, nameKey, innerPackagingType,
                    packageInstructionType, reportableQuantity, mixture, solution, solid, molten,
                    liquid, stabilized, waste, hot, marinePollutant, maritimeOnly,
                    elevatedTemperature, empty, isMaterialNonHazmat, isMaterialNotInPackage,
                    isInnerPackagingLiquid, showMarinePollutantLabel, showOrientationLabel,
                    customInnerPackagingType, authorization, ergNumber,
                    additionalQuantityInformation, toxicInhalationHazardZone,
                    otherRequiredInformation, emptyPackageType);
        }
    }
}
