/*
 * QuickStartAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.transtream.apimatic.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Warnings type.
 */
public class Warnings {
    private List<Warning> warning;

    /**
     * Default constructor.
     */
    public Warnings() {
    }

    /**
     * Initialization constructor.
     * @param  warning  List of Warning value for warning.
     */
    public Warnings(
            List<Warning> warning) {
        this.warning = warning;
    }

    /**
     * Getter for Warning.
     * Container for a single warning found whilst processing the transaction.
     * @return Returns the List of Warning
     */
    @JsonGetter("Warning")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlElement(name = "Warning")
    public List<Warning> getWarning() {
        return warning;
    }

    /**
     * Setter for Warning.
     * Container for a single warning found whilst processing the transaction.
     * @param warning Value for List of Warning
     */
    @JsonSetter("Warning")
    public void setWarning(List<Warning> warning) {
        this.warning = warning;
    }

    /**
     * Converts this Warnings into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Warnings [" + "warning=" + warning + "]";
    }

    /**
     * Builds a new {@link Warnings.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Warnings.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .warning(getWarning());
        return builder;
    }

    /**
     * Class to build instances of {@link Warnings}.
     */
    public static class Builder {
        private List<Warning> warning;



        /**
         * Setter for warning.
         * @param  warning  List of Warning value for warning.
         * @return Builder
         */
        public Builder warning(List<Warning> warning) {
            this.warning = warning;
            return this;
        }

        /**
         * Builds a new {@link Warnings} object using the set fields.
         * @return {@link Warnings}
         */
        public Warnings build() {
            return new Warnings(warning);
        }
    }
}
