/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.events.webhooks;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorStringCase;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import localhost3000.ApiHelper;
import localhost3000.events.SignatureVerificationResult;

/**
 * This is an event class for WebhooksCParsingResult.
 */
@JsonDeserialize(using = WebhooksCParsingResult.WebhooksCParsingResultDeserializer.class)
public abstract class WebhooksCParsingResult {
    
    /**
     *
     * @param stringEvent String value for stringEvent.
     * @return The StringEventCase object.
     */
    public static WebhooksCParsingResult fromStringEvent(String stringEvent) {
        return stringEvent == null ? null : new StringEventCase(stringEvent);
    }

    /**
     *
     * @param intEvent int value for intEvent.
     * @return The IntEventCase object.
     */
    public static WebhooksCParsingResult fromIntEvent(int intEvent) {
        return new IntEventCase(intEvent);
    }

    /**
     *
     * @param numberListEvent List of Double value for numberListEvent.
     * @return The NumberListEventCase object.
     */
    public static WebhooksCParsingResult fromNumberListEvent(List<Double> numberListEvent) {
        return numberListEvent == null ? null : new NumberListEventCase(numberListEvent);
    }

    /**
     *
     * @param stringMapEvent Map of String, value for stringMapEvent.
     * @return The StringMapEventCase object.
     */
    public static WebhooksCParsingResult fromStringMapEvent(Map<String, String> stringMapEvent) {
        return stringMapEvent == null ? null : new StringMapEventCase(stringMapEvent);
    }

    /**
     * Triggered when no event identified
     * @return The Unknown object.
     */
    public static WebhooksCParsingResult markUnknown() {
        return new Unknown();
    }

    /**
     * Triggered when signature verification failed
     * @param signatureVerificationResult SignatureVerificationResult value for signatureVerificationResult.
     * @return The SignatureVerificationFailed object.
     */
    public static WebhooksCParsingResult fromSignatureVerificationFailed(
            SignatureVerificationResult signatureVerificationResult) {
        return new SignatureVerificationFailed(signatureVerificationResult);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * Method to match from the provided some-of cases (any one).
     * @param <R> The type to return after applying callback.
     * @param someCases The some-of type cases callback.
     * @return The matched case, or null if not handled.
     */
    public <R> R matchSome(SomeCases<R> someCases) {
        return match(new Cases<R>() {

            @Override
            public R stringEvent(String stringEvent) {
                return someCases.stringEvent(stringEvent);
            }

            @Override
            public R intEvent(int intEvent) {
                return someCases.intEvent(intEvent);
            }

            @Override
            public R numberListEvent(List<Double> numberListEvent) {
                return someCases.numberListEvent(numberListEvent);
            }

            @Override
            public R stringMapEvent(Map<String, String> stringMapEvent) {
                return someCases.stringMapEvent(stringMapEvent);
            }

            @Override
            public R unknown() {
                return someCases.unknown();
            }

            @Override
            public R signatureVerificationFailed(SignatureVerificationResult signatureVerificationResult) {
                return someCases.signatureVerificationFailed(signatureVerificationResult);
            }
        });
    }

    /**
     * This is interface for WebhooksCParsingResult cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R stringEvent(String stringEvent);

        R intEvent(int intEvent);

        R numberListEvent(List<Double> numberListEvent);

        R stringMapEvent(Map<String, String> stringMapEvent);

        R unknown();

        R signatureVerificationFailed(SignatureVerificationResult signatureVerificationResult);
    }

    /**
     * This is interface for some-of cases (any subset).
     * @param <R> The type to return after applying callback.
     */
    public interface SomeCases<R> {
        default R stringEvent(String stringEvent) { return null; }

        default R intEvent(int intEvent) { return null; }

        default R numberListEvent(List<Double> numberListEvent) { return null; }

        default R stringMapEvent(Map<String, String> stringMapEvent) { return null; }

        default R unknown() { return null; }

        default R signatureVerificationFailed(SignatureVerificationResult signatureVerificationResult) { return null; }
    }

    /**
     * This is a implementation class for StringEventCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorStringCase
    @TypeCombinatorCase(type = "String")
    private static class StringEventCase extends WebhooksCParsingResult {

        @JsonValue
        private String stringEvent;

        StringEventCase(String stringEvent) {
            this.stringEvent = stringEvent;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.stringEvent(this.stringEvent);
        }

        @JsonCreator
        private StringEventCase(JsonNode jsonNode) throws IOException {
            if (jsonNode.isTextual()) {
                this.stringEvent = ApiHelper.deserialize(jsonNode, String.class);
            } else {
                throw new IllegalArgumentException();
            }
        }

        @Override
        public String toString() {
            return stringEvent.toString();
        }
    }

    /**
     * This is a implementation class for IntEventCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "int")
    private static class IntEventCase extends WebhooksCParsingResult {

        @JsonValue
        private int intEvent;

        IntEventCase(int intEvent) {
            this.intEvent = intEvent;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.intEvent(this.intEvent);
        }

        @JsonCreator
        private IntEventCase(JsonNode jsonNode) throws IOException {
            if (jsonNode.isInt()) {
                this.intEvent = ApiHelper.deserialize(jsonNode, Integer.class);
            } else {
                throw new IllegalArgumentException();
            }
        }

        @Override
        public String toString() {
            return String.valueOf(intEvent);
        }
    }

    /**
     * This is a implementation class for NumberListEventCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "List<Double>")
    private static class NumberListEventCase extends WebhooksCParsingResult {

        @JsonValue
        private List<Double> numberListEvent;

        NumberListEventCase(List<Double> numberListEvent) {
            this.numberListEvent = numberListEvent;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.numberListEvent(this.numberListEvent);
        }

        @JsonCreator
        private NumberListEventCase(JsonNode jsonNode) throws IOException {
            this.numberListEvent = ApiHelper.deserializeArray(jsonNode,
                Double[].class);
        }

        @Override
        public String toString() {
            return numberListEvent.toString();
        }
    }

    /**
     * This is a implementation class for StringMapEventCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "Map<String, String>")
    private static class StringMapEventCase extends WebhooksCParsingResult {

        @JsonValue
        private Map<String, String> stringMapEvent;

        StringMapEventCase(Map<String, String> stringMapEvent) {
            this.stringMapEvent = stringMapEvent;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.stringMapEvent(this.stringMapEvent);
        }

        @JsonCreator
        private StringMapEventCase(JsonNode jsonNode) throws IOException {
            this.stringMapEvent = ApiHelper.deserialize(jsonNode,
                new TypeReference<Map<String, String>>(){});
        }

        @Override
        public String toString() {
            return stringMapEvent.toString();
        }
    }

    /**
     * This is a implementation class for UnknownCase.
     */
    private static class Unknown extends WebhooksCParsingResult {

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.unknown();
        }

    }

    /**
     * This is a implementation class for SignatureVerificationFailedCase.
     */
    private static class SignatureVerificationFailed extends WebhooksCParsingResult {

        private SignatureVerificationResult signatureVerificationResult;

        SignatureVerificationFailed(SignatureVerificationResult signatureVerificationResult) {
            this.signatureVerificationResult = signatureVerificationResult;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.signatureVerificationFailed(this.signatureVerificationResult);
        }

    }

    /**
     * This is a custom deserializer class for WebhooksCParsingResult.
     */
    protected static class WebhooksCParsingResultDeserializer
            extends JsonDeserializer<WebhooksCParsingResult> {

        @Override
        public WebhooksCParsingResult deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(StringEventCase.class,
                    IntEventCase.class, NumberListEventCase.class, StringMapEventCase.class), true);
        }
    }

}
