/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.events.webhooks;

import localhost3000.ApiHelper;
import localhost3000.http.request.HttpRequest;
import java.util.concurrent.CompletableFuture;
import io.apimatic.core.utilities.CoreHelper;
import localhost3000.events.SignatureVerificationResult;
import io.apimatic.core.security.DigestCodecFactory;
import io.apimatic.coreinterfaces.http.request.Request;
import io.apimatic.coreinterfaces.security.SignatureVerifier;
import io.apimatic.core.security.HmacSignatureVerifier;
import java.nio.charset.StandardCharsets;
import java.util.function.Function;

/**
 * Manages Webhooks event processing, including signature verification and event payload parsing.
 */
public class WebhooksHandler {

    private final SignatureVerifier signatureVerifier;

    private static final Function<Request, byte[]> requestSignatureTemplateResolver =
            (request) -> {
                if (request == null) {
                    throw new IllegalArgumentException("request cannot be null");
                }
                String payload = request.getBody() instanceof String
                        ? request.getBody().toString()
                        : CoreHelper.trySerialize(request.getBody());
                String result = String.format("%s", payload);
                return result.getBytes(StandardCharsets.UTF_8);
            };

    /**
     * Initializes a new instance of the {@link WebhooksHandler} class with the specified secret key.
     *
     * @param secretKey The secret key used for HMAC signature verification.
     */
    public WebhooksHandler(String secretKey) {
        this.signatureVerifier = new HmacSignatureVerifier(
                secretKey,
                "X-Signature",
                DigestCodecFactory.hex(),
                requestSignatureTemplateResolver,
                "HmacSHA256",
                "{digest}"
        );
    }

    /**
     * Verifies the request signature and parses the event payload.
     *
     * @param request The HTTP request data containing the event payload and headers.
     * @return A {@link CompletableFuture} of {@link WebhooksParsingResult},
     *     a SignatureVerificationFailed case if the signature cannot be verified,
     *     or an Unknown case if parsing fails.
     */
    public CompletableFuture<WebhooksParsingResult> verifyAndParseEventAsync(HttpRequest request) {

        return verifyAsync(request).thenApply(result -> {
            if (!result.isSuccess()) {
                return WebhooksParsingResult.fromSignatureVerificationFailed(result);
            }

            return parseEvent(request);
        });
    }

    /**
     * Verifies the request signature and parses the event payload.
     *
     * @param request The HTTP request data containing the event payload and headers.
     * @return A {@link WebhooksParsingResult},
     *     a SignatureVerificationFailed case if the signature cannot be verified,
     *     or an Unknown case if parsing fails.
     */
    public WebhooksParsingResult verifyAndParseEvent(HttpRequest request) {

        SignatureVerificationResult result = verify(request);
        if (!result.isSuccess()) {
            return WebhooksParsingResult.fromSignatureVerificationFailed(result);
        }

        return parseEvent(request);
    }

    /**
     * Parse the incoming HTTP request data and deserialize it into an {@link WebhooksParsingResult} object.
     *
     * @param request The HTTP request data containing the event payload.
     * @return A {@link WebhooksParsingResult},
     *     an Unknown case if parsing fails.
     */
    private static WebhooksParsingResult parseEvent(HttpRequest request) {

        try {
            WebhooksParsingResult parsedEvent = ApiHelper.deserialize(request.getSerializedBody(), WebhooksParsingResult.class);
            return parsedEvent != null ? parsedEvent : WebhooksParsingResult.markUnknown();
        } catch (Exception e) {
            return WebhooksParsingResult.markUnknown();
        }
    }

    /**
     * Verifies the request using the configured signature verifier.
     *
     * @param request The HTTP request data to verify.
     * @return A {@link CompletableFuture} of {@link SignatureVerificationResult} representing the outcome of signature verification.
     */
    public CompletableFuture<SignatureVerificationResult> verifyAsync(HttpRequest request) {
        return signatureVerifier.verifyAsync(request)
                .thenApply(SignatureVerificationResult::fromVerificationResult);
    }

    /**
     * Verifies the request using the configured signature verifier.
     *
     * @param request The HTTP request data to verify.
     * @return A {@link SignatureVerificationResult} representing the outcome of signature verification.
     */
    public SignatureVerificationResult verify(HttpRequest request) {
        return verifyAsync(request).join();
    }
}