/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for AuditLogEvent type.
 */
public class AuditLogEvent {
    private EventType3 eventType;
    private String actor;
    private String action;
    private Object context;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public AuditLogEvent() {
    }

    /**
     * Initialization constructor.
     * @param  eventType  EventType3 value for eventType.
     * @param  actor  String value for actor.
     * @param  action  String value for action.
     * @param  context  Object value for context.
     */
    public AuditLogEvent(
            EventType3 eventType,
            String actor,
            String action,
            Object context) {
        this.eventType = eventType;
        this.actor = actor;
        this.action = action;
        this.context = context;
    }

    /**
     * Getter for EventType.
     * @return Returns the EventType3
     */
    @JsonGetter("eventType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EventType3 getEventType() {
        return eventType;
    }

    /**
     * Setter for EventType.
     * @param eventType Value for EventType3
     */
    @JsonSetter("eventType")
    public void setEventType(EventType3 eventType) {
        this.eventType = eventType;
    }

    /**
     * Getter for Actor.
     * @return Returns the String
     */
    @JsonGetter("actor")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getActor() {
        return actor;
    }

    /**
     * Setter for Actor.
     * @param actor Value for String
     */
    @JsonSetter("actor")
    public void setActor(String actor) {
        this.actor = actor;
    }

    /**
     * Getter for Action.
     * @return Returns the String
     */
    @JsonGetter("action")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAction() {
        return action;
    }

    /**
     * Setter for Action.
     * @param action Value for String
     */
    @JsonSetter("action")
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * Getter for Context.
     * @return Returns the Object
     */
    @JsonGetter("context")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getContext() {
        return context;
    }

    /**
     * Setter for Context.
     * @param context Value for Object
     */
    @JsonSetter("context")
    public void setContext(Object context) {
        this.context = context;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this AuditLogEvent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AuditLogEvent [" + "eventType=" + eventType + ", actor=" + actor + ", action="
                + action + ", context=" + context + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link AuditLogEvent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AuditLogEvent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .eventType(getEventType())
                .actor(getActor())
                .action(getAction())
                .context(getContext());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link AuditLogEvent}.
     */
    public static class Builder {
        private EventType3 eventType;
        private String actor;
        private String action;
        private Object context;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for eventType.
         * @param  eventType  EventType3 value for eventType.
         * @return Builder
         */
        public Builder eventType(EventType3 eventType) {
            this.eventType = eventType;
            return this;
        }

        /**
         * Setter for actor.
         * @param  actor  String value for actor.
         * @return Builder
         */
        public Builder actor(String actor) {
            this.actor = actor;
            return this;
        }

        /**
         * Setter for action.
         * @param  action  String value for action.
         * @return Builder
         */
        public Builder action(String action) {
            this.action = action;
            return this;
        }

        /**
         * Setter for context.
         * @param  context  Object value for context.
         * @return Builder
         */
        public Builder context(Object context) {
            this.context = context;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link AuditLogEvent} object using the set fields.
         * @return {@link AuditLogEvent}
         */
        public AuditLogEvent build() {
            AuditLogEvent model =
                    new AuditLogEvent(eventType, actor, action, context);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
