/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Event to be used.
 */
public enum Event {
    ENUM_ORDERCREATED,

    ENUM_ORDERUPDATED,

    ENUM_ORDERCANCELLED,

    ENUM_PAYMENTCOMPLETED,

    ENUM_PAYMENTFAILED,

    ENUM_FULFILLMENTCOMPLETED;

    private static TreeMap<String, Event> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_ORDERCREATED.value = "order.created";
        ENUM_ORDERUPDATED.value = "order.updated";
        ENUM_ORDERCANCELLED.value = "order.cancelled";
        ENUM_PAYMENTCOMPLETED.value = "payment.completed";
        ENUM_PAYMENTFAILED.value = "payment.failed";
        ENUM_FULFILLMENTCOMPLETED.value = "fulfillment.completed";

        valueMap.put("order.created", ENUM_ORDERCREATED);
        valueMap.put("order.updated", ENUM_ORDERUPDATED);
        valueMap.put("order.cancelled", ENUM_ORDERCANCELLED);
        valueMap.put("payment.completed", ENUM_PAYMENTCOMPLETED);
        valueMap.put("payment.failed", ENUM_PAYMENTFAILED);
        valueMap.put("fulfillment.completed", ENUM_FULFILLMENTCOMPLETED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Event constructFromString(String toConvert) throws IOException {
        Event enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Event fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Event values to list of string values.
     * @param toConvert The list of Event values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Event> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Event enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 