/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for OrderUpdatedEvent type.
 */
public class OrderUpdatedEvent {
    private EventType eventType;
    private int orderUpdatedId;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public OrderUpdatedEvent() {
    }

    /**
     * Initialization constructor.
     * @param  orderUpdatedId  int value for orderUpdatedId.
     * @param  eventType  EventType value for eventType.
     */
    public OrderUpdatedEvent(
            int orderUpdatedId,
            EventType eventType) {
        this.eventType = eventType;
        this.orderUpdatedId = orderUpdatedId;
    }

    /**
     * Initialization constructor.
     * @param  orderUpdatedId  int value for orderUpdatedId.
     */
    @JsonCreator
    protected OrderUpdatedEvent(
            @JsonProperty("orderUpdatedId") int orderUpdatedId) {
        this(orderUpdatedId, null);
    }

    /**
     * Getter for EventType.
     * @return Returns the EventType
     */
    @JsonGetter("eventType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EventType getEventType() {
        return eventType;
    }

    /**
     * Setter for EventType.
     * @param eventType Value for EventType
     */
    @JsonSetter("eventType")
    public void setEventType(EventType eventType) {
        this.eventType = eventType;
    }

    /**
     * Getter for OrderUpdatedId.
     * @return Returns the int
     */
    @JsonGetter("orderUpdatedId")
    public int getOrderUpdatedId() {
        return orderUpdatedId;
    }

    /**
     * Setter for OrderUpdatedId.
     * @param orderUpdatedId Value for int
     */
    @JsonSetter("orderUpdatedId")
    public void setOrderUpdatedId(int orderUpdatedId) {
        this.orderUpdatedId = orderUpdatedId;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this OrderUpdatedEvent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrderUpdatedEvent [" + "orderUpdatedId=" + orderUpdatedId + ", eventType="
                + eventType + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link OrderUpdatedEvent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrderUpdatedEvent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(orderUpdatedId)
                .eventType(getEventType());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link OrderUpdatedEvent}.
     */
    public static class Builder {
        private int orderUpdatedId;
        private EventType eventType;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  orderUpdatedId  int value for orderUpdatedId.
         */
        public Builder(int orderUpdatedId) {
            this.orderUpdatedId = orderUpdatedId;
        }

        /**
         * Setter for orderUpdatedId.
         * @param  orderUpdatedId  int value for orderUpdatedId.
         * @return Builder
         */
        public Builder orderUpdatedId(int orderUpdatedId) {
            this.orderUpdatedId = orderUpdatedId;
            return this;
        }

        /**
         * Setter for eventType.
         * @param  eventType  EventType value for eventType.
         * @return Builder
         */
        public Builder eventType(EventType eventType) {
            this.eventType = eventType;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link OrderUpdatedEvent} object using the set fields.
         * @return {@link OrderUpdatedEvent}
         */
        public OrderUpdatedEvent build() {
            OrderUpdatedEvent model =
                    new OrderUpdatedEvent(orderUpdatedId, eventType);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
