/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for SystemMaintenanceNotificationEvent type.
 */
public class SystemMaintenanceNotificationEvent {
    private String systemMaintenanceNotificationEventType;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SystemMaintenanceNotificationEvent() {
        systemMaintenanceNotificationEventType = "system.maintenance";
    }

    /**
     * Initialization constructor.
     * @param  systemMaintenanceNotificationEventType  String value for
     *         systemMaintenanceNotificationEventType.
     */
    @JsonCreator
    public SystemMaintenanceNotificationEvent(
            @JsonProperty("systemMaintenanceNotificationEventType") String systemMaintenanceNotificationEventType) {
        this.systemMaintenanceNotificationEventType = systemMaintenanceNotificationEventType;
    }

    /**
     * Getter for SystemMaintenanceNotificationEventType.
     * @return Returns the String
     */
    @JsonGetter("systemMaintenanceNotificationEventType")
    public String getSystemMaintenanceNotificationEventType() {
        return systemMaintenanceNotificationEventType;
    }

    /**
     * Setter for SystemMaintenanceNotificationEventType.
     * @param systemMaintenanceNotificationEventType Value for String
     */
    @JsonSetter("systemMaintenanceNotificationEventType")
    private void setSystemMaintenanceNotificationEventType(String systemMaintenanceNotificationEventType) {
        this.systemMaintenanceNotificationEventType = systemMaintenanceNotificationEventType;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SystemMaintenanceNotificationEvent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SystemMaintenanceNotificationEvent [" + "systemMaintenanceNotificationEventType="
                + systemMaintenanceNotificationEventType + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SystemMaintenanceNotificationEvent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SystemMaintenanceNotificationEvent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(systemMaintenanceNotificationEventType);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SystemMaintenanceNotificationEvent}.
     */
    public static class Builder {
        private String systemMaintenanceNotificationEventType = "system.maintenance";
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  systemMaintenanceNotificationEventType  String value for
         *         systemMaintenanceNotificationEventType.
         */
        public Builder(String systemMaintenanceNotificationEventType) {
            this.systemMaintenanceNotificationEventType = systemMaintenanceNotificationEventType;
        }

        /**
         * Setter for systemMaintenanceNotificationEventType.
         * @param  systemMaintenanceNotificationEventType  String value for
         *         systemMaintenanceNotificationEventType.
         * @return Builder
         */
        public Builder systemMaintenanceNotificationEventType(
                String systemMaintenanceNotificationEventType) {
            this.systemMaintenanceNotificationEventType = systemMaintenanceNotificationEventType;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SystemMaintenanceNotificationEvent} object using the set fields.
         * @return {@link SystemMaintenanceNotificationEvent}
         */
        public SystemMaintenanceNotificationEvent build() {
            SystemMaintenanceNotificationEvent model =
                    new SystemMaintenanceNotificationEvent(systemMaintenanceNotificationEventType);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
