/*
 * WebhooksAndCallbacksAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for UserStatusNotificationEvent type.
 */
public class UserStatusNotificationEvent {
    private String userStatusNotificationEventType;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public UserStatusNotificationEvent() {
        userStatusNotificationEventType = "user.status";
    }

    /**
     * Initialization constructor.
     * @param  userStatusNotificationEventType  String value for userStatusNotificationEventType.
     */
    @JsonCreator
    public UserStatusNotificationEvent(
            @JsonProperty("userStatusNotificationEventType") String userStatusNotificationEventType) {
        this.userStatusNotificationEventType = userStatusNotificationEventType;
    }

    /**
     * Getter for UserStatusNotificationEventType.
     * @return Returns the String
     */
    @JsonGetter("userStatusNotificationEventType")
    public String getUserStatusNotificationEventType() {
        return userStatusNotificationEventType;
    }

    /**
     * Setter for UserStatusNotificationEventType.
     * @param userStatusNotificationEventType Value for String
     */
    @JsonSetter("userStatusNotificationEventType")
    private void setUserStatusNotificationEventType(String userStatusNotificationEventType) {
        this.userStatusNotificationEventType = userStatusNotificationEventType;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this UserStatusNotificationEvent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UserStatusNotificationEvent [" + "userStatusNotificationEventType="
                + userStatusNotificationEventType + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link UserStatusNotificationEvent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UserStatusNotificationEvent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(userStatusNotificationEventType);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link UserStatusNotificationEvent}.
     */
    public static class Builder {
        private String userStatusNotificationEventType = "user.status";
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  userStatusNotificationEventType  String value for
         *         userStatusNotificationEventType.
         */
        public Builder(String userStatusNotificationEventType) {
            this.userStatusNotificationEventType = userStatusNotificationEventType;
        }

        /**
         * Setter for userStatusNotificationEventType.
         * @param  userStatusNotificationEventType  String value for
         *         userStatusNotificationEventType.
         * @return Builder
         */
        public Builder userStatusNotificationEventType(String userStatusNotificationEventType) {
            this.userStatusNotificationEventType = userStatusNotificationEventType;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link UserStatusNotificationEvent} object using the set fields.
         * @return {@link UserStatusNotificationEvent}
         */
        public UserStatusNotificationEvent build() {
            UserStatusNotificationEvent model =
                    new UserStatusNotificationEvent(userStatusNotificationEventType);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
